// Spanish conversation scenarios. Vocabulary packs live in es-vocab.js,
// keeping this module cheap to load eagerly with the app shell.

export const ES_SCENARIOS = [
  {
    id: 'es-cafe', title: 'At the Café', setup: 'You walk into a lively café in Madrid and want to order.',
    aiRole: 'You are a friendly but busy barista taking the order.',
    opener: '¡Buenos días! ¿Qué le pongo?', openerTranslation: 'Good morning! What can I get you?',
    curveball: 'the milk for the coffee has just run out',
    staticHints: ['Try: «Un café, por favor.»', 'Ask the price: «¿Cuánto es?»', 'Order food too: «Y una tostada.»'],
  },
  {
    id: 'es-directions', title: 'Asking for Directions', setup: 'You are lost and need to find the station.',
    aiRole: 'You are a helpful passer-by who knows the city well.',
    opener: 'Pareces perdido, ¿te ayudo?', openerTranslation: 'You look lost — can I help you?',
    curveball: 'the direct road is closed for a street festival',
    staticHints: ['Ask: «¿Dónde está la estación?»', 'Say you’re on foot: «Voy a pie.»', 'Thank them: «¡Muchas gracias!»'],
  },
  {
    id: 'es-hotel', title: 'Checking into a Hotel', setup: 'You arrive at your hotel and check in for two nights.',
    aiRole: 'You are the receptionist at the front desk.',
    opener: '¡Bienvenido! ¿Tiene una reserva?', openerTranslation: 'Welcome! Do you have a reservation?',
    curveball: 'the room they booked is not ready yet',
    staticHints: ['Say: «Tengo una habitación reservada.»', 'Give your name: «A nombre de …»', 'Ask about breakfast: «¿A qué hora es el desayuno?»'],
  },
  {
    id: 'es-shopping', title: 'At the Market', setup: 'You are buying fruit and vegetables at a market stall.',
    aiRole: 'You are a cheerful market vendor.',
    opener: '¡Todo fresquito hoy! ¿Qué le apetece?', openerTranslation: 'All fresh today! What would you like?',
    curveball: 'they are out of the oranges you wanted',
    staticHints: ['Ask for a kilo: «Un kilo de tomates, por favor.»', 'Ask the price: «¿Cuánto cuesta?»', 'Say that’s all: «Nada más, gracias.»'],
  },
  {
    id: 'es-smalltalk', title: 'Meeting Someone New', setup: 'You meet a new colleague at a work event.',
    aiRole: 'You are a friendly colleague making small talk.',
    opener: '¡Hola! Creo que aún no nos conocemos.', openerTranslation: 'Hi! I don’t think we’ve met yet.',
    curveball: 'they discover you both support the same football team',
    staticHints: ['Introduce yourself: «Me llamo …»', 'Say where you’re from: «Soy de …»', 'Ask about them: «¿Y a qué te dedicas?»'],
  },
  {
    id: 'es-doctor', title: 'At the Pharmacy', setup: 'You feel unwell and go to a pharmacy for advice.',
    aiRole: 'You are a knowledgeable pharmacist.',
    opener: 'Buenas, ¿en qué puedo ayudarle?', openerTranslation: 'Hello, how can I help you?',
    curveball: 'they ask whether you are allergic to anything',
    staticHints: ['Say what hurts: «Me duele la cabeza.»', 'Ask for something: «¿Tiene algo para esto?»', 'Ask how to take it: «¿Cada cuánto lo tomo?»'],
  },
  {
    id: 'es-restaurant', title: 'Dinner at a Restaurant', setup: 'You sit down for dinner and order a full meal.',
    aiRole: 'You are an attentive waiter at a traditional restaurant.',
    opener: '¡Buenas noches! ¿Ya han decidido?', openerTranslation: 'Good evening! Have you decided yet?',
    curveball: 'the dish you ask for is sold out tonight',
    staticHints: ['Order: «Para mí, la paella, por favor.»', 'Ask for a drink: «Y una copa de vino tinto.»', 'Ask for the bill: «La cuenta, por favor.»'],
  },
  {
    id: 'es-clothes', title: 'Shopping for Clothes', setup: 'You are in a clothes shop looking for a jacket.',
    aiRole: 'You are a helpful shop assistant.',
    opener: '¡Hola! ¿Le puedo ayudar?', openerTranslation: 'Hello! Can I help you?',
    curveball: 'they don’t have your size in the colour you want',
    staticHints: ['Say what you want: «Busco una chaqueta.»', 'Ask to try it on: «¿Me lo puedo probar?»', 'Ask the price: «¿Cuánto cuesta la chaqueta?»'],
  },
  {
    id: 'es-phone', title: 'A Phone Call', setup: 'You call a restaurant to book a table for Friday.',
    aiRole: 'You are the person answering the restaurant phone.',
    opener: 'Restaurante El Sol, ¿dígame?', openerTranslation: 'El Sol Restaurant, hello?',
    curveball: 'they are fully booked at the time you wanted',
    staticHints: ['Say why you call: «Quería reservar una mesa.»', 'Give details: «Para cuatro personas, el viernes.»', 'Confirm: «A las ocho, perfecto.»'],
  },
  {
    id: 'es-doctor2', title: 'At the Doctor', setup: 'You visit the doctor because you’ve felt unwell for days.',
    aiRole: 'You are a calm, thorough general practitioner.',
    opener: 'Buenos días, ¿qué le trae por aquí?', openerTranslation: 'Good morning, what brings you in?',
    curveball: 'they ask how long you’ve had the symptoms',
    staticHints: ['Describe it: «Tengo tos desde hace tres días.»', 'Say how you feel: «Me siento débil.»', 'Ask: «¿Qué debo hacer?»'],
  },
  {
    id: 'es-bank', title: 'At the Bank', setup: 'You want to open a bank account as a new resident.',
    aiRole: 'You are a helpful bank clerk.',
    opener: '¡Bienvenido! ¿En qué puedo ayudarle?', openerTranslation: 'Welcome! How can I help you?',
    curveball: 'they ask for a document you may not have with you',
    staticHints: ['State your goal: «Quiero abrir una cuenta.»', 'Ask what’s needed: «¿Qué necesito para eso?»', 'Ask about fees: «¿Tiene algún coste?»'],
  },
  {
    id: 'es-apartment', title: 'Viewing a Flat', setup: 'You view a flat you might rent and ask about the details.',
    aiRole: 'You are the landlord showing the flat.',
    opener: '¡Pase! Este es el salón.', openerTranslation: 'Come in! This is the living room.',
    curveball: 'the rent is higher than the advert said',
    staticHints: ['Ask the rent: «¿Cuánto es el alquiler?»', 'Ask what’s included: «¿Están incluidos los gastos?»', 'Ask to move in: «¿Desde cuándo está libre?»'],
  },
  {
    id: 'es-interview', title: 'A Job Interview', setup: 'You interview for a part-time job in a café.',
    aiRole: 'You are the café manager interviewing the candidate.',
    opener: 'Me alegra que haya venido. Cuénteme un poco sobre usted.', openerTranslation: 'Glad you came. Tell me a bit about yourself.',
    curveball: 'they ask whether you can work weekends',
    staticHints: ['Introduce yourself: «Me llamo … y soy estudiante.»', 'Say your experience: «Ya he trabajado en una cafetería.»', 'Show interest: «Aprendo rápido.»'],
  },
  {
    id: 'es-taxi', title: 'Taking a Taxi', setup: 'You take a taxi from the airport to your hotel.',
    aiRole: 'You are a chatty taxi driver.',
    opener: '¡Buenas noches! ¿A dónde le llevo?', openerTranslation: 'Good evening! Where can I take you?',
    curveball: 'there is heavy traffic and a longer route',
    staticHints: ['Give the address: «Al Hotel Estrella, por favor.»', 'Ask the price: «¿Cuánto cuesta más o menos?»', 'Ask the time: «¿Cuánto se tarda?»'],
  },
  {
    id: 'es-lost', title: 'Lost in the City', setup: 'You’re lost and your phone is dead. You ask a local for help.',
    aiRole: 'You are a friendly local who knows the area well.',
    opener: 'Pareces un poco perdido, ¿necesitas ayuda?', openerTranslation: 'You look a bit lost — do you need help?',
    curveball: 'the place you’re looking for has moved',
    staticHints: ['Say you’re lost: «Me he perdido.»', 'Ask the way: «¿Cómo llego al museo?»', 'Ask if it’s far: «¿Está lejos de aquí?»'],
  },
  {
    id: 'es-party', title: 'At a Party', setup: 'A friend brings you to a house party where you know no one.',
    aiRole: 'You are a sociable guest who starts chatting with you.',
    opener: '¡Hola! Creo que no nos conocemos. Soy Marta.', openerTranslation: 'Hi! I don’t think we’ve met. I’m Marta.',
    curveball: 'they invite you to join a game you don’t know',
    staticHints: ['Introduce yourself: «Hola, soy …»', 'Make small talk: «¿De qué conoces al anfitrión?»', 'Keep it going: «¿Y tú a qué te dedicas?»'],
  },
  {
    id: 'es-complaint', title: 'Returning a Product', setup: 'You return a jacket that has a broken zip.',
    aiRole: 'You are a shop assistant at the returns desk.',
    opener: 'Hola, ¿qué puedo hacer por usted?', openerTranslation: 'Hello, what can I do for you?',
    curveball: 'they ask for the receipt, which you may have lost',
    staticHints: ['Explain: «La cremallera está rota.»', 'Say what you want: «Quiero cambiar la chaqueta.»', 'Or: «¿Puedo recuperar mi dinero?»'],
  },
  {
    id: 'es-gym', title: 'Joining a Gym', setup: 'You ask about memberships at a local gym.',
    aiRole: 'You are an upbeat gym receptionist.',
    opener: '¡Hola! ¿Te interesa una membresía?', openerTranslation: 'Hi! Are you interested in a membership?',
    curveball: 'they push a more expensive plan',
    staticHints: ['Ask the price: «¿Cuánto cuesta al mes?»', 'Ask about hours: «¿Qué horario tenéis?»', 'Ask to try: «¿Puedo probarlo primero?»'],
  },
  {
    id: 'es-weekend', title: 'Making Weekend Plans', setup: 'A colleague asks what you’re doing this weekend.',
    aiRole: 'You are a friendly colleague suggesting plans.',
    opener: '¿Tienes planes para el fin de semana?', openerTranslation: 'Do you have plans for the weekend?',
    curveball: 'it’s supposed to rain on the day they suggest',
    staticHints: ['Answer: «Todavía nada fijo.»', 'Suggest: «¿Vamos al cine?»', 'Agree: «¡Suena bien, hagámoslo!»'],
  },
  {
    id: 'es-delivery', title: 'Ordering Delivery', setup: 'You order pizza by phone for delivery to your flat.',
    aiRole: 'You take orders at a busy pizzeria.',
    opener: 'Pizzería Bella, ¿qué va a querer?', openerTranslation: 'Pizzería Bella, what would you like?',
    curveball: 'one topping you want is unavailable',
    staticHints: ['Order: «Una pizza margarita, por favor.»', 'Give your address: «Mi dirección es …»', 'Ask the time: «¿Cuánto tarda el reparto?»'],
  },
];
