// Spanish content core — themed vocab packs and everyday conversation
// scenarios, in the same shape as the French library (the `fr` field holds the
// target-language term), so every screen, the SRS engine, TTS and the AI
// conversation work unchanged.

const w = (id, fr, en, emoji, freq, example, exampleEn, extra = {}) =>
  ({ id, fr, en, emoji, freq, example, exampleEn, syn: [], ant: [], coll: [], note: '', ...extra });

export const ES_VOCAB_PACKS = [
  {
    id: 'es-basics', title: 'Greetings & Basics', description: 'The words you need in the first five minutes.',
    entries: [
      w('es-hola', 'hola', 'hello', '👋', 1, '¡Hola! ¿Qué tal?', 'Hi! How’s it going?'),
      w('es-gracias', 'gracias', 'thank you', '🙏', 1, 'Muchas gracias por todo.', 'Thank you very much for everything.'),
      w('es-porfavor', 'por favor', 'please', '🤲', 1, 'Un café, por favor.', 'A coffee, please.'),
      w('es-si', 'sí', 'yes', '✅', 1, 'Sí, claro.', 'Yes, of course.'),
      w('es-no', 'no', 'no', '❌', 1, 'No, gracias.', 'No, thanks.'),
      w('es-adios', 'adiós', 'goodbye', '👋', 1, '¡Adiós, hasta mañana!', 'Bye, see you tomorrow!'),
      w('es-perdon', 'perdón', 'excuse me / sorry', '🙇', 2, 'Perdón, ¿dónde está la estación?', 'Excuse me, where is the station?'),
      w('es-bien', 'bien', 'well / fine', '👍', 1, 'Estoy muy bien, gracias.', 'I’m very well, thanks.'),
    ],
  },
  {
    id: 'es-people', title: 'People & Pronouns', description: 'Talk about yourself and others.',
    entries: [
      w('es-yo', 'yo', 'I', '🙋', 1, 'Yo me llamo Ana.', 'My name is Ana.'),
      w('es-tu', 'tú', 'you (informal)', '👉', 1, '¿De dónde eres tú?', 'Where are you from?'),
      w('es-usted', 'usted', 'you (formal)', '🎩', 1, '¿Puede usted ayudarme?', 'Can you help me?'),
      w('es-amigo', 'el amigo', 'friend (m)', '🧑', 2, 'Es mi mejor amigo.', 'He’s my best friend.'),
      w('es-familia', 'la familia', 'family', '👨‍👩‍👧', 2, 'Mi familia vive en Madrid.', 'My family lives in Madrid.'),
      w('es-mujer', 'la mujer', 'woman / wife', '👩', 1, 'Esa mujer es mi jefa.', 'That woman is my boss.'),
      w('es-hombre', 'el hombre', 'man', '👨', 1, 'El hombre lee el periódico.', 'The man is reading the newspaper.'),
      w('es-nino', 'el niño', 'child / boy', '🧒', 2, 'El niño juega en el parque.', 'The child is playing in the park.'),
    ],
  },
  {
    id: 'es-food', title: 'Food & Café', description: 'Order, eat and drink with confidence.',
    entries: [
      w('es-agua', 'el agua', 'water', '💧', 1, 'Un vaso de agua, por favor.', 'A glass of water, please.'),
      w('es-cafe', 'el café', 'coffee', '☕', 2, 'Me gusta el café con leche.', 'I like coffee with milk.'),
      w('es-pan', 'el pan', 'bread', '🍞', 2, 'El pan está recién hecho.', 'The bread is freshly made.'),
      w('es-cerveza', 'la cerveza', 'beer', '🍺', 2, 'Dos cervezas, por favor.', 'Two beers, please.'),
      w('es-comida', 'la comida', 'food / lunch', '🍽️', 2, 'La comida está deliciosa.', 'The food is delicious.'),
      w('es-cuenta', 'la cuenta', 'the bill', '🧾', 3, 'La cuenta, por favor.', 'The bill, please.'),
      w('es-rico', 'rico', 'tasty', '😋', 3, '¡Qué rico está el pastel!', 'The cake is so tasty!'),
      w('es-hambre', 'el hambre', 'hunger', '🤤', 3, 'Tengo hambre.', 'I’m hungry.'),
    ],
  },
  {
    id: 'es-travel', title: 'Travel & Getting Around', description: 'Stations, tickets and directions.',
    entries: [
      w('es-estacion', 'la estación', 'station', '🚉', 2, 'La estación está muy cerca.', 'The station is very close.'),
      w('es-tren', 'el tren', 'train', '🚆', 2, 'El tren llega tarde.', 'The train is arriving late.'),
      w('es-billete', 'el billete', 'ticket', '🎫', 3, 'Quiero un billete para Sevilla.', 'I want a ticket to Seville.'),
      w('es-izquierda', 'la izquierda', 'left', '⬅️', 2, 'Gira a la izquierda.', 'Turn left.'),
      w('es-derecha', 'la derecha', 'right', '➡️', 2, 'El banco está a la derecha.', 'The bank is on the right.'),
      w('es-recto', 'todo recto', 'straight ahead', '⬆️', 3, 'Sigue todo recto.', 'Go straight ahead.'),
      w('es-aeropuerto', 'el aeropuerto', 'airport', '✈️', 3, '¿Cómo llego al aeropuerto?', 'How do I get to the airport?'),
      w('es-mapa', 'el mapa', 'map', '🗺️', 2, '¿Tienes un mapa de la ciudad?', 'Do you have a map of the city?'),
    ],
  },
  {
    id: 'es-verbs', title: 'Everyday Verbs', description: 'The verbs you can’t speak without.',
    entries: [
      w('es-ser', 'ser', 'to be (permanent)', '🫥', 1, 'Soy de México.', 'I’m from Mexico.', { note: 'soy, eres, es …' }),
      w('es-estar', 'estar', 'to be (state/place)', '📍', 1, 'Estoy cansado.', 'I’m tired.', { note: 'estoy, estás, está …' }),
      w('es-tener', 'tener', 'to have', '🤲', 1, '¿Tienes tiempo?', 'Do you have time?'),
      w('es-ir', 'ir', 'to go', '🚶', 1, 'Vamos al cine.', 'We’re going to the cinema.'),
      w('es-hacer', 'hacer', 'to do / make', '🔨', 1, '¿Qué haces hoy?', 'What are you doing today?'),
      w('es-querer', 'querer', 'to want', '🙏', 1, 'Quiero ir a casa.', 'I want to go home.'),
      w('es-poder', 'poder', 'can / to be able to', '💪', 1, '¿Puedes ayudarme?', 'Can you help me?'),
      w('es-hablar', 'hablar', 'to speak', '🗣️', 2, '¿Habla usted inglés?', 'Do you speak English?'),
    ],
  },
  {
    id: 'es-time', title: 'Numbers & Time', description: 'Count, tell the time, make plans.',
    entries: [
      w('es-uno', 'uno', 'one', '1️⃣', 1, 'Quiero uno, por favor.', 'I’d like one, please.'),
      w('es-dos', 'dos', 'two', '2️⃣', 1, 'Dos cafés, por favor.', 'Two coffees, please.'),
      w('es-tres', 'tres', 'three', '3️⃣', 1, 'En tres minutos.', 'In three minutes.'),
      w('es-hoy', 'hoy', 'today', '📅', 1, 'Hoy es lunes.', 'Today is Monday.'),
      w('es-manana', 'mañana', 'tomorrow / morning', '🌅', 2, '¡Hasta mañana!', 'See you tomorrow!'),
      w('es-ahora', 'ahora', 'now', '⏱️', 1, 'Tenemos que irnos ahora.', 'We have to leave now.'),
      w('es-hora', 'la hora', 'hour / time', '🕐', 2, '¿Qué hora es?', 'What time is it?'),
      w('es-semana', 'la semana', 'week', '🗓️', 2, 'La próxima semana tengo vacaciones.', 'Next week I’m on holiday.'),
    ],
  },
  {
    id: 'es-home', title: 'House & Home', description: 'Rooms, furniture and everyday spaces.',
    entries: [
      w('es-casa', 'la casa', 'house / home', '🏠', 1, 'Mi casa tiene un jardín.', 'My house has a garden.'),
      w('es-piso', 'el piso', 'flat / apartment', '🏢', 2, 'Vivo en un piso pequeño.', 'I live in a small flat.'),
      w('es-cocina', 'la cocina', 'kitchen', '🍳', 2, 'La comida está en la cocina.', 'The food is in the kitchen.'),
      w('es-habitacion', 'la habitación', 'room / bedroom', '🚪', 2, 'Mi habitación está arriba.', 'My room is upstairs.'),
      w('es-cama', 'la cama', 'bed', '🛏️', 2, 'El niño duerme en la cama.', 'The child is sleeping in bed.'),
      w('es-mesa', 'la mesa', 'table', '🪑', 2, 'El libro está sobre la mesa.', 'The book is on the table.'),
      w('es-ventana', 'la ventana', 'window', '🪟', 2, 'Cierra la ventana, por favor.', 'Close the window, please.'),
      w('es-llave', 'la llave', 'key', '🔑', 3, 'He perdido mi llave.', 'I’ve lost my key.'),
    ],
  },
  {
    id: 'es-body', title: 'Health & Body', description: 'Body parts and talking to a doctor.',
    entries: [
      w('es-cabeza', 'la cabeza', 'head', '🧠', 2, 'Me duele la cabeza.', 'My head hurts.'),
      w('es-mano', 'la mano', 'hand', '✋', 2, 'Dame la mano.', 'Give me your hand.'),
      w('es-pie', 'el pie', 'foot', '🦶', 2, 'Me duele el pie.', 'My foot hurts.'),
      w('es-ojo', 'el ojo', 'eye', '👁️', 2, 'Tiene los ojos azules.', 'She has blue eyes.'),
      w('es-enfermo', 'enfermo', 'ill / sick', '🤒', 2, 'Hoy estoy enfermo.', 'I’m ill today.'),
      w('es-medico', 'el médico', 'doctor', '👨‍⚕️', 2, 'Tengo que ir al médico.', 'I have to go to the doctor.'),
      w('es-dolor', 'el dolor', 'pain', '💢', 3, 'Tengo dolor de espalda.', 'I have back pain.'),
      w('es-sano', 'sano', 'healthy', '💪', 3, 'La fruta es sana.', 'Fruit is healthy.'),
    ],
  },
  {
    id: 'es-weather', title: 'Nature & Weather', description: 'Talk about the sky and the seasons.',
    entries: [
      w('es-tiempo', 'el tiempo', 'weather', '🌤️', 2, '¿Qué tiempo hace hoy?', 'What’s the weather like today?'),
      w('es-sol', 'el sol', 'sun', '☀️', 2, 'Hace sol.', 'It’s sunny.'),
      w('es-lluvia', 'la lluvia', 'rain', '🌧️', 2, 'La lluvia no para.', 'The rain won’t stop.'),
      w('es-nieve', 'la nieve', 'snow', '❄️', 3, 'En invierno hay mucha nieve.', 'In winter there’s a lot of snow.'),
      w('es-viento', 'el viento', 'wind', '🌬️', 3, 'Hoy hace mucho viento.', 'It’s very windy today.'),
      w('es-frio', 'frío', 'cold', '🥶', 1, 'Tengo frío.', 'I’m cold.'),
      w('es-calor', 'el calor', 'heat / hot', '🔥', 1, 'Hace mucho calor.', 'It’s very hot.'),
      w('es-cielo', 'el cielo', 'sky', '🌌', 3, 'El cielo está despejado.', 'The sky is clear.'),
    ],
  },
  {
    id: 'es-work', title: 'Work & Office', description: 'Get through the working day.',
    entries: [
      w('es-trabajo', 'el trabajo', 'work / job', '💼', 2, 'Voy al trabajo.', 'I’m going to work.'),
      w('es-oficina', 'la oficina', 'office', '🏢', 2, 'Mi oficina está en el centro.', 'My office is in the centre.'),
      w('es-jefe', 'el jefe', 'boss', '👔', 2, 'Mi jefe es muy simpático.', 'My boss is very nice.'),
      w('es-reunion', 'la reunión', 'meeting', '📊', 3, 'La reunión empieza a las diez.', 'The meeting starts at ten.'),
      w('es-ordenador', 'el ordenador', 'computer', '💻', 2, 'Mi ordenador no funciona.', 'My computer isn’t working.'),
      w('es-correo', 'el correo', 'email / mail', '📧', 2, 'Te mando un correo.', 'I’ll send you an email.'),
      w('es-companero', 'el compañero', 'colleague', '🧑‍💼', 3, 'Es un buen compañero.', 'He’s a good colleague.'),
      w('es-cita', 'la cita', 'appointment', '📅', 3, 'Tengo una cita mañana.', 'I have an appointment tomorrow.'),
    ],
  },
  {
    id: 'es-feelings', title: 'Feelings & Moods', description: 'Say how you really feel.',
    entries: [
      w('es-feliz', 'feliz', 'happy', '😊', 2, 'Estoy muy feliz.', 'I’m very happy.'),
      w('es-triste', 'triste', 'sad', '😢', 2, '¿Por qué estás triste?', 'Why are you sad?'),
      w('es-cansado', 'cansado', 'tired', '😴', 2, 'Hoy estoy muy cansado.', 'I’m very tired today.'),
      w('es-enfadado', 'enfadado', 'angry', '😠', 3, 'Está enfadado conmigo.', 'He’s angry with me.'),
      w('es-miedo', 'el miedo', 'fear', '😨', 3, 'Tengo miedo a los perros.', 'I’m afraid of dogs.'),
      w('es-amor', 'el amor', 'love', '❤️', 2, 'El amor lo puede todo.', 'Love can do anything.'),
      w('es-contento', 'contento', 'glad / pleased', '🙂', 2, 'Estoy contento de verte.', 'I’m glad to see you.'),
      w('es-nervioso', 'nervioso', 'nervous', '😰', 3, 'Antes del examen estoy nervioso.', 'Before the exam I’m nervous.'),
    ],
  },
  {
    id: 'es-clothing', title: 'Clothing & Colours', description: 'Get dressed and describe it.',
    entries: [
      w('es-ropa', 'la ropa', 'clothing', '👕', 2, 'Compro ropa nueva.', 'I’m buying new clothes.'),
      w('es-camisa', 'la camisa', 'shirt', '👔', 2, 'La camisa es demasiado grande.', 'The shirt is too big.'),
      w('es-pantalon', 'el pantalón', 'trousers', '👖', 2, 'El pantalón me queda bien.', 'The trousers fit me well.'),
      w('es-zapatos', 'los zapatos', 'shoes', '👟', 2, 'Tus zapatos son bonitos.', 'Your shoes are nice.'),
      w('es-rojo', 'rojo', 'red', '🔴', 1, 'Me gusta el vestido rojo.', 'I like the red dress.'),
      w('es-azul', 'azul', 'blue', '🔵', 1, 'El cielo es azul.', 'The sky is blue.'),
      w('es-verde', 'verde', 'green', '🟢', 1, 'La hierba es verde.', 'The grass is green.'),
      w('es-negro', 'negro', 'black', '⚫', 1, 'Lleva un abrigo negro.', 'He’s wearing a black coat.'),
    ],
  },
  {
    id: 'es-shopping', title: 'Shopping & Money', description: 'Buy, pay and haggle.',
    entries: [
      w('es-dinero', 'el dinero', 'money', '💶', 2, 'No llevo dinero encima.', 'I don’t have money on me.'),
      w('es-comprar', 'comprar', 'to buy', '🛒', 2, 'Quiero comprar pan.', 'I want to buy bread.'),
      w('es-caro', 'caro', 'expensive', '💸', 2, 'Esto es demasiado caro.', 'This is too expensive.'),
      w('es-barato', 'barato', 'cheap', '🏷️', 3, 'La camisa era muy barata.', 'The shirt was very cheap.'),
      w('es-precio', 'el precio', 'price', '🔖', 2, '¿Cuál es el precio?', 'What’s the price?'),
      w('es-tienda', 'la tienda', 'shop', '🏬', 2, 'La tienda abre a las nueve.', 'The shop opens at nine.'),
      w('es-pagar', 'pagar', 'to pay', '💳', 2, '¿Puedo pagar con tarjeta?', 'Can I pay by card?'),
      w('es-caja', 'la caja', 'checkout / till', '🧾', 3, 'Pague en la caja, por favor.', 'Please pay at the till.'),
    ],
  },
  {
    id: 'es-adjectives', title: 'Everyday Adjectives', description: 'Describe almost anything.',
    entries: [
      w('es-grande', 'grande', 'big', '🔼', 1, 'Es una casa grande.', 'It’s a big house.'),
      w('es-pequeno', 'pequeño', 'small', '🔽', 1, 'Un perro pequeño.', 'A small dog.'),
      w('es-nuevo', 'nuevo', 'new', '✨', 1, 'Tengo un móvil nuevo.', 'I have a new phone.'),
      w('es-viejo', 'viejo', 'old', '📜', 1, 'Es un coche viejo.', 'It’s an old car.'),
      w('es-bonito', 'bonito', 'pretty / nice', '😍', 1, '¡Qué día tan bonito!', 'What a beautiful day!'),
      w('es-rapido', 'rápido', 'fast', '⚡', 2, 'El tren es muy rápido.', 'The train is very fast.'),
      w('es-lento', 'lento', 'slow', '🐌', 2, 'Conduce despacio, es lento.', 'Drive slowly, it’s slow.'),
      w('es-importante', 'importante', 'important', '❗', 2, 'Esto es muy importante.', 'This is very important.'),
    ],
  },
  {
    id: 'es-questions', title: 'Question Words', description: 'Ask anything you need.',
    entries: [
      w('es-quien', 'quién', 'who', '🙋', 1, '¿Quién es?', 'Who is it?'),
      w('es-que', 'qué', 'what', '❓', 1, '¿Qué haces?', 'What are you doing?'),
      w('es-donde', 'dónde', 'where', '📍', 1, '¿Dónde vives?', 'Where do you live?'),
      w('es-cuando', 'cuándo', 'when', '🕐', 1, '¿Cuándo vienes?', 'When are you coming?'),
      w('es-porque', 'por qué', 'why', '🤔', 1, '¿Por qué te ríes?', 'Why are you laughing?'),
      w('es-como', 'cómo', 'how', '🔧', 1, '¿Cómo estás?', 'How are you?'),
      w('es-cual', 'cuál', 'which', '🔀', 2, '¿Cuál prefieres?', 'Which do you prefer?'),
      w('es-cuanto', 'cuánto', 'how much / many', '🔢', 2, '¿Cuánto cuesta?', 'How much does it cost?'),
    ],
  },
  {
    id: 'es-connectors', title: 'Connectors & Discourse', description: 'Link ideas and sound fluent.',
    entries: [
      w('es-y', 'y', 'and', '➕', 1, 'Pan y queso.', 'Bread and cheese.'),
      w('es-pero', 'pero', 'but', '↔️', 1, 'Quiero, pero no puedo.', 'I want to, but I can’t.'),
      w('es-porqueconj', 'porque', 'because', '💡', 1, 'Me quedo porque llueve.', 'I’m staying because it’s raining.'),
      w('es-asique', 'así que', 'so', '➡️', 2, 'Era tarde, así que me fui.', 'It was late, so I left.'),
      w('es-poreso', 'por eso', 'that’s why', '🗨️', 2, 'Por eso no vine.', 'That’s why I didn’t come.'),
      w('es-sinembargo', 'sin embargo', 'however', '🔁', 3, 'Llovía; sin embargo, salimos.', 'It was raining; however, we went out.'),
      w('es-primero', 'primero', 'first', '1️⃣', 2, 'Primero comemos, luego salimos.', 'First we eat, then we go out.'),
      w('es-luego', 'luego', 'then / later', '⏭️', 1, 'Primero el trabajo, luego el placer.', 'Work first, then pleasure.'),
    ],
  },
  {
    id: 'es-animals', title: 'Animals', description: 'Pets, farm and wild animals.',
    entries: [
      w('es-perro', 'el perro', 'dog', '🐕', 2, 'El perro ladra fuerte.', 'The dog is barking loudly.'),
      w('es-gato', 'el gato', 'cat', '🐈', 2, 'El gato duerme en el sofá.', 'The cat is sleeping on the sofa.'),
      w('es-pajaro', 'el pájaro', 'bird', '🐦', 2, 'Un pájaro canta en el árbol.', 'A bird is singing in the tree.'),
      w('es-caballo', 'el caballo', 'horse', '🐎', 3, 'El caballo corre rápido.', 'The horse runs fast.'),
      w('es-pez', 'el pez', 'fish (live)', '🐟', 2, 'Hay un pez en el acuario.', 'There’s a fish in the tank.'),
      w('es-vaca', 'la vaca', 'cow', '🐄', 3, 'La vaca da leche.', 'The cow gives milk.'),
      w('es-animal', 'el animal', 'animal', '🐾', 2, 'Mi animal favorito es el elefante.', 'My favourite animal is the elephant.'),
      w('es-oso', 'el oso', 'bear', '🐻', 3, 'En el bosque viven osos.', 'Bears live in the forest.'),
    ],
  },
  {
    id: 'es-nature', title: 'Nature & Outdoors', description: 'Trees, mountains and the sea.',
    entries: [
      w('es-arbol', 'el árbol', 'tree', '🌳', 2, 'El árbol es muy alto.', 'The tree is very tall.'),
      w('es-flor', 'la flor', 'flower', '🌸', 2, 'Te regalo una flor.', 'I’m giving you a flower.'),
      w('es-montana', 'la montaña', 'mountain', '⛰️', 2, 'Subimos a la montaña.', 'We’re going up the mountain.'),
      w('es-lago', 'el lago', 'lake', '🏞️', 3, 'El lago está tranquilo hoy.', 'The lake is calm today.'),
      w('es-mar', 'el mar', 'sea', '🌊', 2, 'En verano vamos al mar.', 'In summer we go to the sea.'),
      w('es-bosque', 'el bosque', 'forest', '🌲', 2, 'El bosque es verde y tranquilo.', 'The forest is green and quiet.'),
      w('es-rio', 'el río', 'river', '🏞️', 3, 'El río cruza la ciudad.', 'The river crosses the city.'),
      w('es-naturaleza', 'la naturaleza', 'nature', '🍃', 2, 'Me encanta la naturaleza.', 'I love nature.'),
    ],
  },
];

export const ES_SCENARIOS = [
  {
    id: 'es-cafe', title: 'At the Café', setup: 'You walk into a lively café in Madrid and want to order.',
    aiRole: 'You are a friendly but busy barista taking the order.',
    opener: '¡Buenos días! ¿Qué le pongo?', openerTranslation: 'Good morning! What can I get you?',
    curveball: 'the milk for the coffee has just run out',
    staticHints: ['Try: «Un café, por favor.»', 'Ask the price: «¿Cuánto es?»', 'Order food too: «Y una tostada.»'],
  },
  {
    id: 'es-directions', title: 'Asking for Directions', setup: 'You are lost and need to find the station.',
    aiRole: 'You are a helpful passer-by who knows the city well.',
    opener: 'Pareces perdido, ¿te ayudo?', openerTranslation: 'You look lost — can I help you?',
    curveball: 'the direct road is closed for a street festival',
    staticHints: ['Ask: «¿Dónde está la estación?»', 'Say you’re on foot: «Voy a pie.»', 'Thank them: «¡Muchas gracias!»'],
  },
  {
    id: 'es-hotel', title: 'Checking into a Hotel', setup: 'You arrive at your hotel and check in for two nights.',
    aiRole: 'You are the receptionist at the front desk.',
    opener: '¡Bienvenido! ¿Tiene una reserva?', openerTranslation: 'Welcome! Do you have a reservation?',
    curveball: 'the room they booked is not ready yet',
    staticHints: ['Say: «Tengo una habitación reservada.»', 'Give your name: «A nombre de …»', 'Ask about breakfast: «¿A qué hora es el desayuno?»'],
  },
  {
    id: 'es-shopping', title: 'At the Market', setup: 'You are buying fruit and vegetables at a market stall.',
    aiRole: 'You are a cheerful market vendor.',
    opener: '¡Todo fresquito hoy! ¿Qué le apetece?', openerTranslation: 'All fresh today! What would you like?',
    curveball: 'they are out of the oranges you wanted',
    staticHints: ['Ask for a kilo: «Un kilo de tomates, por favor.»', 'Ask the price: «¿Cuánto cuesta?»', 'Say that’s all: «Nada más, gracias.»'],
  },
  {
    id: 'es-smalltalk', title: 'Meeting Someone New', setup: 'You meet a new colleague at a work event.',
    aiRole: 'You are a friendly colleague making small talk.',
    opener: '¡Hola! Creo que aún no nos conocemos.', openerTranslation: 'Hi! I don’t think we’ve met yet.',
    curveball: 'they discover you both support the same football team',
    staticHints: ['Introduce yourself: «Me llamo …»', 'Say where you’re from: «Soy de …»', 'Ask about them: «¿Y a qué te dedicas?»'],
  },
  {
    id: 'es-doctor', title: 'At the Pharmacy', setup: 'You feel unwell and go to a pharmacy for advice.',
    aiRole: 'You are a knowledgeable pharmacist.',
    opener: 'Buenas, ¿en qué puedo ayudarle?', openerTranslation: 'Hello, how can I help you?',
    curveball: 'they ask whether you are allergic to anything',
    staticHints: ['Say what hurts: «Me duele la cabeza.»', 'Ask for something: «¿Tiene algo para esto?»', 'Ask how to take it: «¿Cada cuánto lo tomo?»'],
  },
  {
    id: 'es-restaurant', title: 'Dinner at a Restaurant', setup: 'You sit down for dinner and order a full meal.',
    aiRole: 'You are an attentive waiter at a traditional restaurant.',
    opener: '¡Buenas noches! ¿Ya han decidido?', openerTranslation: 'Good evening! Have you decided yet?',
    curveball: 'the dish you ask for is sold out tonight',
    staticHints: ['Order: «Para mí, la paella, por favor.»', 'Ask for a drink: «Y una copa de vino tinto.»', 'Ask for the bill: «La cuenta, por favor.»'],
  },
  {
    id: 'es-clothes', title: 'Shopping for Clothes', setup: 'You are in a clothes shop looking for a jacket.',
    aiRole: 'You are a helpful shop assistant.',
    opener: '¡Hola! ¿Le puedo ayudar?', openerTranslation: 'Hello! Can I help you?',
    curveball: 'they don’t have your size in the colour you want',
    staticHints: ['Say what you want: «Busco una chaqueta.»', 'Ask to try it on: «¿Me lo puedo probar?»', 'Ask the price: «¿Cuánto cuesta la chaqueta?»'],
  },
  {
    id: 'es-phone', title: 'A Phone Call', setup: 'You call a restaurant to book a table for Friday.',
    aiRole: 'You are the person answering the restaurant phone.',
    opener: 'Restaurante El Sol, ¿dígame?', openerTranslation: 'El Sol Restaurant, hello?',
    curveball: 'they are fully booked at the time you wanted',
    staticHints: ['Say why you call: «Quería reservar una mesa.»', 'Give details: «Para cuatro personas, el viernes.»', 'Confirm: «A las ocho, perfecto.»'],
  },
  {
    id: 'es-doctor2', title: 'At the Doctor', setup: 'You visit the doctor because you’ve felt unwell for days.',
    aiRole: 'You are a calm, thorough general practitioner.',
    opener: 'Buenos días, ¿qué le trae por aquí?', openerTranslation: 'Good morning, what brings you in?',
    curveball: 'they ask how long you’ve had the symptoms',
    staticHints: ['Describe it: «Tengo tos desde hace tres días.»', 'Say how you feel: «Me siento débil.»', 'Ask: «¿Qué debo hacer?»'],
  },
  {
    id: 'es-bank', title: 'At the Bank', setup: 'You want to open a bank account as a new resident.',
    aiRole: 'You are a helpful bank clerk.',
    opener: '¡Bienvenido! ¿En qué puedo ayudarle?', openerTranslation: 'Welcome! How can I help you?',
    curveball: 'they ask for a document you may not have with you',
    staticHints: ['State your goal: «Quiero abrir una cuenta.»', 'Ask what’s needed: «¿Qué necesito para eso?»', 'Ask about fees: «¿Tiene algún coste?»'],
  },
  {
    id: 'es-apartment', title: 'Viewing a Flat', setup: 'You view a flat you might rent and ask about the details.',
    aiRole: 'You are the landlord showing the flat.',
    opener: '¡Pase! Este es el salón.', openerTranslation: 'Come in! This is the living room.',
    curveball: 'the rent is higher than the advert said',
    staticHints: ['Ask the rent: «¿Cuánto es el alquiler?»', 'Ask what’s included: «¿Están incluidos los gastos?»', 'Ask to move in: «¿Desde cuándo está libre?»'],
  },
  {
    id: 'es-interview', title: 'A Job Interview', setup: 'You interview for a part-time job in a café.',
    aiRole: 'You are the café manager interviewing the candidate.',
    opener: 'Me alegra que haya venido. Cuénteme un poco sobre usted.', openerTranslation: 'Glad you came. Tell me a bit about yourself.',
    curveball: 'they ask whether you can work weekends',
    staticHints: ['Introduce yourself: «Me llamo … y soy estudiante.»', 'Say your experience: «Ya he trabajado en una cafetería.»', 'Show interest: «Aprendo rápido.»'],
  },
  {
    id: 'es-taxi', title: 'Taking a Taxi', setup: 'You take a taxi from the airport to your hotel.',
    aiRole: 'You are a chatty taxi driver.',
    opener: '¡Buenas noches! ¿A dónde le llevo?', openerTranslation: 'Good evening! Where can I take you?',
    curveball: 'there is heavy traffic and a longer route',
    staticHints: ['Give the address: «Al Hotel Estrella, por favor.»', 'Ask the price: «¿Cuánto cuesta más o menos?»', 'Ask the time: «¿Cuánto se tarda?»'],
  },
  {
    id: 'es-lost', title: 'Lost in the City', setup: 'You’re lost and your phone is dead. You ask a local for help.',
    aiRole: 'You are a friendly local who knows the area well.',
    opener: 'Pareces un poco perdido, ¿necesitas ayuda?', openerTranslation: 'You look a bit lost — do you need help?',
    curveball: 'the place you’re looking for has moved',
    staticHints: ['Say you’re lost: «Me he perdido.»', 'Ask the way: «¿Cómo llego al museo?»', 'Ask if it’s far: «¿Está lejos de aquí?»'],
  },
  {
    id: 'es-party', title: 'At a Party', setup: 'A friend brings you to a house party where you know no one.',
    aiRole: 'You are a sociable guest who starts chatting with you.',
    opener: '¡Hola! Creo que no nos conocemos. Soy Marta.', openerTranslation: 'Hi! I don’t think we’ve met. I’m Marta.',
    curveball: 'they invite you to join a game you don’t know',
    staticHints: ['Introduce yourself: «Hola, soy …»', 'Make small talk: «¿De qué conoces al anfitrión?»', 'Keep it going: «¿Y tú a qué te dedicas?»'],
  },
  {
    id: 'es-complaint', title: 'Returning a Product', setup: 'You return a jacket that has a broken zip.',
    aiRole: 'You are a shop assistant at the returns desk.',
    opener: 'Hola, ¿qué puedo hacer por usted?', openerTranslation: 'Hello, what can I do for you?',
    curveball: 'they ask for the receipt, which you may have lost',
    staticHints: ['Explain: «La cremallera está rota.»', 'Say what you want: «Quiero cambiar la chaqueta.»', 'Or: «¿Puedo recuperar mi dinero?»'],
  },
  {
    id: 'es-gym', title: 'Joining a Gym', setup: 'You ask about memberships at a local gym.',
    aiRole: 'You are an upbeat gym receptionist.',
    opener: '¡Hola! ¿Te interesa una membresía?', openerTranslation: 'Hi! Are you interested in a membership?',
    curveball: 'they push a more expensive plan',
    staticHints: ['Ask the price: «¿Cuánto cuesta al mes?»', 'Ask about hours: «¿Qué horario tenéis?»', 'Ask to try: «¿Puedo probarlo primero?»'],
  },
  {
    id: 'es-weekend', title: 'Making Weekend Plans', setup: 'A colleague asks what you’re doing this weekend.',
    aiRole: 'You are a friendly colleague suggesting plans.',
    opener: '¿Tienes planes para el fin de semana?', openerTranslation: 'Do you have plans for the weekend?',
    curveball: 'it’s supposed to rain on the day they suggest',
    staticHints: ['Answer: «Todavía nada fijo.»', 'Suggest: «¿Vamos al cine?»', 'Agree: «¡Suena bien, hagámoslo!»'],
  },
  {
    id: 'es-delivery', title: 'Ordering Delivery', setup: 'You order pizza by phone for delivery to your flat.',
    aiRole: 'You take orders at a busy pizzeria.',
    opener: 'Pizzería Bella, ¿qué va a querer?', openerTranslation: 'Pizzería Bella, what would you like?',
    curveball: 'one topping you want is unavailable',
    staticHints: ['Order: «Una pizza margarita, por favor.»', 'Give your address: «Mi dirección es …»', 'Ask the time: «¿Cuánto tarda el reparto?»'],
  },
];
