// Static content: roleplay scenarios (with 3rd-turn curveballs), daily
// challenge topics, and the filler-word flashcard deck.
// UI-facing fields (title, setup, hint scaffolding) are in English; the
// practice material itself (openers, hints' French phrases, topics,
// examples) stays in French. aiRole/curveball are model-facing prompts.

import { DE_SCENARIOS } from './content/de.js';
import { ES_SCENARIOS } from './content/es.js';
import { contentLang } from './content/active.js';

const FR_SCENARIOS = [
  {
    id: 'bistro',
    title: 'Ordering at the Bistro',
    setup: 'You walk into a busy Parisian bistro at lunchtime and want to order.',
    aiRole: "Serveur/serveuse parisien(ne) sympathique mais pressé(e).",
    opener: "Bonjour ! Bienvenue au Petit Zinc. Vous avez choisi, ou vous avez besoin d'une minute ?",
    openerTranslation: "Hello! Welcome to Le Petit Zinc. Have you decided, or do you need a minute?",
    curveball: "Le plat que le client vient de commander (ou son choix le plus probable) n'est plus disponible — propose une alternative du jour.",
    staticHints: [
      "Vocabulary: «la carte» (the menu), «le plat du jour» (today's special), «saignant / à point» (rare / medium).",
      "Start with: «Je vais prendre…» or «Qu'est-ce que vous me conseillez…»",
      "«Je vais prendre le plat du jour, et une carafe d'eau, s'il vous plaît.» — I'll have today's special and a carafe of water, please.",
    ],
  },
  {
    id: 'poste',
    title: 'At the Post Office',
    setup: 'You need to send an important package abroad and ask about delivery times.',
    aiRole: "Agent(e) de la Poste efficace qui pose beaucoup de questions de procédure.",
    opener: "Bonjour, c'est à vous ! Qu'est-ce que je peux faire pour vous aujourd'hui ?",
    openerTranslation: "Hello, you're next! What can I do for you today?",
    curveball: "Le colis dépasse la limite de poids pour le tarif standard — annonce un supplément et demande au client de choisir.",
    staticHints: [
      "Vocabulary: «un colis» (a package), «les délais» (delivery times), «en recommandé» (registered mail).",
      "Start with: «Je voudrais envoyer…»",
      "«Je voudrais envoyer ce colis au Royaume-Uni, c'est possible en recommandé ?» — I'd like to send this package to the UK, can I do it registered?",
    ],
  },
  {
    id: 'vol',
    title: 'Rebooking a Flight',
    setup: "Tomorrow's flight is cancelled and you're calling the airline to rebook it.",
    aiRole: "Agent(e) du service client d'une compagnie aérienne, poli(e) mais qui suit un script strict.",
    opener: "Air Hexagone, bonjour ! Je suis Camille, comment puis-je vous aider ?",
    openerTranslation: "Air Hexagone, hello! I'm Camille, how can I help you?",
    curveball: "Le seul vol de remplacement disponible part à 6h du matin avec une escale — demande au client s'il accepte.",
    staticHints: [
      "Vocabulary: «annulé» (cancelled), «reporter» (to postpone), «un remboursement» (a refund).",
      "Start with: «Bonjour, je vous appelle parce que…»",
      "«Bonjour, je vous appelle parce que mon vol a été annulé et je voudrais le reporter.» — Hello, I'm calling because my flight was cancelled and I'd like to rebook it.",
    ],
  },
  {
    id: 'marche',
    title: 'At the Market',
    setup: 'You are shopping at the open-air market, chatting with a fruit-and-veg seller.',
    aiRole: "Marchand(e) bavard(e) qui adore donner des conseils de cuisine.",
    opener: "Allez-y, goûtez-moi ces fraises ! Elles sont arrivées ce matin. Qu'est-ce qu'il vous faut ?",
    openerTranslation: "Go on, taste these strawberries! They arrived this morning. What do you need?",
    curveball: "Le marchand n'a plus de monnaie — demande au client s'il peut payer par carte ou en appoint.",
    staticHints: [
      "Vocabulary: «une barquette» (a punnet), «mûr» (ripe), «c'est combien ?» (how much is it?).",
      "Start with: «Je vais vous prendre…»",
      "«Elles ont l'air délicieuses ! Je vais vous prendre deux barquettes, s'il vous plaît.» — They look delicious! I'll take two punnets, please.",
    ],
  },
  {
    id: 'colloc',
    title: 'Flat-share Viewing',
    setup: 'You are viewing a flat-share in Lyon and chatting with one of the current flatmates.',
    aiRole: "Colocataire décontracté(e) qui veut savoir si vous êtes compatible avec l'ambiance de l'appart.",
    opener: "Salut, entre ! Alors, c'est toi qui cherches une chambre ? Tu viens d'où ?",
    openerTranslation: "Hi, come in! So you're the one looking for a room? Where are you from?",
    curveball: "Le colocataire mentionne que le loyer vient d'augmenter de 50 € — observe la réaction du candidat.",
    staticHints: [
      "Vocabulary: «le loyer» (the rent), «les charges» (utilities), «au calme» (quiet).",
      "Start with: «Oui, c'est moi ! Je viens de…»",
      "«Oui c'est moi ! Je viens d'Angleterre et je cherche une chambre pour six mois.» — Yes, that's me! I'm from England and I'm looking for a room for six months.",
    ],
  },
];

// Goal-specific scenarios (business & school learning paths) + free talk.
FR_SCENARIOS.push(
  {
    id: 'libre',
    title: 'Free Talk',
    setup: 'Open-ended conversation — no script, no scenario. Talk about whatever you like; your partner follows your lead.',
    aiRole: "Ami(e) français(e) curieux/curieuse qui suit la conversation où l'apprenant veut l'emmener, pose des questions ouvertes et partage ses propres opinions.",
    opener: "Salut ! Ça me fait plaisir de te voir. Alors, qu'est-ce que tu as envie de raconter aujourd'hui ?",
    openerTranslation: "Hi! Great to see you. So, what do you feel like talking about today?",
    curveball: "Change complètement de sujet avec une question personnelle inattendue mais amicale (par exemple : ton plus grand rêve, un souvenir marquant).",
    staticHints: [
      "Vocabulary: «en ce moment» (at the moment), «d'ailleurs» (by the way), «ça dépend» (it depends).",
      "Start with: «En ce moment, je… » or «J'ai envie de parler de…»",
      "«En ce moment, je pense beaucoup à mes prochaines vacances.» — At the moment I'm thinking a lot about my next holidays.",
    ],
  },
  {
    id: 'entretien',
    title: 'Job Interview',
    setup: 'You are interviewing for a position at a French company. The hiring manager wants to know about you.',
    aiRole: "Responsable RH professionnel(le) mais bienveillant(e) qui mène un entretien d'embauche.",
    opener: "Bonjour, asseyez-vous ! Merci d'être venu(e). Alors, parlez-moi un peu de vous et de votre parcours.",
    openerTranslation: "Hello, have a seat! Thanks for coming. So, tell me a little about yourself and your background.",
    curveball: "Demande au candidat de décrire un échec professionnel et ce qu'il en a appris.",
    staticHints: [
      "Vocabulary: «un poste» (a position), «une expérience» (experience), «un point fort» (a strength).",
      "Start with: «Alors, j'ai travaillé pendant… » or «Je suis quelqu'un de…»",
      "«J'ai trois ans d'expérience dans ce domaine et je cherche un nouveau défi.» — I have three years' experience in this field and I'm looking for a new challenge.",
    ],
  },
  {
    id: 'reunion',
    title: 'Team Meeting',
    setup: 'You are giving a project update in a weekly team meeting at your French office.',
    aiRole: "Chef(fe) de projet qui anime la réunion et pose des questions précises sur l'avancement.",
    opener: "Bon, on va commencer. Où est-ce qu'on en est sur le projet ? Vous pouvez nous faire un point rapide ?",
    openerTranslation: "Right, let's get started. Where are we on the project? Can you give us a quick update?",
    curveball: "Annonce que le client vient d'avancer la date de livraison d'une semaine — demande comment on s'adapte.",
    staticHints: [
      "Vocabulary: «l'avancement» (progress), «un délai» (a deadline), «en retard / dans les temps» (behind / on schedule).",
      "Start with: «Alors, pour le moment, on a terminé…»",
      "«On est dans les temps : la première phase est terminée et on commence les tests cette semaine.» — We're on schedule: phase one is done and we start testing this week.",
    ],
  },
  {
    id: 'cours',
    title: 'Office Hours',
    setup: "You are meeting your French professor during office hours to discuss an assignment you're struggling with.",
    aiRole: "Professeur(e) d'université exigeant(e) mais qui aime aider les étudiants motivés.",
    opener: "Entrez ! Vous vouliez me voir à propos du devoir, c'est ça ? Qu'est-ce qui vous pose problème ?",
    openerTranslation: "Come in! You wanted to see me about the assignment, right? What's giving you trouble?",
    curveball: "Propose à l'étudiant(e) de présenter son travail devant la classe la semaine prochaine — observe sa réaction.",
    staticHints: [
      "Vocabulary: «un devoir» (an assignment), «une consigne» (an instruction), «un délai supplémentaire» (an extension).",
      "Start with: «En fait, je n'ai pas bien compris…»",
      "«En fait, je n'ai pas bien compris la deuxième question — est-ce que vous pourriez me l'expliquer ?» — Actually, I didn't quite understand the second question — could you explain it to me?",
    ],
  },
  {
    id: 'pharmacie',
    title: 'At the Pharmacy',
    setup: "You feel unwell while travelling and go to a pharmacy to describe your symptoms and get advice.",
    aiRole: "Pharmacien(ne) attentif(ve) qui pose des questions sur les symptômes avant de conseiller.",
    opener: "Bonjour, qu'est-ce qui vous amène ? Vous n'avez pas l'air en forme.",
    openerTranslation: "Hello, what brings you in? You don't look well.",
    curveball: "Demande si le client prend déjà d'autres médicaments ou a des allergies avant de recommander quoi que ce soit.",
    staticHints: [
      "Vocabulary: «j'ai mal à la tête / au ventre» (I have a headache / stomachache), «de la fièvre» (a fever), «une ordonnance» (a prescription).",
      "Start with: «Je ne me sens pas très bien, j'ai…»",
      "«Depuis hier, j'ai mal à la gorge et un peu de fièvre. Qu'est-ce que vous me conseillez ?» — Since yesterday I've had a sore throat and a slight fever. What do you recommend?",
    ],
  },
  {
    id: 'banque',
    title: 'At the Bank',
    setup: 'You are opening a bank account as a newcomer in France and have questions about the paperwork.',
    aiRole: "Conseiller(ère) bancaire poli(e) et méthodique qui demande des justificatifs.",
    opener: "Bonjour, bienvenue. Vous souhaitez ouvrir un compte, c'est bien ça ? Vous avez un justificatif de domicile ?",
    openerTranslation: "Hello, welcome. You'd like to open an account, is that right? Do you have proof of address?",
    curveball: "Explique qu'il manque un document (justificatif de domicile récent) et propose une solution.",
    staticHints: [
      "Vocabulary: «un compte» (an account), «une carte bancaire» (a debit card), «un justificatif de domicile» (proof of address), «un RIB» (bank details).",
      "Start with: «Bonjour, je voudrais ouvrir un compte…»",
      "«Je viens d'arriver en France et je voudrais ouvrir un compte courant. Qu'est-ce qu'il vous faut ?» — I've just arrived in France and I'd like to open a current account. What do you need?",
    ],
  },
  {
    id: 'medecin',
    title: "At the Doctor's",
    setup: "You have a persistent symptom and are describing it to a GP during an appointment.",
    aiRole: "Médecin généraliste calme qui pose des questions précises et rassure.",
    opener: "Bonjour, installez-vous. Alors, qu'est-ce qui ne va pas aujourd'hui ?",
    openerTranslation: "Hello, have a seat. So, what's wrong today?",
    curveball: "Demande depuis combien de temps ça dure et si le symptôme empêche de dormir ou de travailler.",
    staticHints: [
      "Vocabulary: «depuis trois jours» (for three days), «ça me lance» (it throbs), «une analyse de sang» (a blood test), «se reposer» (to rest).",
      "Start with: «Docteur, j'ai un problème depuis…»",
      "«Depuis une semaine, j'ai très mal au dos et je dors mal.» — For a week I've had bad back pain and I'm sleeping badly.",
    ],
  },
  {
    id: 'coiffeur',
    title: 'At the Hairdresser',
    setup: 'You want a haircut and need to explain exactly what you would (and would not) like.',
    aiRole: "Coiffeur/coiffeuse bavard(e) et enthousiaste qui propose toujours un peu plus.",
    opener: "Bonjour ! Installez-vous. Alors, on fait quoi de beau aujourd'hui ?",
    openerTranslation: "Hello! Have a seat. So, what are we doing today?",
    curveball: "Propose une coupe plus courte ou une couleur que le client n'a pas demandée — vois comment il réagit.",
    staticHints: [
      "Vocabulary: «une coupe» (a cut), «les pointes» (the ends), «dégradé» (layered/faded), «pas trop court» (not too short).",
      "Start with: «Je voudrais juste rafraîchir la coupe…»",
      "«Juste les pointes, s'il vous plaît, mais gardez la longueur.» — Just the ends, please, but keep the length.",
    ],
  },
  {
    id: 'logement',
    title: 'Renting a Flat',
    setup: "You are viewing a flat to rent and asking the letting agent the questions that matter.",
    aiRole: "Agent(e) immobilier(ère) enthousiaste qui vante le bien mais élude les défauts.",
    opener: "Bonjour ! Alors voilà le salon — lumineux, n'est-ce pas ? Vous cherchez pour quand ?",
    openerTranslation: "Hello! So here's the living room — bright, isn't it? When are you looking to move in?",
    curveball: "Admet à contrecœur un défaut (voisins bruyants, ou charges élevées) quand le client insiste.",
    staticHints: [
      "Vocabulary: «le loyer» (rent), «les charges» (utilities/fees), «meublé» (furnished), «la caution» (deposit), «lumineux» (bright).",
      "Start with: «C'est à combien le loyer, charges comprises ?»",
      "«Le loyer, c'est combien charges comprises, et il y a un dépôt de garantie ?» — How much is the rent including fees, and is there a deposit?",
    ],
  }
);

// Third wave: everyday-life scenarios (hotel to Christmas market).
FR_SCENARIOS.push(
  {
    id: 'hotel',
    title: 'Hotel Check-in',
    setup: "You arrive at a small hotel in Nice after a long journey. There's a problem with your booking.",
    aiRole: "Réceptionniste d'hôtel poli(e) mais débordé(e) qui gère un souci de réservation.",
    opener: "Bonsoir, bienvenue à l'Hôtel des Palmiers ! Vous avez une réservation à quel nom ?",
    openerTranslation: 'Good evening, welcome to the Hôtel des Palmiers! Under what name is your booking?',
    curveball: "Annonce que la chambre réservée n'est pas disponible et propose une alternative moins bien placée.",
    staticHints: [
      "Vocabulary: «une réservation» (a booking), «la clé» (the key), «une chambre avec vue» (a room with a view).",
      "Start with: «Bonsoir, j'ai réservé au nom de…»",
      "«J'ai réservé une chambre double pour deux nuits, voici ma confirmation.» — I booked a double room for two nights, here's my confirmation.",
    ],
  },
  {
    id: 'taxi',
    title: 'Taxi Ride',
    setup: "You hail a taxi at the airport and need to get to your hotel — the driver is chatty and traffic is bad.",
    aiRole: "Chauffeur de taxi bavard qui aime parler de sa ville et commenter la circulation.",
    opener: "Bonjour ! Montez, montez. On va où aujourd'hui ?",
    openerTranslation: "Hello! Hop in. Where are we going today?",
    curveball: "Annonce un gros embouteillage et propose un détour plus long mais plus joli.",
    staticHints: [
      "Vocabulary: «la circulation» (traffic), «un détour» (a detour), «la course» (the fare/ride).",
      "Start with: «Je vais à…, s'il vous plaît.»",
      "«Vous pouvez me déposer devant l'hôtel, à côté de la gare ?» — Can you drop me in front of the hotel, next to the station?",
    ],
  },
  {
    id: 'musee',
    title: 'At the Museum',
    setup: 'You visit a museum and chat with the attendant about tickets, the collection, and what not to miss.',
    aiRole: "Agent d'accueil de musée passionné(e) d'art qui adore conseiller les visiteurs.",
    opener: "Bonjour, bienvenue ! C'est pour une entrée simple, ou vous voulez aussi l'exposition temporaire ?",
    openerTranslation: 'Hello, welcome! Is it a standard ticket, or would you like the temporary exhibition too?',
    curveball: "Signale qu'une salle célèbre est fermée aujourd'hui et propose un autre parcours.",
    staticHints: [
      "Vocabulary: «une œuvre» (a work of art), «un tarif réduit» (a reduced price), «une exposition» (an exhibition).",
      "Start with: «Je voudrais un billet pour…»",
      "«Qu'est-ce qu'il ne faut surtout pas rater dans la collection ?» — What absolutely shouldn't I miss in the collection?",
    ],
  },
  {
    id: 'cinema',
    title: 'At the Cinema',
    setup: "You're buying tickets for a French film. The cashier helps you pick the showing and snacks.",
    aiRole: "Caissier/caissière de cinéma cinéphile qui donne volontiers son avis sur les films.",
    opener: "Bonsoir ! Vous venez voir quel film ce soir ?",
    openerTranslation: 'Good evening! Which film are you here to see tonight?',
    curveball: "Annonce que la séance choisie est complète et propose la version originale sous-titrée plus tard.",
    staticHints: [
      "Vocabulary: «une séance» (a showing), «la version originale» (original version), «une place» (a seat).",
      "Start with: «Deux places pour…, s'il vous plaît.»",
      "«Il reste des places pour la séance de vingt heures ?» — Are there seats left for the 8 p.m. showing?",
    ],
  },
  {
    id: 'supermarche',
    title: 'Supermarket Help',
    setup: "You can't find several items in a big supermarket and ask an employee for help.",
    aiRole: "Employé(e) de supermarché serviable qui connaît le magasin par cœur.",
    opener: "Bonjour ! Je peux vous aider ? Vous cherchez quelque chose ?",
    openerTranslation: 'Hello! Can I help you? Are you looking for something?',
    curveball: "Explique que le produit demandé est en rupture de stock et propose un équivalent.",
    staticHints: [
      "Vocabulary: «un rayon» (an aisle/section), «en rupture de stock» (out of stock), «une promotion» (a special offer).",
      "Start with: «Excusez-moi, où est-ce que je peux trouver…»",
      "«Je cherche la farine — c'est dans quel rayon ?» — I'm looking for flour — which aisle is it in?",
    ],
  },
  {
    id: 'boulangerie2',
    title: 'Morning Bakery',
    setup: "Seven a.m. at the neighbourhood bakery: order your bread and pastries, chat about the day.",
    aiRole: "Boulanger/boulangère du quartier chaleureux/chaleureuse qui connaît tous ses clients.",
    opener: "Bonjour ! Qu'est-ce que je vous sers ce matin ? La baguette tradition sort du four.",
    openerTranslation: "Morning! What can I get you today? The tradition baguette is fresh out of the oven.",
    curveball: "Annonce qu'il ne reste plus de croissants et propose des pains au chocolat tout chauds.",
    staticHints: [
      "Vocabulary: «bien cuite» (well baked), «une viennoiserie» (a pastry), «il ne reste plus de…» (there's no … left).",
      "Start with: «Bonjour, je vais prendre…»",
      "«Une baguette pas trop cuite et deux croissants, s'il vous plaît.» — A not-too-dark baguette and two croissants, please.",
    ],
  },
  {
    id: 'dentiste',
    title: 'At the Dentist',
    setup: "You have a toothache and managed to get an emergency dentist appointment.",
    aiRole: "Dentiste calme et rassurant(e) qui examine une rage de dents.",
    opener: "Bonjour, installez-vous. Alors, dites-moi ce qui vous amène.",
    openerTranslation: "Hello, have a seat. So, tell me what brings you in.",
    curveball: "Annonce qu'il faut faire un petit soin tout de suite et demande si l'apprenant est d'accord.",
    staticHints: [
      "Vocabulary: «une rage de dents» (a bad toothache), «une carie» (a cavity), «ça fait mal» (it hurts).",
      "Start with: «J'ai mal à une dent depuis…»",
      "«J'ai très mal en bas à droite, surtout quand je bois froid.» — It really hurts at the bottom right, especially when I drink something cold.",
    ],
  },
  {
    id: 'veterinaire',
    title: 'At the Vet',
    setup: "Your cat hasn't been eating for two days. You take it to the vet, worried.",
    aiRole: "Vétérinaire doux/douce et pédagogue qui examine un chat et rassure son maître.",
    opener: "Bonjour ! Et voilà notre patient… Alors, qu'est-ce qui ne va pas avec ce petit chat ?",
    openerTranslation: "Hello! And here's our patient… So, what's wrong with this little cat?",
    curveball: "Demande des détails précis sur l'alimentation et le comportement du chat cette semaine.",
    staticHints: [
      "Vocabulary: «il ne mange plus» (he's stopped eating), «une piqûre» (an injection), «inquiet/inquiète» (worried).",
      "Start with: «Mon chat ne mange plus depuis…»",
      "«Il dort beaucoup plus que d'habitude et il ne joue plus.» — He sleeps far more than usual and doesn't play any more.",
    ],
  },
  {
    id: 'garagiste',
    title: 'Car Trouble',
    setup: "Your car is making a strange noise. You describe the problem to a mechanic.",
    aiRole: "Garagiste franc/franche et sympathique qui pose des questions techniques simples.",
    opener: "Bonjour ! Alors, c'est quoi le souci avec la voiture ?",
    openerTranslation: "Hello! So, what's the trouble with the car?",
    curveball: "Annonce que la réparation coûtera plus cher que prévu et explique pourquoi.",
    staticHints: [
      "Vocabulary: «un bruit bizarre» (a strange noise), «freiner» (to brake), «un devis» (a quote/estimate).",
      "Start with: «Ma voiture fait un bruit quand…»",
      "«Ça fait un bruit métallique quand je freine, surtout à froid.» — It makes a metallic noise when I brake, especially when cold.",
    ],
  },
  {
    id: 'plombier',
    title: 'The Plumber Visit',
    setup: "A leak under your kitchen sink — the plumber arrives and you explain what happened.",
    aiRole: "Plombier/plombière pragmatique qui diagnostique une fuite et explique la réparation.",
    opener: "Bonjour ! C'est vous qui avez appelé pour la fuite ? Montrez-moi ça.",
    openerTranslation: "Hello! You're the one who called about the leak? Show me.",
    curveball: "Découvre un deuxième problème (un joint usé) et demande s'il faut le réparer aussi.",
    staticHints: [
      "Vocabulary: «une fuite» (a leak), «couper l'eau» (to turn off the water), «sous l'évier» (under the sink).",
      "Start with: «Il y a une fuite sous…»",
      "«Ça goutte depuis hier soir, j'ai mis une bassine en attendant.» — It's been dripping since last night, I put a bowl under it in the meantime.",
    ],
  },
  {
    id: 'commissariat',
    title: 'Lost Wallet',
    setup: "Your wallet was stolen in the metro. You report it at the police station.",
    aiRole: "Policier/policière méthodique qui enregistre une déclaration de vol avec patience.",
    opener: "Bonjour. Asseyez-vous. Alors, vous venez déclarer un vol, c'est bien ça ?",
    openerTranslation: "Hello. Have a seat. So, you're here to report a theft, is that right?",
    curveball: "Demande une description précise du moment du vol : où, quand, comment, qui était autour.",
    staticHints: [
      "Vocabulary: «un vol» (a theft), «un portefeuille» (a wallet), «faire opposition» (to cancel/block a card).",
      "Start with: «On m'a volé mon portefeuille dans…»",
      "«C'était dans la ligne 4, vers dix-huit heures, il y avait beaucoup de monde.» — It was on line 4, around 6 p.m., it was very crowded.",
    ],
  },
  {
    id: 'mairie',
    title: 'Town Hall Paperwork',
    setup: "You need a certificate from the town hall and discover French bureaucracy first-hand.",
    aiRole: "Agent administratif précis(e) qui applique les règles mais aide volontiers.",
    opener: "Bonjour, c'est pour quelle démarche ?",
    openerTranslation: "Hello, what procedure are you here for?",
    curveball: "Annonce qu'il manque un justificatif de domicile et explique comment l'obtenir.",
    staticHints: [
      "Vocabulary: «une démarche» (an administrative procedure), «un justificatif» (a supporting document), «un formulaire» (a form).",
      "Start with: «Bonjour, j'aurais besoin de…»",
      "«Quels documents est-ce que je dois fournir pour ce dossier ?» — Which documents do I need to provide for this file?",
    ],
  },
  {
    id: 'bibliotheque',
    title: 'Library Card',
    setup: "You sign up at the local library and ask what you can borrow.",
    aiRole: "Bibliothécaire passionné(e) qui adore recommander des lectures.",
    opener: "Bonjour ! Vous voulez vous inscrire ? C'est gratuit pour les habitants de la commune.",
    openerTranslation: "Hello! Would you like to sign up? It's free for local residents.",
    curveball: "Demande quel genre de livres l'apprenant aime et propose trois recommandations.",
    staticHints: [
      "Vocabulary: «emprunter» (to borrow), «rendre» (to return), «un abonnement» (a membership).",
      "Start with: «Je voudrais m'inscrire à la bibliothèque.»",
      "«Combien de livres est-ce qu'on peut emprunter à la fois ?» — How many books can you borrow at a time?",
    ],
  },
  {
    id: 'librairie',
    title: 'Bookshop Advice',
    setup: "You want a French novel that's not too hard. The bookseller quizzes you on your tastes.",
    aiRole: "Libraire érudit(e) et enthousiaste qui pose des questions pour trouver le livre parfait.",
    opener: "Bonjour ! Je peux vous conseiller ? Vous cherchez quelque chose de particulier ?",
    openerTranslation: "Hello! Can I help you choose? Are you looking for something in particular?",
    curveball: "Propose deux livres opposés (un classique, un roman contemporain) et demande de choisir en justifiant.",
    staticHints: [
      "Vocabulary: «un roman» (a novel), «facile à lire» (easy to read), «une histoire» (a story).",
      "Start with: «Je cherche un livre en français pas trop difficile…»",
      "«J'aime les histoires vraies et les romans courts — vous me conseillez quoi ?» — I like true stories and short novels — what do you recommend?",
    ],
  },
  {
    id: 'pressing',
    title: 'Dry Cleaner Mix-up',
    setup: "You collect a jacket from the dry cleaner — but they hand you the wrong one.",
    aiRole: "Employé(e) de pressing confus(e) mais de bonne volonté qui cherche à résoudre une erreur d'étiquette.",
    opener: "Bonjour ! Vous venez récupérer un vêtement ? Vous avez le ticket ?",
    openerTranslation: "Hello! Here to pick up an item? Do you have the ticket?",
    curveball: "Tend le mauvais vêtement et met un moment à admettre l'erreur.",
    staticHints: [
      "Vocabulary: «un ticket» (a ticket/receipt), «une veste» (a jacket), «ce n'est pas la mienne» (it's not mine).",
      "Start with: «Je viens récupérer…, voici mon ticket.»",
      "«Ce n'est pas ma veste — la mienne est bleu marine, avec des boutons dorés.» — That's not my jacket — mine is navy blue with gold buttons.",
    ],
  },
  {
    id: 'opticien',
    title: 'New Glasses',
    setup: "Your glasses broke. At the optician you choose new frames and discuss lenses.",
    aiRole: "Opticien(ne) stylé(e) et de bon conseil qui aide à choisir des montures.",
    opener: "Bonjour ! Oh là, elles ont souffert, ces lunettes… On regarde ce qu'on peut faire ?",
    openerTranslation: "Hello! Oh dear, these glasses have been through a lot… Shall we see what we can do?",
    curveball: "Demande si l'apprenant préfère payer plus pour des verres amincis et traite anti-reflets.",
    staticHints: [
      "Vocabulary: «une monture» (a frame), «des verres» (lenses), «une ordonnance» (a prescription).",
      "Start with: «Mes lunettes sont cassées, il me faut…»",
      "«Je cherche une monture légère, plutôt ronde, dans un budget raisonnable.» — I'm looking for a light frame, roundish, at a reasonable price.",
    ],
  },
  {
    id: 'camping',
    title: 'At the Campsite',
    setup: "You arrive at a campsite in the Ardèche and sort out your pitch with the manager.",
    aiRole: "Gérant(e) de camping détendu(e) qui explique les règles et la vie du camping.",
    opener: "Bienvenue au Camping des Cigales ! Vous avez réservé un emplacement ?",
    openerTranslation: "Welcome to the Camping des Cigales! Did you book a pitch?",
    curveball: "Prévient qu'un orage est annoncé cette nuit et conseille de bien fixer la tente.",
    staticHints: [
      "Vocabulary: «un emplacement» (a pitch), «une tente» (a tent), «les sanitaires» (the washrooms).",
      "Start with: «Bonjour, on a réservé un emplacement pour…»",
      "«L'emplacement est à l'ombre ? Et la piscine est ouverte jusqu'à quelle heure ?» — Is the pitch shaded? And how late is the pool open?",
    ],
  },
  {
    id: 'ski',
    title: 'Ski Rental',
    setup: "First day in the Alps: you rent skis, boots and a helmet, and ask about the slopes.",
    aiRole: "Loueur/loueuse de skis montagnard(e) qui ajuste le matériel et donne des conseils pistes.",
    opener: "Salut ! Alors, on s'équipe pour la semaine ? Tu skies depuis longtemps ?",
    openerTranslation: "Hi! So, kitting you out for the week? Have you been skiing long?",
    curveball: "Déconseille une piste noire verglacée et suggère un itinéraire adapté au niveau.",
    staticHints: [
      "Vocabulary: «louer» (to rent), «des chaussures de ski» (ski boots), «une piste» (a slope/run).",
      "Start with: «Je voudrais louer des skis pour…»",
      "«Je suis débutant — il me faut des skis faciles et un casque.» — I'm a beginner — I need easy skis and a helmet.",
    ],
  },
  {
    id: 'plage',
    title: 'Beach Kiosk',
    setup: "A hot afternoon on the beach: you rent a parasol and order cold drinks at the kiosk.",
    aiRole: "Vendeur/vendeuse de plage décontracté(e) qui gère parasols, glaces et boissons.",
    opener: "Salut ! Il fait chaud, hein ? Qu'est-ce que je vous sers ?",
    openerTranslation: "Hi! Hot today, isn't it? What can I get you?",
    curveball: "Annonce qu'il n'y a plus de parasols et propose une solution créative.",
    staticHints: [
      "Vocabulary: «un parasol» (a parasol), «une glace» (an ice cream), «à l'ombre» (in the shade).",
      "Start with: «On peut louer un parasol pour l'après-midi ?»",
      "«Deux eaux bien fraîches et une glace à la vanille, s'il vous plaît.» — Two very cold waters and a vanilla ice cream, please.",
    ],
  },
  {
    id: 'diner',
    title: 'Dinner Party Guest',
    setup: "You're invited to dinner at a French friend's home — compliments, seconds, and conversation.",
    aiRole: "Hôte/hôtesse généreux/généreuse qui ressert tout le monde et anime la conversation.",
    opener: "Entre, entre ! Ça me fait tellement plaisir ! Installe-toi, l'apéro est prêt.",
    openerTranslation: "Come in, come in! I'm so glad you're here! Sit down, the apéritif is ready.",
    curveball: "Insiste chaleureusement pour resservir l'apprenant qui doit refuser poliment (ou accepter).",
    staticHints: [
      "Vocabulary: «c'est délicieux» (it's delicious), «je n'en peux plus» (I'm stuffed), «la recette» (the recipe).",
      "Start with: «Merci pour l'invitation, ça sent très bon !»",
      "«C'était délicieux, mais je ne peux vraiment plus rien avaler !» — It was delicious, but I honestly can't eat another thing!",
    ],
  },
  {
    id: 'voisin',
    title: 'New Neighbour',
    setup: "You just moved in. A curious neighbour knocks to welcome you to the building.",
    aiRole: "Voisin(e) accueillant(e) et un peu curieux/curieuse qui veut tout savoir du nouveau venu.",
    opener: "Bonjour ! Je suis du troisième. Je voulais vous souhaiter la bienvenue dans l'immeuble !",
    openerTranslation: "Hello! I'm from the third floor. I wanted to welcome you to the building!",
    curveball: "Mentionne les petites règles non écrites de l'immeuble (poubelles, bruit) avec tact.",
    staticHints: [
      "Vocabulary: «emménager» (to move in), «l'immeuble» (the building), «enchanté(e)» (nice to meet you).",
      "Start with: «Enchanté(e) ! Je viens d'emménager…»",
      "«Merci beaucoup ! N'hésitez pas à frapper si le déménagement fait trop de bruit.» — Thank you! Don't hesitate to knock if the move gets too noisy.",
    ],
  },
  {
    id: 'covoiturage',
    title: 'Carpool Trip',
    setup: "Three hours of carpooling from Paris to Rennes with a talkative driver.",
    aiRole: "Conducteur/conductrice de covoiturage sociable qui aime discuter pour faire passer la route.",
    opener: "Salut ! C'est toi mon covoitureur ? Mets ton sac dans le coffre, on y va !",
    openerTranslation: "Hi! You're my carpooler? Put your bag in the boot, off we go!",
    curveball: "Propose un jeu de conversation : chacun raconte son pire souvenir de voyage.",
    staticHints: [
      "Vocabulary: «le coffre» (the boot/trunk), «une pause» (a break), «la route» (the road/journey).",
      "Start with: «Salut ! Oui, c'est moi. Merci pour le covoiturage !»",
      "«Tu fais ce trajet souvent ? Moi, c'est la première fois que je vais à Rennes.» — Do you do this trip often? It's my first time going to Rennes.",
    ],
  },
  {
    id: 'sav',
    title: 'Customer Service Call',
    setup: "Your internet has been down for three days. You call customer service — stay polite, stay firm.",
    aiRole: "Téléconseiller/téléconseillère au script rigide qui suit une procédure avant de vraiment aider.",
    opener: "Service client, bonjour ! Je vous écoute, comment puis-je vous aider ?",
    openerTranslation: "Customer service, hello! I'm listening, how can I help you?",
    curveball: "Fait suivre une procédure inutile (redémarrer la box) avant d'admettre une panne générale.",
    staticHints: [
      "Vocabulary: «une panne» (an outage/failure), «la box» (the router), «un remboursement» (a refund).",
      "Start with: «Bonjour, je vous appelle parce que…»",
      "«J'ai déjà redémarré la box trois fois — je voudrais un vrai diagnostic.» — I've already restarted the router three times — I'd like a real diagnosis.",
    ],
  },
  {
    id: 'gym',
    title: 'Joining the Gym',
    setup: "You visit a gym to compare memberships — the coach gives you the full sales tour.",
    aiRole: "Coach sportif/sportive motivé(e) qui fait visiter la salle et vante les abonnements.",
    opener: "Salut ! Bienvenue ! Alors, tu cherches à te remettre au sport ? Je te fais visiter ?",
    openerTranslation: "Hi! Welcome! So, looking to get back into sport? Shall I show you around?",
    curveball: "Pousse l'abonnement premium à l'année ; l'apprenant doit négocier ou refuser poliment.",
    staticHints: [
      "Vocabulary: «un abonnement» (a membership), «une séance d'essai» (a trial session), «s'entraîner» (to train).",
      "Start with: «Je voudrais des infos sur vos abonnements.»",
      "«Est-ce qu'il y a un abonnement sans engagement, juste pour trois mois ?» — Is there a no-commitment membership, just for three months?",
    ],
  },
  {
    id: 'fleuriste',
    title: 'At the Florist',
    setup: "You need a bouquet for a friend's birthday — the florist helps you compose it.",
    aiRole: "Fleuriste artiste et de bon conseil qui compose des bouquets sur mesure.",
    opener: "Bonjour ! Qu'est-ce qui vous ferait plaisir aujourd'hui ? C'est pour offrir ?",
    openerTranslation: "Hello! What would you like today? Is it a gift?",
    curveball: "Demande le budget et la personnalité de la personne pour personnaliser le bouquet.",
    staticHints: [
      "Vocabulary: «un bouquet» (a bouquet), «offrir» (to give as a gift), «des roses» (roses).",
      "Start with: «Je cherche un bouquet pour…»",
      "«C'est pour un anniversaire — quelque chose de coloré, autour de trente euros.» — It's for a birthday — something colourful, around thirty euros.",
    ],
  },
  {
    id: 'noel',
    title: 'Christmas Market',
    setup: "Mulled wine, crafts and crowds at the Strasbourg Christmas market — chat with a stallholder.",
    aiRole: "Artisan(e) d'un chalet de marché de Noël chaleureux/chaleureuse et fier/fière de ses produits.",
    opener: "Bonsoir ! Approchez, approchez ! Un petit vin chaud pour vous réchauffer ?",
    openerTranslation: "Good evening! Come closer! A little mulled wine to warm you up?",
    curveball: "Raconte l'histoire d'un objet artisanal et propose de le personnaliser (gravure).",
    staticHints: [
      "Vocabulary: «le vin chaud» (mulled wine), «un chalet» (a market stall/hut), «fait main» (handmade).",
      "Start with: «Bonsoir ! Qu'est-ce que vous vendez de fait main ?»",
      "«C'est vous qui fabriquez tout ça ? J'aimerais un cadeau original pour ma sœur.» — Do you make all this yourself? I'd like an original gift for my sister.",
    ],
  }
);

export const DAILY_TOPICS = [
  { fr: "Décrivez votre petit-déjeuner idéal.", en: 'Describe your ideal breakfast.' },
  { fr: "Racontez la dernière fois que vous avez été en retard.", en: 'Tell the story of the last time you were late.' },
  { fr: "Quel est le meilleur conseil qu'on vous ait donné ?", en: "What's the best advice you've ever been given?" },
  { fr: "Décrivez votre ville à quelqu'un qui ne la connaît pas.", en: "Describe your town to someone who doesn't know it." },
  { fr: "Qu'est-ce que vous feriez avec un million d'euros ?", en: 'What would you do with a million euros?' },
  { fr: "Racontez un souvenir d'enfance.", en: 'Tell a childhood memory.' },
  { fr: "Pour ou contre les réseaux sociaux ?", en: 'For or against social media?' },
  { fr: "Décrivez votre film ou série préféré(e) sans dire le titre.", en: 'Describe your favourite film or series without saying the title.' },
  { fr: "Qu'est-ce qui vous rend heureux/heureuse un dimanche ?", en: 'What makes you happy on a Sunday?' },
  { fr: "Si vous pouviez dîner avec une personne célèbre, qui et pourquoi ?", en: 'If you could have dinner with someone famous, who and why?' },
  { fr: "Décrivez le pire repas de votre vie.", en: 'Describe the worst meal of your life.' },
  { fr: "Quelle habitude aimeriez-vous changer ?", en: 'Which habit would you like to change?' },
];

// Scenarios for the active target language. Functions (not consts) so the
// Arena, Home and search re-read them after the learner switches language.
const SCENARIOS_BY_LANG = { fr: FR_SCENARIOS, de: DE_SCENARIOS, es: ES_SCENARIOS };
export const getScenarios = () => SCENARIOS_BY_LANG[contentLang()] || FR_SCENARIOS;
export const getScenario = (id) => getScenarios().find((s) => s.id === id) || getScenarios()[0];

export const FLASHCARDS = [
  { id: 'du-coup', front: 'du coup', meaning: 'so / as a result', example: "Il pleuvait, du coup on est restés à la maison.", exampleTranslation: 'It was raining, so we stayed home.', register: 'Very common, informal' },
  { id: 'en-fait', front: 'en fait', meaning: 'actually / in fact', example: "En fait, je ne suis jamais allé à Paris.", exampleTranslation: "Actually, I've never been to Paris.", register: 'Universal, all registers' },
  { id: 'bref', front: 'bref', meaning: 'anyway / long story short', example: "Bref, on a raté le train.", exampleTranslation: 'Long story short, we missed the train.', register: 'Informal, wraps up a story' },
  { id: 'quand-meme', front: 'quand même', meaning: 'still / all the same', example: "C'est cher, mais c'est quand même très bon.", exampleTranslation: "It's expensive, but it's still really good.", register: 'Universal' },
  { id: 'genre', front: 'genre', meaning: 'like / kind of', example: "Il est arrivé genre deux heures en retard.", exampleTranslation: 'He arrived like two hours late.', register: 'Very informal, younger speakers' },
  { id: 'enfin', front: 'enfin', meaning: 'well / I mean', example: "Enfin, tu vois ce que je veux dire.", exampleTranslation: 'Well, you see what I mean.', register: 'Universal filler' },
  { id: 'franchement', front: 'franchement', meaning: 'honestly / frankly', example: "Franchement, c'était le meilleur concert de ma vie.", exampleTranslation: 'Honestly, it was the best concert of my life.', register: 'Informal emphasis' },
  { id: 'bah', front: 'bah', meaning: 'well / duh', example: "Bah oui, évidemment !", exampleTranslation: 'Well yes, obviously!', register: 'Very informal, spoken only' },
  { id: 'tu-vois', front: 'tu vois', meaning: 'you know / you see', example: "C'est compliqué, tu vois, il y a beaucoup d'étapes.", exampleTranslation: "It's complicated, you know, there are lots of steps.", register: 'Informal, conversational glue' },
  { id: 'carrement', front: 'carrément', meaning: 'totally / absolutely', example: "Ce resto est carrément incroyable.", exampleTranslation: 'This restaurant is totally amazing.', register: 'Informal, enthusiastic' },
];

export const randomTopic = () =>
  DAILY_TOPICS[Math.floor(Math.random() * DAILY_TOPICS.length)];
