// Real-world practice: a survival phrasebook grouped by situation, plus a
// timed mock exam. Situations that map to an Arena roleplay expose a
// `scenarioId` so the learner can jump from reading phrases to using them
// live. All content is authored and self-contained (no backend).

// situation: { id, title, emoji, blurb, scenarioId?, level?, phrases: [{fr, en}] }
export const SITUATIONS = [
  {
    id: 'travel',
    title: 'Travel & directions',
    emoji: '🧳',
    blurb: 'Stations, maps and getting unstuck',
    level: 'A1–A2',
    phrases: [
      { fr: "Excusez-moi, où se trouve la gare ?", en: 'Excuse me, where is the station?' },
      { fr: "Un aller-retour pour Lyon, s'il vous plaît.", en: 'A return ticket to Lyon, please.' },
      { fr: "À quelle heure part le prochain train ?", en: 'What time does the next train leave?' },
      { fr: "Je crois que je me suis perdu(e).", en: 'I think I’m lost.' },
      { fr: "Pouvez-vous me montrer sur la carte ?", en: 'Can you show me on the map?' },
      { fr: "C'est loin d'ici à pied ?", en: 'Is it far from here on foot?' },
      { fr: "Il y a un arrêt de bus près d'ici ?", en: 'Is there a bus stop near here?' },
      { fr: "Je descend à la prochaine station.", en: 'I’m getting off at the next stop.' },
      { fr: "Le quai numéro trois, c'est par où ?", en: 'Which way is platform three?' },
      { fr: "Est-ce que ce train s'arrête à Dijon ?", en: 'Does this train stop at Dijon?' },
    ],
  },
  {
    id: 'restaurant',
    title: 'Restaurant',
    emoji: '🍽️',
    blurb: 'Ordering, dietary needs, the bill',
    scenarioId: 'bistro',
    level: 'A1–A2',
    phrases: [
      { fr: "Une table pour deux, s'il vous plaît.", en: 'A table for two, please.' },
      { fr: "Qu'est-ce que vous me conseillez ?", en: 'What do you recommend?' },
      { fr: "Je suis végétarien(ne).", en: 'I’m vegetarian.' },
      { fr: "Je suis allergique aux fruits de mer.", en: 'I’m allergic to seafood.' },
      { fr: "L'addition, s'il vous plaît.", en: 'The bill, please.' },
      { fr: "C'était délicieux, merci !", en: 'That was delicious, thank you!' },
      { fr: "On peut avoir la carte des vins ?", en: 'Could we have the wine list?' },
      { fr: "Est-ce que c'est compris ?", en: 'Is service included?' },
      { fr: "Je prendrai la même chose.", en: 'I’ll have the same.' },
      { fr: "On est un peu pressés.", en: 'We’re in a bit of a hurry.' },
    ],
  },
  {
    id: 'airport',
    title: 'Airport',
    emoji: '✈️',
    blurb: 'Check-in, security, delays',
    scenarioId: 'vol',
    level: 'A2',
    phrases: [
      { fr: "Où est l'enregistrement pour ce vol ?", en: 'Where is check-in for this flight?' },
      { fr: "Je n'ai qu'un bagage à main.", en: 'I only have hand luggage.' },
      { fr: "Mon vol est en retard.", en: 'My flight is delayed.' },
      { fr: "J'ai raté ma correspondance.", en: 'I missed my connection.' },
      { fr: "Où puis-je récupérer mes bagages ?", en: 'Where can I collect my luggage?' },
      { fr: "Ma valise n'est pas arrivée.", en: 'My suitcase hasn’t arrived.' },
      { fr: "Puis-je avoir un siège côté hublot ?", en: 'May I have a window seat?' },
      { fr: "Où est le contrôle de sécurité ?", en: 'Where is security screening?' },
      { fr: "Mon vol a été annulé.", en: 'My flight has been cancelled.' },
      { fr: "Y a-t-il une indemnisation ?", en: 'Is there compensation?' },
    ],
  },
  {
    id: 'shopping',
    title: 'Shopping',
    emoji: '🛍️',
    blurb: 'Sizes, prices, paying',
    scenarioId: 'marche',
    level: 'A1–A2',
    phrases: [
      { fr: "Est-ce que vous avez ça dans une autre taille ?", en: 'Do you have this in another size?' },
      { fr: "Je peux l'essayer ?", en: 'Can I try it on?' },
      { fr: "Ça coûte combien ?", en: 'How much does it cost?' },
      { fr: "C'est un peu trop cher pour moi.", en: 'It’s a bit too expensive for me.' },
      { fr: "Je vais juste regarder, merci.", en: 'I’m just looking, thanks.' },
      { fr: "Est-ce que je peux payer par carte ?", en: 'Can I pay by card?' },
      { fr: "Vous faites des échanges ?", en: 'Do you do exchanges?' },
      { fr: "C'est en solde ?", en: 'Is it on sale?' },
      { fr: "Je le prends.", en: 'I’ll take it.' },
      { fr: "Avez-vous un sac, s'il vous plaît ?", en: 'Do you have a bag, please?' },
    ],
  },
  {
    id: 'medical',
    title: 'Medical emergencies',
    emoji: '🚑',
    blurb: 'Symptoms, the pharmacy, urgent help',
    scenarioId: 'pharmacie',
    level: 'A2–B1',
    phrases: [
      { fr: "J'ai besoin d'un médecin.", en: 'I need a doctor.' },
      { fr: "Appelez une ambulance, s'il vous plaît !", en: 'Call an ambulance, please!' },
      { fr: "J'ai mal ici.", en: 'It hurts here.' },
      { fr: "Je suis diabétique.", en: 'I’m diabetic.' },
      { fr: "Avez-vous quelque chose contre le mal de tête ?", en: 'Do you have something for a headache?' },
      { fr: "Où est la pharmacie la plus proche ?", en: 'Where is the nearest pharmacy?' },
      { fr: "J'ai de la fièvre depuis hier.", en: 'I’ve had a fever since yesterday.' },
      { fr: "Je prends déjà des médicaments.", en: 'I’m already on medication.' },
      { fr: "C'est urgent.", en: 'It’s urgent.' },
      { fr: "Avez-vous besoin d'une ordonnance ?", en: 'Do you need a prescription?' },
    ],
  },
  {
    id: 'doctor',
    title: "At the doctor's",
    emoji: '🩺',
    blurb: 'Appointments, symptoms, follow-up',
    scenarioId: 'medecin',
    level: 'A2–B1',
    phrases: [
      { fr: "J'ai pris rendez-vous pour 10 heures.", en: 'I booked an appointment for 10 o’clock.' },
      { fr: "Ça me fait mal quand j'avale.", en: 'It hurts when I swallow.' },
      { fr: "Les symptômes ont commencé il y a trois jours.", en: 'The symptoms started three days ago.' },
      { fr: "Est-ce que c'est contagieux ?", en: 'Is it contagious?' },
      { fr: "Dois-je revenir vous voir ?", en: 'Should I come back to see you?' },
      { fr: "Je suis enceinte.", en: 'I’m pregnant.' },
      { fr: "Je suis allergique à la pénicilline.", en: 'I’m allergic to penicillin.' },
      { fr: "Pouvez-vous me faire une ordonnance ?", en: 'Can you write me a prescription?' },
    ],
  },
  {
    id: 'business',
    title: 'Business communication',
    emoji: '💼',
    blurb: 'Meetings, email, introductions',
    scenarioId: 'reunion',
    level: 'B1–B2',
    phrases: [
      { fr: "Enchanté(e), je travaille dans le marketing.", en: 'Pleased to meet you, I work in marketing.' },
      { fr: "Je vous envoie un mail pour confirmer.", en: 'I’ll send you an email to confirm.' },
      { fr: "On peut fixer une réunion la semaine prochaine ?", en: 'Can we set up a meeting next week?' },
      { fr: "Je reviens vers vous dès que possible.", en: 'I’ll get back to you as soon as possible.' },
      { fr: "Pouvez-vous préciser votre demande ?", en: 'Could you clarify your request?' },
      { fr: "Merci pour votre temps.", en: 'Thank you for your time.' },
      { fr: "Je partage mon écran.", en: 'I’m sharing my screen.' },
      { fr: "On est d'accord sur les prochaines étapes ?", en: 'Are we agreed on the next steps?' },
      { fr: "Je vais préparer un compte rendu.", en: 'I’ll prepare the minutes / a write-up.' },
      { fr: "Désolé(e) du retard, j'étais en appel.", en: 'Sorry I’m late — I was on a call.' },
    ],
  },
  {
    id: 'interview',
    title: 'Job interviews',
    emoji: '🎯',
    blurb: 'Strengths, experience, questions',
    scenarioId: 'entretien',
    level: 'B1–B2',
    phrases: [
      { fr: "J'ai cinq ans d'expérience dans ce domaine.", en: 'I have five years’ experience in this field.' },
      { fr: "Je suis quelqu'un de rigoureux et curieux.", en: 'I’m a rigorous and curious person.' },
      { fr: "Je cherche un nouveau défi.", en: 'I’m looking for a new challenge.' },
      { fr: "Mon plus grand point fort, c'est l'organisation.", en: 'My greatest strength is organisation.' },
      { fr: "Est-ce que le poste est en télétravail ?", en: 'Is the position remote?' },
      { fr: "Quand puis-je espérer une réponse ?", en: 'When can I expect an answer?' },
      { fr: "Quelles sont les perspectives d'évolution ?", en: 'What are the career prospects?' },
      { fr: "J'ai une question sur l'équipe.", en: 'I have a question about the team.' },
      { fr: "Je suis disponible dès le mois prochain.", en: 'I’m available from next month.' },
      { fr: "Merci pour cet entretien.", en: 'Thank you for this interview.' },
    ],
  },
  {
    id: 'hotel',
    title: 'Hotel check-in',
    emoji: '🏨',
    blurb: 'Booking, keys, problems at reception',
    scenarioId: 'hotel',
    level: 'A2',
    phrases: [
      { fr: "J'ai une réservation au nom de Martin.", en: 'I have a reservation under the name Martin.' },
      { fr: "À quelle heure est le check-out ?", en: 'What time is check-out?' },
      { fr: "Est-ce que le petit-déjeuner est inclus ?", en: 'Is breakfast included?' },
      { fr: "Il y a un problème avec la chambre.", en: 'There’s a problem with the room.' },
      { fr: "Le Wi-Fi ne fonctionne pas.", en: 'The Wi-Fi isn’t working.' },
      { fr: "Pouvez-vous me donner un réveil ?", en: 'Can you give me a wake-up call?' },
      { fr: "Y a-t-il un ascenseur ?", en: 'Is there a lift?' },
      { fr: "Je voudrais prolonger mon séjour d'une nuit.", en: 'I’d like to stay one more night.' },
    ],
  },
  {
    id: 'taxi',
    title: 'Taxi & rides',
    emoji: '🚕',
    blurb: 'Destinations, fares, traffic chat',
    scenarioId: 'taxi',
    level: 'A1–A2',
    phrases: [
      { fr: "À l'hôtel du Parc, s'il vous plaît.", en: 'To Hôtel du Parc, please.' },
      { fr: "Combien ça va coûter environ ?", en: 'Roughly how much will it cost?' },
      { fr: "Vous prenez les cartes ?", en: 'Do you take cards?' },
      { fr: "Vous pouvez arrêter ici, s'il vous plaît.", en: 'You can stop here, please.' },
      { fr: "Il y a beaucoup de circulation.", en: 'There’s a lot of traffic.' },
      { fr: "Vous connaissez un bon raccourci ?", en: 'Do you know a good shortcut?' },
      { fr: "Gardez la monnaie.", en: 'Keep the change.' },
      { fr: "C'est pour la gare TGV ?", en: 'Is this for the TGV station?' },
    ],
  },
  {
    id: 'bank',
    title: 'At the bank',
    emoji: '🏦',
    blurb: 'Accounts, cards, paperwork',
    scenarioId: 'banque',
    level: 'A2–B1',
    phrases: [
      { fr: "Je voudrais ouvrir un compte courant.", en: 'I’d like to open a current account.' },
      { fr: "Quels documents faut-il fournir ?", en: 'Which documents do I need to provide?' },
      { fr: "J'ai oublié mon code PIN.", en: 'I’ve forgotten my PIN.' },
      { fr: "Ma carte a été bloquée.", en: 'My card has been blocked.' },
      { fr: "Y a-t-il des frais de tenue de compte ?", en: 'Are there account maintenance fees?' },
      { fr: "Je voudrais faire un virement.", en: 'I’d like to make a transfer.' },
      { fr: "Pouvez-vous me donner un RIB ?", en: 'Can you give me a bank identity statement (RIB)?' },
      { fr: "Quand vais-je recevoir ma carte ?", en: 'When will I receive my card?' },
    ],
  },
  {
    id: 'housing',
    title: 'Renting a flat',
    emoji: '🏠',
    blurb: 'Viewings, deposits, agents',
    scenarioId: 'logement',
    level: 'B1',
    phrases: [
      { fr: "Le loyer est de combien par mois ?", en: 'How much is the rent per month?' },
      { fr: "Les charges sont-elles comprises ?", en: 'Are service charges included?' },
      { fr: "Y a-t-il un dépôt de garantie ?", en: 'Is there a security deposit?' },
      { fr: "Est-ce meublé ?", en: 'Is it furnished?' },
      { fr: "Quand puis-je emménager ?", en: 'When can I move in?' },
      { fr: "Le bail est pour quelle durée ?", en: 'How long is the lease for?' },
      { fr: "Y a-t-il un parking ?", en: 'Is there parking?' },
      { fr: "Je peux revoir l'appartement demain ?", en: 'Can I view the flat again tomorrow?' },
    ],
  },
  {
    id: 'flatshare',
    title: 'Flat-share',
    emoji: '🔑',
    blurb: 'Viewings, house rules, roommates',
    scenarioId: 'colloc',
    level: 'A2–B1',
    phrases: [
      { fr: "La chambre est encore disponible ?", en: 'Is the room still available?' },
      { fr: "Combien de colocataires y a-t-il ?", en: 'How many flatmates are there?' },
      { fr: "Comment se passe le ménage ?", en: 'How does the cleaning work?' },
      { fr: "On partage les courses ?", en: 'Do we share the shopping?' },
      { fr: "Est-ce que les fêtes sont autorisées ?", en: 'Are parties allowed?' },
      { fr: "Je travaille souvent le soir.", en: 'I often work in the evening.' },
      { fr: "On peut se revoir la semaine prochaine ?", en: 'Can we meet again next week?' },
      { fr: "Ça me plaît bien — je suis intéressé(e).", en: 'I like it — I’m interested.' },
    ],
  },
  {
    id: 'post',
    title: 'Post office',
    emoji: '📦',
    blurb: 'Parcels, stamps, delivery',
    scenarioId: 'poste',
    level: 'A2',
    phrases: [
      { fr: "Je voudrais envoyer ce colis à l'étranger.", en: 'I’d like to send this parcel abroad.' },
      { fr: "Combien de temps pour la livraison ?", en: 'How long for delivery?' },
      { fr: "Je voudrais un recommandé avec accusé de réception.", en: 'I’d like registered post with proof of receipt.' },
      { fr: "Des timbres pour une lettre, s'il vous plaît.", en: 'Stamps for a letter, please.' },
      { fr: "Y a-t-il un suivi en ligne ?", en: 'Is there online tracking?' },
      { fr: "Le poids maximum, c'est combien ?", en: 'What’s the maximum weight?' },
      { fr: "Je viens récupérer un colis.", en: 'I’ve come to collect a parcel.' },
      { fr: "Voici ma pièce d'identité.", en: 'Here’s my ID.' },
    ],
  },
  {
    id: 'supermarket',
    title: 'Supermarket',
    emoji: '🛒',
    blurb: 'Finding items, self-checkout, deals',
    scenarioId: 'supermarche',
    level: 'A1–A2',
    phrases: [
      { fr: "Pardon, où se trouvent les yaourts ?", en: 'Excuse me, where are the yoghurts?' },
      { fr: "Avez-vous du pain sans gluten ?", en: 'Do you have gluten-free bread?' },
      { fr: "C'est le rayon bio ?", en: 'Is this the organic aisle?' },
      { fr: "Est-ce qu'il y a une promotion ?", en: 'Is there a special offer?' },
      { fr: "Je n'ai pas de carte de fidélité.", en: 'I don’t have a loyalty card.' },
      { fr: "Sac plastique ou sac en papier ?", en: 'Plastic bag or paper bag?' },
      { fr: "C'est en libre-service, non ?", en: 'It’s self-service, right?' },
      { fr: "Le code-barres ne passe pas.", en: 'The barcode won’t scan.' },
    ],
  },
  {
    id: 'bakery',
    title: 'Bakery',
    emoji: '🥖',
    blurb: 'Morning orders and polite queues',
    scenarioId: 'boulangerie2',
    level: 'A1',
    phrases: [
      { fr: "Bonjour, une baguette tradition, s'il vous plaît.", en: 'Hello, a traditional baguette, please.' },
      { fr: "Deux croissants et un pain au chocolat.", en: 'Two croissants and a pain au chocolat.' },
      { fr: "C'est tout, merci.", en: 'That’s all, thank you.' },
      { fr: "Vous avez encore des chaussons aux pommes ?", en: 'Do you still have apple turnovers?' },
      { fr: "Une tarte aux fraises pour six personnes.", en: 'A strawberry tart for six people.' },
      { fr: "C'est pour emporter.", en: 'It’s to take away.' },
      { fr: "Vous prenez les tickets restaurant ?", en: 'Do you take meal vouchers?' },
      { fr: "Bonne journée !", en: 'Have a good day!' },
    ],
  },
  {
    id: 'museum',
    title: 'Museum',
    emoji: '🖼️',
    blurb: 'Tickets, audio guides, highlights',
    scenarioId: 'musee',
    level: 'A2',
    phrases: [
      { fr: "Deux billets adultes, s'il vous plaît.", en: 'Two adult tickets, please.' },
      { fr: "Y a-t-il un tarif étudiant ?", en: 'Is there a student rate?' },
      { fr: "Est-ce que la photo est autorisée ?", en: 'Is photography allowed?' },
      { fr: "Où sont les vestiaires ?", en: 'Where is the cloakroom?' },
      { fr: "Je voudrais un audioguide en anglais.", en: 'I’d like an audio guide in English.' },
      { fr: "Qu'est-ce qu'il ne faut pas manquer ?", en: 'What shouldn’t I miss?' },
      { fr: "À quelle heure ferme le musée ?", en: 'What time does the museum close?' },
      { fr: "Y a-t-il une exposition temporaire ?", en: 'Is there a temporary exhibition?' },
    ],
  },
  {
    id: 'cinema',
    title: 'Cinema',
    emoji: '🎬',
    blurb: 'Showtimes, seats, snacks',
    scenarioId: 'cinema',
    level: 'A2',
    phrases: [
      { fr: "Deux places pour le film de 20 heures.", en: 'Two seats for the 8pm showing.' },
      { fr: "En VF ou en VO ?", en: 'Dubbed (French) or original version?' },
      { fr: "Il reste des places au centre ?", en: 'Are there still seats in the middle?' },
      { fr: "Un grand pop-corn et deux eaux, s'il vous plaît.", en: 'A large popcorn and two waters, please.' },
      { fr: "C'est sous-titré en français ?", en: 'Is it subtitled in French?' },
      { fr: "Combien dure le film ?", en: 'How long is the film?' },
      { fr: "On peut prendre un abonnement ?", en: 'Can we get a subscription / pass?' },
      { fr: "La séance a déjà commencé ?", en: 'Has the screening already started?' },
    ],
  },
  {
    id: 'hairdresser',
    title: 'Hairdresser',
    emoji: '💇',
    blurb: 'Cuts, colour, appointments',
    scenarioId: 'coiffeur',
    level: 'A2',
    phrases: [
      { fr: "Je voudrais juste une coupe.", en: 'I’d just like a cut.' },
      { fr: "Pas trop court, s'il vous plaît.", en: 'Not too short, please.' },
      { fr: "Je garde la même longueur.", en: 'I’m keeping the same length.' },
      { fr: "Vous pouvez juste éclaircir les pointes ?", en: 'Can you just lighten the ends?' },
      { fr: "J'ai les cheveux sensibles.", en: 'I have sensitive hair / scalp.' },
      { fr: "Combien de temps ça va prendre ?", en: 'How long will it take?' },
      { fr: "C'est combien pour une coupe homme ?", en: 'How much for a men’s cut?' },
      { fr: "Je reviens dans six semaines.", en: 'I’ll come back in six weeks.' },
    ],
  },
  {
    id: 'university',
    title: 'University & classes',
    emoji: '🎓',
    blurb: 'Office hours, deadlines, feedback',
    scenarioId: 'cours',
    level: 'B1',
    phrases: [
      { fr: "Je n'ai pas bien compris le devoir.", en: 'I didn’t quite understand the assignment.' },
      { fr: "Puis-je vous voir pendant vos permanences ?", en: 'May I see you during your office hours?' },
      { fr: "La date limite, c'est vendredi, c'est bien ça ?", en: 'The deadline is Friday, right?' },
      { fr: "Est-ce que je peux rendre un brouillon ?", en: 'Can I submit a draft?' },
      { fr: "J'ai manqué le cours d'hier.", en: 'I missed yesterday’s class.' },
      { fr: "Y a-t-il des lectures obligatoires ?", en: 'Are there required readings?' },
      { fr: "Comment se passe l'examen ?", en: 'How does the exam work?' },
      { fr: "Merci pour vos commentaires.", en: 'Thank you for your feedback.' },
    ],
  },
  {
    id: 'police',
    title: 'Police station',
    emoji: '🚓',
    blurb: 'Reports, lost documents, help',
    scenarioId: 'commissariat',
    level: 'B1',
    phrases: [
      { fr: "Je voudrais porter plainte.", en: 'I’d like to file a complaint / report.' },
      { fr: "On m'a volé mon portefeuille.", en: 'My wallet was stolen.' },
      { fr: "J'ai perdu mon passeport.", en: 'I’ve lost my passport.' },
      { fr: "Voici mon numéro de téléphone.", en: 'Here’s my phone number.' },
      { fr: "Ça s'est passé vers 22 heures.", en: 'It happened around 10pm.' },
      { fr: "Avez-vous un numéro de dossier ?", en: 'Do you have a case number?' },
      { fr: "J'ai besoin d'un récépissé pour mon assurance.", en: 'I need a receipt for my insurance.' },
      { fr: "Parlez-vous anglais ?", en: 'Do you speak English?' },
    ],
  },
  {
    id: 'townhall',
    title: 'Town hall (mairie)',
    emoji: '🏛️',
    blurb: 'Admin, forms, appointments',
    scenarioId: 'mairie',
    level: 'B1',
    phrases: [
      { fr: "Je viens pour une demande d'acte de naissance.", en: 'I’ve come for a birth certificate request.' },
      { fr: "Faut-il prendre rendez-vous ?", en: 'Do I need an appointment?' },
      { fr: "Quels justificatifs dois-je apporter ?", en: 'Which supporting documents should I bring?' },
      { fr: "Je suis nouvellement arrivé(e) dans la commune.", en: 'I’ve just moved into the municipality.' },
      { fr: "Combien de temps pour le traitement du dossier ?", en: 'How long does processing take?' },
      { fr: "Puis-je faire la démarche en ligne ?", en: 'Can I do this online?' },
      { fr: "Où se trouve le guichet d'accueil ?", en: 'Where is the reception desk?' },
      { fr: "Merci pour votre aide.", en: 'Thank you for your help.' },
    ],
  },
  {
    id: 'phone',
    title: 'Phone & customer service',
    emoji: '📱',
    blurb: 'Orders, complaints, hold music',
    scenarioId: 'sav',
    level: 'B1',
    phrases: [
      { fr: "Bonjour, je vous appelle au sujet de ma commande.", en: 'Hello, I’m calling about my order.' },
      { fr: "Mon numéro de client est…", en: 'My customer number is…' },
      { fr: "Je n'ai toujours pas reçu mon colis.", en: 'I still haven’t received my parcel.' },
      { fr: "Pouvez-vous me rappeler ?", en: 'Can you call me back?' },
      { fr: "Je voudrais parler à un responsable.", en: 'I’d like to speak to a manager.' },
      { fr: "La ligne est mauvaise, vous m'entendez ?", en: 'The line is bad — can you hear me?' },
      { fr: "Je vais envoyer un mail de réclamation.", en: 'I’ll send a complaint email.' },
      { fr: "Merci, bonne journée.", en: 'Thank you, have a good day.' },
    ],
  },
  {
    id: 'neighbours',
    title: 'Neighbours',
    emoji: '🚪',
    blurb: 'Noise, favours, small talk',
    scenarioId: 'voisin',
    level: 'A2–B1',
    phrases: [
      { fr: "Bonjour, je suis votre nouveau voisin / nouvelle voisine.", en: 'Hello, I’m your new neighbour.' },
      { fr: "Désolé(e) pour le bruit hier soir.", en: 'Sorry about the noise last night.' },
      { fr: "Est-ce que je pourrais emprunter un tournevis ?", en: 'Could I borrow a screwdriver?' },
      { fr: "Vous savez où est la cave à vélos ?", en: 'Do you know where the bike storage is?' },
      { fr: "On organise un apéro demain, vous êtes libre ?", en: 'We’re having drinks tomorrow — are you free?' },
      { fr: "Le digicode a changé, vous l'avez ?", en: 'The door code has changed — do you have it?' },
      { fr: "Bonne soirée !", en: 'Have a good evening!' },
      { fr: "Si vous avez besoin d'aide, n'hésitez pas.", en: 'If you need help, don’t hesitate.' },
    ],
  },
  {
    id: 'carpool',
    title: 'Carpool (covoiturage)',
    emoji: '🚗',
    blurb: 'Meeting points, timing, chat',
    scenarioId: 'covoiturage',
    level: 'A2',
    phrases: [
      { fr: "On se retrouve où exactement ?", en: 'Where exactly are we meeting?' },
      { fr: "Je serai là dans dix minutes.", en: 'I’ll be there in ten minutes.' },
      { fr: "Vous avez beaucoup de bagages ?", en: 'Do you have a lot of luggage?' },
      { fr: "On peut faire une pause en route ?", en: 'Can we stop on the way?' },
      { fr: "Je vous envoie mon numéro.", en: 'I’ll send you my number.' },
      { fr: "Merci pour le trajet, bonne continuation !", en: 'Thanks for the ride — take care!' },
      { fr: "Le péage, on le partage ?", en: 'Shall we split the toll?' },
      { fr: "Je descends au centre-ville.", en: 'I’m getting off in the city centre.' },
    ],
  },
  {
    id: 'gym',
    title: 'Gym & sports',
    emoji: '🏋️',
    blurb: 'Memberships, classes, equipment',
    scenarioId: 'gym',
    level: 'A2',
    phrases: [
      { fr: "Je voudrais m'inscrire à la salle.", en: 'I’d like to join the gym.' },
      { fr: "Y a-t-il un essai gratuit ?", en: 'Is there a free trial?' },
      { fr: "À quelle heure est le cours de yoga ?", en: 'What time is the yoga class?' },
      { fr: "Où sont les vestiaires ?", en: 'Where are the changing rooms?' },
      { fr: "Est-ce que je peux réserver un cours en ligne ?", en: 'Can I book a class online?' },
      { fr: "La machine est en panne.", en: 'The machine is broken.' },
      { fr: "Combien de mois d'engagement ?", en: 'How many months’ commitment?' },
      { fr: "Avez-vous une serviette ?", en: 'Do you have a towel?' },
    ],
  },
  {
    id: 'beach',
    title: 'Beach & holidays',
    emoji: '🏖️',
    blurb: 'Sun, sea and seasonal small talk',
    scenarioId: 'plage',
    level: 'A1–A2',
    phrases: [
      { fr: "L'eau est bonne ?", en: 'Is the water nice?' },
      { fr: "Où peut-on louer des parasols ?", en: 'Where can we hire parasols?' },
      { fr: "Y a-t-il des méduses ?", en: 'Are there jellyfish?' },
      { fr: "C'est une plage surveillée ?", en: 'Is this a lifeguarded beach?' },
      { fr: "On se retrouve près du snack.", en: 'We’ll meet near the snack bar.' },
      { fr: "Il fait trop chaud — on rentre ?", en: 'It’s too hot — shall we head back?' },
      { fr: "Vous avez de la crème solaire ?", en: 'Do you have sunscreen?' },
      { fr: "Quelle belle journée !", en: 'What a lovely day!' },
    ],
  },
  {
    id: 'ski',
    title: 'Ski resort',
    emoji: '⛷️',
    blurb: 'Passes, slopes, hire shops',
    scenarioId: 'ski',
    level: 'A2',
    phrases: [
      { fr: "Un forfait journée, s'il vous plaît.", en: 'A day pass, please.' },
      { fr: "Je voudrais louer des skis.", en: 'I’d like to hire skis.' },
      { fr: "Quelle est ma pointure en chaussures de ski ?", en: 'What’s my ski boot size?' },
      { fr: "Les pistes bleues sont par où ?", en: 'Which way are the blue runs?' },
      { fr: "Le télésiège est fermé aujourd'hui ?", en: 'Is the chairlift closed today?' },
      { fr: "Y a-t-il des cours pour débutants ?", en: 'Are there lessons for beginners?' },
      { fr: "Attention, ça glisse !", en: 'Careful, it’s slippery!' },
      { fr: "On se retrouve au pied de la piste.", en: 'We’ll meet at the bottom of the slope.' },
    ],
  },
  {
    id: 'smalltalk',
    title: 'Small talk',
    emoji: '💬',
    blurb: 'Weather, weekends, polite fillers',
    level: 'A1–A2',
    phrases: [
      { fr: "Il fait beau aujourd'hui, non ?", en: 'Nice weather today, isn’t it?' },
      { fr: "Vous avez passé un bon week-end ?", en: 'Did you have a good weekend?' },
      { fr: "Ça va, et vous ?", en: 'I’m fine, and you?' },
      { fr: "On se connaît, non ?", en: 'We know each other, don’t we?' },
      { fr: "Qu'est-ce que vous faites dans la vie ?", en: 'What do you do for a living?' },
      { fr: "Moi aussi, j'adore ça.", en: 'I love that too.' },
      { fr: "Il faut que j'y aille.", en: 'I’ve got to go.' },
      { fr: "On se revoit bientôt ?", en: 'See you soon?' },
      { fr: "Ravi(e) de vous avoir rencontré(e).", en: 'Nice to have met you.' },
      { fr: "Passez une bonne soirée.", en: 'Have a nice evening.' },
    ],
  },
  {
    id: 'dining_home',
    title: 'Dinner at someone’s home',
    emoji: '🍷',
    blurb: 'Arriving, compliments, helping out',
    scenarioId: 'diner',
    level: 'A2–B1',
    phrases: [
      { fr: "Merci de m'avoir invité(e).", en: 'Thank you for inviting me.' },
      { fr: "Où est-ce que je peux laisser mon manteau ?", en: 'Where can I leave my coat?' },
      { fr: "C'est délicieux — vous avez une recette ?", en: 'It’s delicious — do you have a recipe?' },
      { fr: "Je peux vous aider à débarrasser ?", en: 'Can I help clear the table?' },
      { fr: "Encore un peu de vin ? Non merci, ça ira.", en: 'A little more wine? No thanks, I’m fine.' },
      { fr: "Je dois y aller, il se fait tard.", en: 'I should go — it’s getting late.' },
      { fr: "Ce fut une super soirée.", en: 'It was a great evening.' },
      { fr: "On vous invite la prochaine fois.", en: 'We’ll invite you next time.' },
    ],
  },
  {
    id: 'library',
    title: 'Library',
    emoji: '📚',
    blurb: 'Cards, loans, quiet study',
    scenarioId: 'bibliotheque',
    level: 'A2',
    phrases: [
      { fr: "Je voudrais m'inscrire à la bibliothèque.", en: 'I’d like to join the library.' },
      { fr: "Combien de livres puis-je emprunter ?", en: 'How many books can I borrow?' },
      { fr: "Où est la section romans ?", en: 'Where is the fiction section?' },
      { fr: "Est-ce que je peux prolonger mon emprunt ?", en: 'Can I renew my loan?' },
      { fr: "Y a-t-il du Wi-Fi gratuit ?", en: 'Is there free Wi-Fi?' },
      { fr: "Les photocopies se font où ?", en: 'Where do I make photocopies?' },
      { fr: "À quelle heure fermez-vous ?", en: 'What time do you close?' },
      { fr: "Merci, bonne journée.", en: 'Thank you, have a good day.' },
    ],
  },
  {
    id: 'garage',
    title: 'Garage / car repair',
    emoji: '🔧',
    blurb: 'Breakdowns, quotes, pick-up',
    scenarioId: 'garagiste',
    level: 'B1',
    phrases: [
      { fr: "Ma voiture ne démarre plus.", en: 'My car won’t start any more.' },
      { fr: "Il y a un bruit bizarre à l'avant.", en: 'There’s a strange noise at the front.' },
      { fr: "Pouvez-vous me faire un devis ?", en: 'Can you give me a quote?' },
      { fr: "Combien de temps pour la réparation ?", en: 'How long for the repair?' },
      { fr: "Est-ce que les pièces sont d'origine ?", en: 'Are the parts original?' },
      { fr: "Je peux laisser la voiture ce matin ?", en: 'Can I leave the car this morning?' },
      { fr: "Vous acceptez la carte bleue ?", en: 'Do you take bank cards?' },
      { fr: "Je viens récupérer mon véhicule.", en: 'I’ve come to collect my vehicle.' },
    ],
  },
  {
    id: 'dentist',
    title: 'Dentist',
    emoji: '🦷',
    blurb: 'Pain, appointments, aftercare',
    scenarioId: 'dentiste',
    level: 'A2–B1',
    phrases: [
      { fr: "J'ai très mal à une dent.", en: 'I have a bad toothache.' },
      { fr: "C'est une urgence.", en: 'It’s an emergency.' },
      { fr: "La douleur est d'un côté seulement.", en: 'The pain is only on one side.' },
      { fr: "J'ai une couronne qui bouge.", en: 'I have a crown that is loose.' },
      { fr: "Faut-il une radio ?", en: 'Do I need an X-ray?' },
      { fr: "Est-ce que ça va faire mal ?", en: 'Is it going to hurt?' },
      { fr: "Je suis un peu stressé(e).", en: 'I’m a bit stressed / nervous.' },
      { fr: "Quand dois-je revenir ?", en: 'When should I come back?' },
    ],
  },
  {
    id: 'camping',
    title: 'Camping',
    emoji: '⛺',
    blurb: 'Pitches, facilities, rules',
    scenarioId: 'camping',
    level: 'A2',
    phrases: [
      { fr: "Avez-vous de la place pour une tente ?", en: 'Do you have space for a tent?' },
      { fr: "Où sont les sanitaires ?", en: 'Where are the toilets / showers?' },
      { fr: "Y a-t-il du courant sur l'emplacement ?", en: 'Is there electricity on the pitch?' },
      { fr: "Jusqu'à quelle heure peut-on faire du bruit ?", en: 'Until what time can we make noise?' },
      { fr: "Le Wi-Fi est gratuit ?", en: 'Is Wi-Fi free?' },
      { fr: "On part demain matin.", en: 'We’re leaving tomorrow morning.' },
      { fr: "Où jeter les ordures ?", en: 'Where do we put the rubbish?' },
      { fr: "Il y a une boulangerie près d'ici ?", en: 'Is there a bakery nearby?' },
    ],
  },
];

export const getSituation = (id) => SITUATIONS.find((s) => s.id === id);

export function situationPhraseCount() {
  return SITUATIONS.reduce((n, s) => n + s.phrases.length, 0);
}

export function situationStats() {
  return SITUATIONS.map((s) => ({
    id: s.id,
    title: s.title,
    count: s.phrases.length,
    hasRoleplay: Boolean(s.scenarioId),
    level: s.level || null,
  }));
}

/** Stable tip of the day — rotates through all phrases by calendar day. */
export function situationTipOfDay(date = new Date()) {
  const all = [];
  for (const s of SITUATIONS) {
    for (const p of s.phrases) {
      all.push({ situationId: s.id, title: s.title, emoji: s.emoji, fr: p.fr, en: p.en });
    }
  }
  if (!all.length) return null;
  const start = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const day = Math.floor(start / 86_400_000);
  const tip = all[day % all.length];
  return { ...tip, id: `${tip.situationId}:${day % all.length}` };
}

/** Case-insensitive search over titles, blurbs and phrase text. */
export function searchSituations(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const hits = [];
  for (const s of SITUATIONS) {
    const bag = [s.title, s.blurb, s.id, ...(s.phrases.flatMap((p) => [p.fr, p.en]))]
      .join(' ')
      .toLowerCase();
    if (!bag.includes(q)) continue;
    const matchingPhrases = s.phrases.filter(
      (p) => p.fr.toLowerCase().includes(q) || p.en.toLowerCase().includes(q),
    );
    hits.push({
      situationId: s.id,
      title: s.title,
      emoji: s.emoji,
      blurb: s.blurb,
      scenarioId: s.scenarioId,
      matchCount: matchingPhrases.length || 1,
      sample: matchingPhrases[0] || s.phrases[0],
    });
  }
  return hits;
}

// ---- mock exam (DELF-style: comprehension, grammar & usage) ----

export const EXAM = {
  title: 'Mock placement exam',
  blurb: 'A short exam across grammar, vocabulary and real-world usage.',
  questions: [
    { skill: 'Grammar', q: 'Complétez : « Hier, je ___ au marché. »', options: ['vais', 'suis allé', 'irai'], answer: 1, why: 'Passé composé for a completed past action.' },
    { skill: 'Usage', q: 'At a shop, you enter and first say…', options: ['«Bonjour»', '«C’est combien ?»', '«Au revoir»'], answer: 0, why: 'Always greet before anything else.' },
    { skill: 'Vocabulary', q: '« L’addition » means…', options: ['the menu', 'the bill', 'the tip'], answer: 1, why: '«L’addition» is the restaurant bill.' },
    { skill: 'Grammar', q: 'Complétez : « Il faut que tu ___ prudent. »', options: ['es', 'sois', 'seras'], answer: 1, why: '«Il faut que» triggers the subjonctif.' },
    { skill: 'Usage', q: 'At the airport, « un vol en retard » is…', options: ['a cancelled flight', 'a delayed flight', 'a full flight'], answer: 1, why: '«En retard» = late/delayed.' },
    { skill: 'Vocabulary', q: 'At the pharmacy, « une ordonnance » is…', options: ['a prescription', 'an order of food', 'an appointment'], answer: 0, why: '«Une ordonnance» is a medical prescription.' },
    { skill: 'Grammar', q: 'Complétez : « Si j’avais le temps, je ___ plus. »', options: ['voyage', 'voyagerais', 'voyagerai'], answer: 1, why: 'Conditionnel after «si + imparfait».' },
    { skill: 'Usage', q: 'In a job interview, « un point fort » is…', options: ['a strength', 'a weakness', 'a salary'], answer: 0, why: '«Un point fort» = a strong point / strength.' },
    { skill: 'Vocabulary', q: '« Un aller-retour » is a…', options: ['one-way ticket', 'return ticket', 'season pass'], answer: 1, why: '«Aller-retour» = round trip / return.' },
    { skill: 'Grammar', q: 'Choisissez : « Je cherche la femme ___ j’ai rencontrée. »', options: ['qui', 'que', 'dont'], answer: 1, why: '«Que» is the direct object of «rencontrer».' },
    { skill: 'Usage', q: 'At the hotel, « le check-out » is usually…', options: ['when you arrive', 'when you leave the room', 'breakfast time'], answer: 1, why: 'Check-out is departure from the room.' },
    { skill: 'Vocabulary', q: '« Un forfait journée » at a ski resort is…', options: ['a day pass', 'a free lesson', 'a hotel room'], answer: 0, why: '«Forfait» = ski pass package.' },
    { skill: 'Usage', q: 'At the bakery you typically order with…', options: ['«Donne-moi…»', '«Je voudrais… s’il vous plaît»', '«J’exige…»'], answer: 1, why: 'Polite «je voudrais» + please is standard.' },
    { skill: 'Vocabulary', q: 'At the bank, a « RIB » is…', options: ['a credit card', 'bank account identity details', 'a loan'], answer: 1, why: 'RIB = Relevé d’Identité Bancaire.' },
    { skill: 'Grammar', q: 'Complétez : « Je ___ mon passeport. » (I have lost…)', options: ['perd', 'ai perdu', 'perdrai'], answer: 1, why: 'Passé composé of «perdre» with «avoir».' },
    { skill: 'Usage', q: 'Filing a police report: « porter plainte » means…', options: ['to complain about food', 'to file an official complaint', 'to pay a fine'], answer: 1, why: 'Legal phrase for filing a report.' },
    { skill: 'Vocabulary', q: '« Les charges » on a rental often means…', options: ['criminal charges', 'service / utility charges', 'batteries'], answer: 1, why: 'In housing, charges = condo/service fees.' },
    { skill: 'Usage', q: 'Cinema: « VO » means the film is…', options: ['dubbed into French', 'in the original language', 'without sound'], answer: 1, why: 'Version originale; VF = French dub.' },
    { skill: 'Vocabulary', q: '« Un devis » from a garage is…', options: ['a receipt', 'a quote / estimate', 'a spare part'], answer: 1, why: 'Devis = estimate before work.' },
    { skill: 'Grammar', q: 'Complétez : « Il y a ___ circulation. »', options: ['beaucoup de', 'très', 'trop'], answer: 0, why: '«Beaucoup de» + uncountable noun (circulation).' },
  ],
};

// CEFR-ish band from a percentage score.
export function examBand(pct) {
  if (pct >= 90) return { band: 'C1', note: 'Confident and precise — exam-ready.' };
  if (pct >= 70) return { band: 'B2', note: 'Strong. Polish the trickier grammar.' };
  if (pct >= 50) return { band: 'B1', note: 'Solid footing — keep drilling usage.' };
  if (pct >= 30) return { band: 'A2', note: 'Getting there. Review the phrasebook.' };
  return { band: 'A1', note: 'Early days — the situations above will help.' };
}
