// Roadmap data for the Learning Path: twelve units per goal, five lessons
// each — sixty lessons a goal. Units 1–6 are the "getting by" arc; units
// 7–12 deepen everything: consolidation grammar, stories & classics,
// listening immersion, admin & errands, free conversation, and a finale.
// Kept in its own module so the path engine (path.js) stays small.

// Lesson types map onto the app's activity surfaces:
//   scenario   → a conversation session in the given scenario (≥1 turn + End Session)
//   dictation  → N dictée sentences checked
//   cards      → N flashcards rated
//   quickfire  → one 45s improv completed
//   grammar    → finish the given topic's scored quiz
//   reading    → finish the given text's comprehension quiz
//   listening  → finish the given track's comprehension quiz
//   checkpoint → a scored conversation; pass requires report avg ≥ passScore
const L = {
  scenario: (id, title) => ({ type: 'scenario', scenarioId: id, title, need: 1 }),
  dictation: (title, need = 3) => ({ type: 'dictation', title, need }),
  cards: (title, need = 5) => ({ type: 'cards', title, need }),
  quickfire: (title) => ({ type: 'quickfire', title, need: 1 }),
  grammar: (topicId, title) => ({ type: 'grammar', topicId, title, need: 1 }),
  reading: (textId, title) => ({ type: 'reading', textId, title, need: 1 }),
  listening: (trackId, title) => ({ type: 'listening', trackId, title, need: 1 }),
  checkpoint: (id, title) => ({ type: 'checkpoint', scenarioId: id, title, need: 1, passScore: 70 }),
};

const ROADMAPS = {
  travel: [
    { id: 'tr1', title: 'Café & Restaurant', lessons: [
      L.scenario('bistro', 'Order lunch at a bistro'),
      L.grammar('present', 'Grammar: the present tense'),
      L.cards('Filler words for small talk'),
      L.dictation('Train your ear: menus & greetings'),
      L.checkpoint('bistro', 'Checkpoint: handle a full bistro visit'),
    ]},
    { id: 'tr2', title: 'Getting Around', lessons: [
      L.scenario('vol', 'Rebook a cancelled flight'),
      L.reading('read-lyon', 'Read: a weekend in Lyon'),
      L.quickfire('Improv: describe your journey'),
      L.dictation('Train your ear: announcements'),
      L.checkpoint('vol', 'Checkpoint: negotiate with the airline'),
    ]},
    { id: 'tr3', title: 'Markets & Services', lessons: [
      L.scenario('marche', 'Shop at the open-air market'),
      L.scenario('poste', 'Send a package abroad'),
      L.grammar('articles', 'Grammar: articles & quantities'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('marche', 'Checkpoint: haggle like a local'),
    ]},
    { id: 'tr4', title: 'Money & Errands', lessons: [
      L.scenario('banque', 'Open an account at the bank'),
      L.grammar('comparatif', 'Grammar: comparing things'),
      L.listening('news-matin', 'Listen: the morning news'),
      L.dictation('Train your ear: numbers & prices'),
      L.checkpoint('banque', 'Checkpoint: sort out the bank'),
    ]},
    { id: 'tr5', title: 'Health Abroad', lessons: [
      L.scenario('pharmacie', 'Ask a pharmacist for help'),
      L.scenario('medecin', 'Describe symptoms to a doctor'),
      L.listening('dial-pharmacie', 'Listen: at the pharmacy'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('medecin', 'Checkpoint: get through the appointment'),
    ]},
    { id: 'tr6', title: 'Living Local', lessons: [
      L.scenario('colloc', 'View a flat-share'),
      L.scenario('logement', 'Rent a flat from an agent'),
      L.reading('article-cafe', 'Read: café-terrace culture'),
      L.quickfire('Improv: your ideal neighbourhood'),
      L.checkpoint('logement', 'Checkpoint: land the lease'),
    ]},
    { id: 'tr7', title: 'Salon Small Talk', lessons: [
      L.scenario('coiffeur', 'Chat through a haircut'),
      L.grammar('negation', 'Grammar: saying no, naturally'),
      L.listening('dia-resto', 'Listen: dinner-table French'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('coiffeur', 'Checkpoint: small talk in the chair'),
    ]},
    { id: 'tr8', title: 'Past Adventures', lessons: [
      L.grammar('passe-compose', 'Grammar: telling what happened'),
      L.reading('read-boulangerie', 'Read: a first-week story'),
      L.quickfire('Improv: your best trip, in the past tense'),
      L.dictation('Train your ear: travel stories'),
      L.checkpoint('bistro', 'Checkpoint: swap stories over coffee'),
    ]},
    { id: 'tr9', title: 'Radio & Rumours', lessons: [
      L.listening('pod-paris', 'Listen: a year in Paris'),
      L.listening('news-matin', 'Listen: headlines at full speed'),
      L.reading('news-greve', 'Read: strike day, in print'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('marche', 'Checkpoint: discuss the news at the stall'),
    ]},
    { id: 'tr10', title: 'Plans & Maybes', lessons: [
      L.grammar('futur-conditionnel', 'Grammar: plans and polite maybes'),
      L.scenario('vol', 'Change your plans mid-trip'),
      L.quickfire('Improv: your dream itinerary'),
      L.dictation('Train your ear: forecasts & plans'),
      L.checkpoint('vol', 'Checkpoint: replan the whole trip'),
    ]},
    { id: 'tr11', title: 'Neighbours & Feelings', lessons: [
      L.scenario('colloc', 'Sort out a flatmate issue'),
      L.listening('dia-voisin', 'Listen: a neighbourly dispute'),
      L.grammar('subjonctif', 'Grammar: il faut que…'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('colloc', 'Checkpoint: keep the peace at home'),
    ]},
    { id: 'tr12', title: 'The Local', lessons: [
      L.grammar('pronoms', 'Grammar: pronouns like a native'),
      L.reading('book-corbeau', 'Read: a La Fontaine classic'),
      L.scenario('libre', 'Free talk: anything goes'),
      L.quickfire('Improv: convince us you live here'),
      L.checkpoint('marche', 'Checkpoint: pass for a local'),
    ]},
  ],
  school: [
    { id: 'sc1', title: 'Campus Life', lessons: [
      L.scenario('colloc', 'Find student housing'),
      L.grammar('present', 'Grammar: the present tense'),
      L.cards('Conversational glue words'),
      L.dictation('Train your ear: campus chatter'),
      L.checkpoint('colloc', 'Checkpoint: settle the flat-share'),
    ]},
    { id: 'sc2', title: 'Professors & Assignments', lessons: [
      L.scenario('cours', 'Office hours with your professor'),
      L.grammar('passe-compose', 'Grammar: talking about the past'),
      L.quickfire('Improv: explain what you study'),
      L.dictation('Train your ear: instructions'),
      L.checkpoint('cours', 'Checkpoint: negotiate an extension'),
    ]},
    { id: 'sc3', title: 'Everyday Errands', lessons: [
      L.scenario('poste', 'Post office paperwork'),
      L.scenario('bistro', 'Coffee between lectures'),
      L.listening('pod-habitudes', 'Listen: a morning routine'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('bistro', 'Checkpoint: a full café conversation'),
    ]},
    { id: 'sc4', title: 'Reading & Research', lessons: [
      L.reading('art-boulangerie', 'Read: a magazine feature'),
      L.grammar('pronoms', 'Grammar: object pronouns'),
      L.reading('book-corbeau', 'Read: a La Fontaine fable'),
      L.dictation('Train your ear: academic French'),
      L.checkpoint('cours', 'Checkpoint: discuss what you read'),
    ]},
    { id: 'sc5', title: 'Student Budget', lessons: [
      L.scenario('banque', 'Set up a student account'),
      L.scenario('logement', 'Negotiate a student let'),
      L.grammar('comparatif', 'Grammar: comparing options'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('banque', 'Checkpoint: money matters, in French'),
    ]},
    { id: 'sc6', title: 'Presentations', lessons: [
      L.quickfire('Improv: defend an opinion'),
      L.scenario('cours', 'Discuss your presentation plan'),
      L.grammar('subjonctif', 'Grammar: the subjunctive'),
      L.dictation('Train your ear: fast questions'),
      L.checkpoint('cours', 'Checkpoint: field the professor’s questions'),
    ]},
    { id: 'sc7', title: 'Student Health', lessons: [
      L.scenario('medecin', 'A campus-clinic visit'),
      L.scenario('pharmacie', 'Pick up a prescription'),
      L.listening('dial-pharmacie', 'Listen: at the pharmacy'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('medecin', 'Checkpoint: explain what hurts'),
    ]},
    { id: 'sc8', title: 'Debate Club', lessons: [
      L.grammar('negation', 'Grammar: disagreeing precisely'),
      L.listening('pod-teletravail', 'Listen: a structured debate'),
      L.quickfire('Improv: argue the other side'),
      L.dictation('Train your ear: rapid rebuttals'),
      L.checkpoint('cours', 'Checkpoint: win the seminar debate'),
    ]},
    { id: 'sc9', title: 'City Weekend', lessons: [
      L.reading('read-lyon', 'Read: a weekend in Lyon'),
      L.scenario('marche', 'Shop for a picnic'),
      L.listening('scene-gare', 'Listen: a platform farewell'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('marche', 'Checkpoint: plan the picnic out loud'),
    ]},
    { id: 'sc10', title: 'The Written Word', lessons: [
      L.grammar('articles', 'Grammar: articles, mastered'),
      L.reading('article-cafe', 'Read: essay-style prose'),
      L.reading('news-greve', 'Read: journalistic register'),
      L.dictation('Train your ear: dictée, exam style'),
      L.checkpoint('cours', 'Checkpoint: summarise an article aloud'),
    ]},
    { id: 'sc11', title: 'Future Plans', lessons: [
      L.grammar('futur-conditionnel', 'Grammar: your five-year plan'),
      L.scenario('entretien', 'A placement interview'),
      L.quickfire('Improv: where you’ll be in five years'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('entretien', 'Checkpoint: impress the recruiter'),
    ]},
    { id: 'sc12', title: 'Graduation', lessons: [
      L.scenario('libre', 'Free talk: your year, reviewed'),
      L.listening('pod-paris', 'Listen: a year in Paris'),
      L.quickfire('Improv: your graduation speech'),
      L.dictation('Train your ear: the hard stuff'),
      L.checkpoint('cours', 'Checkpoint: the final oral'),
    ]},
  ],
  business: [
    { id: 'bu1', title: 'The Interview', lessons: [
      L.scenario('entretien', 'Introduce yourself and your background'),
      L.grammar('futur-conditionnel', 'Grammar: polite conditionals'),
      L.cards('Professional connectors'),
      L.dictation('Train your ear: formal French'),
      L.checkpoint('entretien', 'Checkpoint: the tough questions'),
    ]},
    { id: 'bu2', title: 'Meetings', lessons: [
      L.scenario('reunion', 'Give a project update'),
      L.listening('pod-teletravail', 'Listen: remote work, debated'),
      L.quickfire('Improv: pitch an idea in 45s'),
      L.dictation('Train your ear: meeting speak'),
      L.checkpoint('reunion', 'Checkpoint: handle a moved deadline'),
    ]},
    { id: 'bu3', title: 'Business Travel', lessons: [
      L.scenario('vol', 'Rebook a work trip'),
      L.scenario('bistro', 'A client lunch'),
      L.reading('article-cafe', 'Read: café culture for client chat'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('vol', 'Checkpoint: fix the travel crisis'),
    ]},
    { id: 'bu4', title: 'Banking & Admin', lessons: [
      L.scenario('banque', 'Discuss accounts and fees'),
      L.grammar('subjonctif', 'Grammar: il faut que…'),
      L.listening('news-matin', 'Listen: the business headlines'),
      L.dictation('Train your ear: figures & dates'),
      L.checkpoint('banque', 'Checkpoint: hold your own at the bank'),
    ]},
    { id: 'bu5', title: 'Relocation', lessons: [
      L.scenario('logement', 'Rent near the office'),
      L.scenario('colloc', 'Meet the new neighbours'),
      L.grammar('pronoms', 'Grammar: object pronouns'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('logement', 'Checkpoint: close the deal'),
    ]},
    { id: 'bu6', title: 'Office Small Talk', lessons: [
      L.quickfire('Improv: Monday-morning chat'),
      L.scenario('reunion', 'Wrap up the quarter'),
      L.listening('dia-voisin', 'Listen: handling a complaint'),
      L.dictation('Train your ear: colleagues talking'),
      L.checkpoint('reunion', 'Checkpoint: run the meeting yourself'),
    ]},
    { id: 'bu7', title: 'Precision French', lessons: [
      L.grammar('present', 'Grammar: present tense, airtight'),
      L.grammar('articles', 'Grammar: articles in contracts'),
      L.dictation('Train your ear: exact wording'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('reunion', 'Checkpoint: brief the team precisely'),
    ]},
    { id: 'bu8', title: 'The Press Review', lessons: [
      L.reading('news-greve', 'Read: a strike hits the news'),
      L.listening('news-matin', 'Listen: the morning bulletin'),
      L.quickfire('Improv: summarise the headlines'),
      L.dictation('Train your ear: newsroom pace'),
      L.checkpoint('reunion', 'Checkpoint: present the press review'),
    ]},
    { id: 'bu9', title: 'Difficult Conversations', lessons: [
      L.grammar('negation', 'Grammar: pushing back politely'),
      L.scenario('poste', 'Chase a lost shipment'),
      L.listening('dia-voisin', 'Listen: de-escalating a dispute'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('poste', 'Checkpoint: resolve the complaint'),
    ]},
    { id: 'bu10', title: 'Wellbeing at Work', lessons: [
      L.scenario('medecin', 'An occupational-health check'),
      L.listening('pod-habitudes', 'Listen: routines that work'),
      L.grammar('comparatif', 'Grammar: weighing options'),
      L.dictation('Train your ear: appointments'),
      L.checkpoint('medecin', 'Checkpoint: the check-up, in French'),
    ]},
    { id: 'bu11', title: 'Storytelling & Influence', lessons: [
      L.grammar('passe-compose', 'Grammar: narrate a project'),
      L.reading('book-corbeau', 'Read: flattery, a case study'),
      L.quickfire('Improv: tell the success story'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('entretien', 'Checkpoint: sell the narrative'),
    ]},
    { id: 'bu12', title: 'The Promotion', lessons: [
      L.scenario('libre', 'Free talk: your career, unscripted'),
      L.scenario('entretien', 'The internal interview'),
      L.quickfire('Improv: your leadership pitch'),
      L.dictation('Train your ear: executive French'),
      L.checkpoint('entretien', 'Checkpoint: earn the promotion'),
    ]},
  ],
  fluency: [
    { id: 'fl1', title: 'Everyday Ease', lessons: [
      L.scenario('bistro', 'A natural café exchange'),
      L.grammar('negation', 'Grammar: natural negation'),
      L.cards('Sound-native filler words'),
      L.quickfire('Improv: whatever comes up'),
      L.checkpoint('marche', 'Checkpoint: banter at the market'),
    ]},
    { id: 'fl2', title: 'Handling Friction', lessons: [
      L.scenario('vol', 'Push back politely'),
      L.scenario('poste', 'Bureaucracy without tears'),
      L.listening('dia-voisin', 'Listen: a neighbourly dispute'),
      L.dictation('Train your ear: fast French'),
      L.checkpoint('vol', 'Checkpoint: keep cool under pressure'),
    ]},
    { id: 'fl3', title: 'People & Stories', lessons: [
      L.scenario('colloc', 'Talk about yourself naturally'),
      L.reading('story-porte', 'Read: an interactive story'),
      L.quickfire('Improv: tell a story'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('colloc', 'Checkpoint: be genuinely likeable'),
    ]},
    { id: 'fl4', title: 'Around Town', lessons: [
      L.scenario('coiffeur', 'Chat through a haircut'),
      L.scenario('banque', 'An errand at the bank'),
      L.listening('pod-paris', 'Listen: a year in Paris'),
      L.grammar('pronoms', 'Grammar: object pronouns'),
      L.checkpoint('coiffeur', 'Checkpoint: small talk in the chair'),
    ]},
    { id: 'fl5', title: 'Body & Health', lessons: [
      L.scenario('medecin', 'Explain how you feel'),
      L.scenario('pharmacie', 'Follow the pharmacist’s advice'),
      L.listening('dial-pharmacie', 'Listen: at the pharmacy'),
      L.grammar('subjonctif', 'Grammar: the subjunctive'),
      L.checkpoint('medecin', 'Checkpoint: a full consultation'),
    ]},
    { id: 'fl6', title: 'The Professional You', lessons: [
      L.scenario('entretien', 'Your story, professionally'),
      L.scenario('reunion', 'Think aloud in a meeting'),
      L.reading('news-greve', 'Read: news in journalistic register'),
      L.dictation('Train your ear: register shifts'),
      L.checkpoint('entretien', 'Checkpoint: fully in character'),
    ]},
    { id: 'fl7', title: 'Time Travel', lessons: [
      L.grammar('passe-compose', 'Grammar: past, mastered'),
      L.grammar('futur-conditionnel', 'Grammar: future & would-be'),
      L.quickfire('Improv: yesterday, today, tomorrow'),
      L.dictation('Train your ear: tense shifts'),
      L.checkpoint('colloc', 'Checkpoint: tell your life in three tenses'),
    ]},
    { id: 'fl8', title: 'Bookshelf', lessons: [
      L.reading('book-corbeau', 'Read: La Fontaine, aloud'),
      L.reading('read-boulangerie', 'Read: deceptively simple prose'),
      L.reading('art-boulangerie', 'Read: a magazine feature'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('cours', 'Checkpoint: talk literature'),
    ]},
    { id: 'fl9', title: 'Ears of a Native', lessons: [
      L.listening('scene-gare', 'Listen: drama at the station'),
      L.listening('dia-resto', 'Listen: overlapping voices'),
      L.listening('pod-teletravail', 'Listen: opinions at speed'),
      L.dictation('Train your ear: no mercy'),
      L.checkpoint('marche', 'Checkpoint: catch every word'),
    ]},
    { id: 'fl10', title: 'Home & Habits', lessons: [
      L.scenario('logement', 'Negotiate like a tenant who knows'),
      L.listening('pod-habitudes', 'Listen: routines, described'),
      L.grammar('comparatif', 'Grammar: nuanced comparisons'),
      L.cards('Review your weak vocabulary'),
      L.checkpoint('logement', 'Checkpoint: the walkthrough'),
    ]},
    { id: 'fl11', title: 'Unscripted', lessons: [
      L.scenario('libre', 'Free talk: no script, no net'),
      L.quickfire('Improv: react to anything'),
      L.reading('read-lyon', 'Read: then retell it'),
      L.dictation('Train your ear: conversational blur'),
      L.checkpoint('reunion', 'Checkpoint: hold the room'),
    ]},
    { id: 'fl12', title: 'Near-Native', lessons: [
      L.grammar('articles', 'Grammar: the last article errors'),
      L.grammar('present', 'Grammar: zero-thought present'),
      L.scenario('libre', 'Free talk: your hardest topic'),
      L.quickfire('Improv: the 45-second essay'),
      L.checkpoint('entretien', 'Checkpoint: indistinguishable'),
    ]},
  ],
};

export const getRoadmap = (goal) => ROADMAPS[goal] || ROADMAPS.fluency;
