// Vocabulary library, wave two: ~360 more rich cards across 23 themed
// packs — same card shape as vocab.js (via the same helper), split into
// its own module to keep both files under the size limit.

const w = (id, fr, en, emoji, freq, example, exampleEn, extra = {}) =>
  ({ id, fr, en, emoji, freq, example, exampleEn, syn: [], ant: [], coll: [], note: '', ...extra });

export const EXTRA_VOCAB_PACKS = [
  {
    id: 'verbs1',
    title: 'Essential Verbs I',
    description: 'The twenty verbs you cannot speak without.',
    entries: [
      w('verbs1-etre', 'être', 'to be', '🫥', 1, "Je suis très content de te voir.", 'I am very happy to see you.', { coll: ['être en retard', 'être d\'accord'] }),
      w('verbs1-avoir', 'avoir', 'to have', '🤲', 1, "Tu as une minute ?", 'Do you have a minute?', { coll: ['avoir faim', 'avoir raison'] }),
      w('verbs1-faire', 'faire', 'to do / make', '🔨', 1, "Qu'est-ce que tu fais ce week-end ?", 'What are you doing this weekend?', { coll: ['faire attention', 'faire la cuisine'] }),
      w('verbs1-aller', 'aller', 'to go', '🚶', 1, "On va au marché ensemble ?", 'Shall we go to the market together?', { coll: ['aller bien', 'aller chercher'] }),
      w('verbs1-venir', 'venir', 'to come', '👋', 1, "Viens dîner à la maison !", 'Come have dinner at our place!', { coll: ['venir de + inf (just did)'] }),
      w('verbs1-dire', 'dire', 'to say', '💬', 1, "Qu'est-ce que tu veux dire ?", 'What do you mean?', { coll: ['vouloir dire', 'dire la vérité'] }),
      w('verbs1-voir', 'voir', 'to see', '👀', 1, "On se voit demain ?", 'See each other tomorrow?', { coll: ['voyons voir', 'se voir'] }),
      w('verbs1-savoir', 'savoir', 'to know (facts)', '🧠', 1, "Je ne sais pas encore.", "I don't know yet.", { note: 'Facts & skills; people/places take «connaître».' }),
      w('verbs1-pouvoir', 'pouvoir', 'to be able to', '💪', 1, "Tu peux m'aider deux secondes ?", 'Can you help me for two seconds?', { coll: ['on peut', 'je n\'en peux plus'] }),
      w('verbs1-vouloir', 'vouloir', 'to want', '🙏', 1, "Je voudrais un café, s'il vous plaît.", 'I would like a coffee, please.', { note: '«Je voudrais» is the polite form.' }),
      w('verbs1-devoir', 'devoir', 'to have to', '📋', 1, "Je dois partir avant six heures.", 'I have to leave before six.', { coll: ['tu aurais dû (you should have)'] }),
      w('verbs1-prendre', 'prendre', 'to take', '✊', 1, "On prend le métro ou le bus ?", 'Shall we take the metro or the bus?', { coll: ['prendre le temps', 'prendre un verre'] }),
      w('verbs1-mettre', 'mettre', 'to put', '📥', 1, "Mets ton manteau, il fait froid.", 'Put your coat on, it is cold.', { coll: ['mettre la table', 'se mettre à'] }),
      w('verbs1-donner', 'donner', 'to give', '🎁', 1, "Donne-moi ton avis.", 'Give me your opinion.', { coll: ['donner un coup de main'] }),
      w('verbs1-parler', 'parler', 'to speak', '🗣️', 1, "Vous parlez trop vite pour moi !", 'You speak too fast for me!', { coll: ['parler de', 'parler couramment'] }),
      w('verbs1-aimer', 'aimer', 'to like / love', '❤️', 1, "J'aime beaucoup ce quartier.", 'I really like this neighbourhood.', { note: '«aimer bien» = like; plain «aimer» a person = love.' }),
    ],
  },
  {
    id: 'verbs2',
    title: 'Essential Verbs II',
    description: 'The everyday actions of any day.',
    entries: [
      w('verbs2-manger', 'manger', 'to eat', '🍽️', 1, "On mange à quelle heure ?", 'What time are we eating?', { coll: ['manger un morceau'] }),
      w('verbs2-boire', 'boire', 'to drink', '🥤', 2, "Bois de l'eau, il fait chaud.", 'Drink some water, it is hot.', { coll: ['boire un coup'] }),
      w('verbs2-dormir', 'dormir', 'to sleep', '😴', 2, "J'ai très mal dormi cette nuit.", 'I slept very badly last night.', { coll: ['dormir profondément'] }),
      w('verbs2-travailler', 'travailler', 'to work', '💼', 1, "Elle travaille dans une banque.", 'She works in a bank.', { coll: ['travailler dur'] }),
      w('verbs2-acheter', 'acheter', 'to buy', '🛒', 2, "J'ai acheté du pain en rentrant.", 'I bought bread on the way home.', { ant: ['vendre'] }),
      w('verbs2-payer', 'payer', 'to pay', '💳', 2, "On peut payer par carte ?", 'Can we pay by card?', { coll: ['payer en espèces'] }),
      w('verbs2-chercher', 'chercher', 'to look for', '🔍', 2, "Je cherche la rue Molière.", "I'm looking for rue Molière.", { coll: ['aller chercher (to fetch)'] }),
      w('verbs2-trouver', 'trouver', 'to find', '🎯', 1, "Je trouve ça très joli.", 'I find that very pretty.', { note: '«Je trouve que…» = I think that…' }),
      w('verbs2-attendre', 'attendre', 'to wait', '⏳', 2, "Attends-moi devant la pharmacie.", 'Wait for me in front of the pharmacy.', { note: 'No preposition: attendre quelqu\'un.' }),
      w('verbs2-ouvrir', 'ouvrir', 'to open', '🚪', 2, "Tu peux ouvrir la fenêtre ?", 'Can you open the window?', { ant: ['fermer'] }),
      w('verbs2-fermer', 'fermer', 'to close', '🔒', 2, "Le magasin ferme à dix-neuf heures.", 'The shop closes at 7 p.m.', { ant: ['ouvrir'] }),
      w('verbs2-commencer', 'commencer', 'to begin', '🏁', 2, "Le film commence dans cinq minutes.", 'The film starts in five minutes.', { ant: ['finir'], coll: ['commencer à + inf'] }),
      w('verbs2-finir', 'finir', 'to finish', '🏆', 2, "J'ai fini mon travail plus tôt.", 'I finished my work early.', { coll: ['finir par + inf (end up)'] }),
      w('verbs2-aider', 'aider', 'to help', '🤝', 2, "Je peux vous aider à porter ça.", 'I can help you carry that.', { coll: ['aider quelqu\'un à + inf'] }),
      w('verbs2-appeler', 'appeler', 'to call', '📞', 2, "Appelle-moi quand tu arrives.", 'Call me when you arrive.', { coll: ['s\'appeler (to be named)'] }),
      w('verbs2-rester', 'rester', 'to stay', '🏠', 1, "Reste encore un peu !", 'Stay a little longer!', { note: 'Takes être in the passé composé.' }),
    ],
  },
  {
    id: 'verbs3',
    title: 'Mind & Heart Verbs',
    description: 'Thinking, feeling and remembering.',
    entries: [
      w('verbs3-penser', 'penser', 'to think', '💭', 1, "Qu'est-ce que tu en penses ?", 'What do you think about it?', { coll: ['penser à', 'penser que'] }),
      w('verbs3-croire', 'croire', 'to believe', '🙌', 1, "Je crois qu'il va pleuvoir.", 'I think it is going to rain.', { coll: ['croire en'] }),
      w('verbs3-comprendre', 'comprendre', 'to understand', '💡', 1, "Désolé, je n'ai pas compris.", "Sorry, I didn't understand.", { coll: ['se comprendre'] }),
      w('verbs3-connaitre', 'connaître', 'to know (people/places)', '🤗', 1, "Tu connais ce restaurant ?", 'Do you know this restaurant?', { note: 'People & places; facts take «savoir».' }),
      w('verbs3-apprendre', 'apprendre', 'to learn', '📚', 2, "J'apprends le français depuis un an.", 'I have been learning French for a year.', { coll: ['apprendre à + inf'] }),
      w('verbs3-oublier', 'oublier', 'to forget', '🌫️', 2, "J'ai oublié mon parapluie dans le bus.", 'I forgot my umbrella on the bus.', { ant: ['se souvenir'] }),
      w('verbs3-souvenir', 'se souvenir de', 'to remember', '📸', 2, "Tu te souviens de cette soirée ?", 'Do you remember that evening?', { syn: ['se rappeler'] }),
      w('verbs3-esperer', 'espérer', 'to hope', '🌟', 2, "J'espère que tout va bien.", 'I hope everything is fine.', { coll: ['espérer que + indicatif'] }),
      w('verbs3-preferer', 'préférer', 'to prefer', '⭐', 2, "Je préfère le thé au café.", 'I prefer tea to coffee.', { coll: ['préférer X à Y'] }),
      w('verbs3-detester', 'détester', 'to hate', '😤', 3, "Je déteste attendre.", 'I hate waiting.', { ant: ['adorer'] }),
      w('verbs3-adorer', 'adorer', 'to adore', '😍', 2, "Ma fille adore les chevaux.", 'My daughter adores horses.', { ant: ['détester'] }),
      w('verbs3-sentir', 'se sentir', 'to feel', '🫀', 2, "Je me sens beaucoup mieux.", 'I feel much better.', { note: 'Plain «sentir» = to smell.' }),
      w('verbs3-decider', 'décider', 'to decide', '⚖️', 2, "On a décidé de partir plus tôt.", 'We decided to leave earlier.', { coll: ['décider de + inf'] }),
      w('verbs3-essayer', 'essayer', 'to try', '🧗', 2, "Essaie encore une fois !", 'Try one more time!', { coll: ['essayer de + inf'] }),
      w('verbs3-reussir', 'réussir', 'to succeed', '🥇', 2, "Elle a réussi son examen.", 'She passed her exam.', { ant: ['échouer, rater'], coll: ['réussir à + inf'] }),
      w('verbs3-rater', 'rater', 'to miss / fail', '😬', 3, "J'ai raté mon train de deux minutes.", 'I missed my train by two minutes.', { syn: ['louper (fam.)'] }),
    ],
  },
  {
    id: 'adjectives1',
    title: 'Core Adjectives I',
    description: 'Describe anything: size, age, quality.',
    entries: [
      w('adj1-grand', 'grand(e)', 'big / tall', '📏', 1, "C'est une grande maison.", 'It is a big house.', { ant: ['petit'], note: 'Before the noun.' }),
      w('adj1-petit', 'petit(e)', 'small', '🐜', 1, "On prend un petit café ?", 'Shall we have a quick coffee?', { ant: ['grand'] }),
      w('adj1-bon', 'bon(ne)', 'good', '👍', 1, "Ce gâteau est vraiment bon.", 'This cake is really good.', { ant: ['mauvais'], coll: ['bon marché (cheap)'] }),
      w('adj1-mauvais', 'mauvais(e)', 'bad', '👎', 1, "C'est une mauvaise idée.", 'It is a bad idea.', { ant: ['bon'] }),
      w('adj1-beau', 'beau / belle', 'beautiful', '🌹', 1, "Quel beau temps aujourd'hui !", 'What lovely weather today!', { note: 'Bel before vowel: un bel homme.' }),
      w('adj1-jeune', 'jeune', 'young', '👶', 1, "Il est encore très jeune.", 'He is still very young.', { ant: ['vieux'] }),
      w('adj1-vieux', 'vieux / vieille', 'old', '👴', 1, "C'est un vieux quartier charmant.", 'It is a charming old district.', { note: 'Vieil before vowel: un vieil ami.' }),
      w('adj1-nouveau', 'nouveau / nouvelle', 'new', '✨', 1, "Tu as vu ma nouvelle veste ?", 'Have you seen my new jacket?', { note: 'Nouvel before vowel: un nouvel appartement.' }),
      w('adj1-long', 'long(ue)', 'long', '🪢', 2, "La journée a été longue.", 'It has been a long day.', { ant: ['court'] }),
      w('adj1-court', 'court(e)', 'short', '✂️', 2, "Une réponse courte suffit.", 'A short answer is enough.', { ant: ['long'] }),
      w('adj1-cher', 'cher / chère', 'expensive / dear', '💸', 1, "C'est trop cher pour moi.", 'It is too expensive for me.', { ant: ['bon marché'], note: 'Before a name = dear (Chère Marie).' }),
      w('adj1-facile', 'facile', 'easy', '🍰', 2, "L'exercice était facile.", 'The exercise was easy.', { ant: ['difficile'] }),
      w('adj1-difficile', 'difficile', 'difficult', '🧗', 1, "Le plus difficile, c'est de commencer.", 'The hardest part is starting.', { ant: ['facile'] }),
      w('adj1-important', 'important(e)', 'important', '❗', 1, "C'est un détail important.", 'It is an important detail.', { coll: ['peu important'] }),
      w('adj1-propre', 'propre', 'clean / own', '🧼', 2, "La chambre est propre.", 'The room is clean.', { note: 'Before noun = own: ma propre voiture.' }),
      w('adj1-sale', 'sale', 'dirty', '🧦', 3, "Mes chaussures sont toutes sales.", 'My shoes are all dirty.', { ant: ['propre'] }),
    ],
  },
  {
    id: 'adjectives2',
    title: 'Core Adjectives II',
    description: 'States, speeds and temperatures.',
    entries: [
      w('adj2-chaud', 'chaud(e)', 'hot', '🔥', 1, "Attention, l'assiette est chaude !", 'Careful, the plate is hot!', { ant: ['froid'] }),
      w('adj2-froid', 'froid(e)', 'cold', '🧊', 1, "Mon café est déjà froid.", 'My coffee is already cold.', { ant: ['chaud'] }),
      w('adj2-rapide', 'rapide', 'fast', '🏎️', 2, "Le TGV est très rapide.", 'The TGV is very fast.', { ant: ['lent'] }),
      w('adj2-lent', 'lent(e)', 'slow', '🐢', 3, "Le service est un peu lent ce soir.", 'The service is a bit slow tonight.', { ant: ['rapide'] }),
      w('adj2-fort', 'fort(e)', 'strong / loud', '💪', 1, "Parle moins fort, s'il te plaît.", 'Speak more quietly, please.', { ant: ['faible'] }),
      w('adj2-fatigue', 'fatigué(e)', 'tired', '🥱', 1, "Je suis trop fatigué pour sortir.", 'I am too tired to go out.', { syn: ['crevé (fam.)'] }),
      w('adj2-malade', 'malade', 'ill', '🤒', 2, "Elle est restée chez elle, malade.", 'She stayed home, ill.', { coll: ['tomber malade'] }),
      w('adj2-content', 'content(e)', 'glad', '😊', 1, "Je suis contente de te voir !", 'I am glad to see you!', { syn: ['heureux'] }),
      w('adj2-triste', 'triste', 'sad', '😢', 2, "C'est une histoire très triste.", 'It is a very sad story.', { ant: ['joyeux'] }),
      w('adj2-libre', 'libre', 'free / available', '🕊️', 1, "Tu es libre samedi soir ?", 'Are you free Saturday evening?', { ant: ['occupé'] }),
      w('adj2-occupe', 'occupé(e)', 'busy', '📵', 2, "Désolé, je suis très occupé cette semaine.", 'Sorry, I am very busy this week.', { ant: ['libre'] }),
      w('adj2-pret', 'prêt(e)', 'ready', '✅', 1, "Tout le monde est prêt ? On y va.", 'Everyone ready? Let us go.', { coll: ['prêt à + inf'] }),
      w('adj2-plein', 'plein(e)', 'full', '🈵', 2, "Le parking est plein.", 'The car park is full.', { ant: ['vide'], note: '«plein de» (fam.) = lots of.' }),
      w('adj2-vide', 'vide', 'empty', '🕳️', 3, "La bouteille est vide.", 'The bottle is empty.', { ant: ['plein'] }),
      w('adj2-vrai', 'vrai(e)', 'true / real', '✔️', 1, "C'est vrai, tu as raison.", 'It is true, you are right.', { ant: ['faux'] }),
      w('adj2-drole', 'drôle', 'funny', '😂', 2, "Ton frère est vraiment drôle.", 'Your brother is really funny.', { syn: ['marrant (fam.)'] }),
    ],
  },
  {
    id: 'kitchen',
    title: 'Kitchen & Cooking',
    description: 'Pots, pans and how to use them.',
    entries: [
      w('kitchen-recette', 'la recette', 'recipe', '📖', 3, "C'est la recette de ma grand-mère.", "It's my grandmother's recipe.", { coll: ['suivre une recette'] }),
      w('kitchen-four', 'le four', 'oven', '♨️', 3, "Mets le plat au four trente minutes.", 'Put the dish in the oven for thirty minutes.', { coll: ['au four'] }),
      w('kitchen-poele', 'la poêle', 'frying pan', '🍳', 3, "Fais chauffer la poêle d'abord.", 'Heat the pan first.', { note: 'LE poêle = a stove; LA poêle = the pan.' }),
      w('kitchen-casserole', 'la casserole', 'saucepan', '🥘', 3, "L'eau bout dans la casserole.", 'The water is boiling in the saucepan.' ),
      w('kitchen-couteau', 'le couteau', 'knife', '🔪', 2, "Attention, ce couteau coupe très bien.", 'Careful, this knife cuts really well.' ),
      w('kitchen-cuillere', 'la cuillère', 'spoon', '🥄', 2, "Ajoute deux cuillères de sucre.", 'Add two spoonfuls of sugar.', { coll: ['cuillère à soupe / à café'] }),
      w('kitchen-couper', 'couper', 'to cut', '✂️', 2, "Coupe les légumes en petits morceaux.", 'Cut the vegetables into small pieces.', { coll: ['couper en dés'] }),
      w('kitchen-melanger', 'mélanger', 'to mix', '🌀', 3, "Mélange bien la pâte.", 'Mix the batter well.' ),
      w('kitchen-cuire', 'cuire', 'to cook (heat)', '🍲', 2, "Laisse cuire à feu doux.", 'Let it cook on a low heat.', { coll: ['à feu doux/vif'] }),
      w('kitchen-gouter2', 'goûter', 'to taste', '👅', 2, "Goûte et dis-moi s'il manque du sel.", 'Taste it and tell me if it needs salt.' ),
      w('kitchen-verser', 'verser', 'to pour', '🫗', 3, "Verse le lait doucement.", 'Pour the milk in slowly.' ),
      w('kitchen-bouillir', 'bouillir', 'to boil', '💨', 3, "Fais bouillir de l'eau pour les pâtes.", 'Boil some water for the pasta.', { coll: ['porter à ébullition'] }),
      w('kitchen-frigo', 'le frigo', 'fridge', '🧊', 2, "Il n'y a plus rien dans le frigo.", 'There is nothing left in the fridge.', { note: 'Familiar for «réfrigérateur».' }),
      w('kitchen-evier', "l'évier", 'sink', '🚰', 3, "Laisse la vaisselle dans l'évier.", 'Leave the dishes in the sink.' ),
      w('kitchen-vaisselle', 'la vaisselle', 'the dishes', '🍽️', 2, "C'est ton tour de faire la vaisselle !", 'It is your turn to do the dishes!', { coll: ['faire la vaisselle'] }),
      w('kitchen-plat2', 'un plat maison', 'a home-made dish', '🏡', 3, "Rien ne vaut un plat maison.", 'Nothing beats a home-made dish.', { coll: ['fait maison'] }),
    ],
  },
  {
    id: 'shoppingx',
    title: 'Shopping & Sales',
    description: 'Sizes, prices, refunds and bargains.',
    entries: [
      w('shopx-taille', 'la taille', 'size', '📐', 2, "Vous l'avez en taille M ?", 'Do you have it in a medium?', { coll: ['quelle taille faites-vous ?'] }),
      w('shopx-essayer', 'essayer', 'to try on', '🪞', 2, "Je peux l'essayer ?", 'Can I try it on?', { coll: ['cabine d\'essayage'] }),
      w('shopx-soldes', 'les soldes', 'the sales', '🏷️', 3, "Tout est à moitié prix pendant les soldes.", 'Everything is half price during the sales.', { coll: ['en solde'] }),
      w('shopx-promotion', 'une promotion', 'a special offer', '💥', 3, "Ce fromage est en promotion.", 'This cheese is on offer.', { syn: ['une promo (fam.)'] }),
      w('shopx-rembourser', 'rembourser', 'to refund', '💶', 3, "Vous pouvez me rembourser ?", 'Can you refund me?', { coll: ['satisfait ou remboursé'] }),
      w('shopx-echanger', 'échanger', 'to exchange', '🔄', 3, "Je voudrais échanger ce pull.", 'I would like to exchange this jumper.', { coll: ['un ticket de caisse'] }),
      w('shopx-caisse', 'la caisse', 'the till / checkout', '🧾', 2, "La caisse est au fond du magasin.", 'The checkout is at the back of the shop.', { coll: ['passer en caisse'] }),
      w('shopx-especes', 'en espèces', 'in cash', '💵', 3, "Vous payez par carte ou en espèces ?", 'Are you paying by card or in cash?', { ant: ['par carte'] }),
      w('shopx-sac2', 'un sac (réutilisable)', 'a (reusable) bag', '🛍️', 2, "Vous voulez un sac ? — Non merci, j'ai le mien.", 'Would you like a bag? — No thanks, I have my own.' ),
      w('shopx-livraison', 'la livraison', 'delivery', '📦', 3, "La livraison est gratuite à partir de 50 euros.", 'Delivery is free over 50 euros.', { coll: ['livraison à domicile'] }),
      w('shopx-commander2', 'commander', 'to order', '🛒', 2, "Je l'ai commandé en ligne.", 'I ordered it online.', { coll: ['passer commande'] }),
      w('shopx-occasion', "d'occasion", 'second-hand', '♻️', 3, "J'achète mes livres d'occasion.", 'I buy my books second-hand.', { ant: ['neuf'] }),
      w('shopx-neuf', 'neuf / neuve', 'brand new', '🆕', 3, "La voiture est toute neuve.", 'The car is brand new.', { note: 'Neuf = never used; nouveau = new to you.' }),
      w('shopx-vitrine', 'la vitrine', 'shop window', '🪟', 4, "J'ai vu une robe magnifique en vitrine.", 'I saw a gorgeous dress in the window.', { coll: ['faire du lèche-vitrine (window-shop)'] }),
      w('shopx-marque', 'la marque', 'brand', '🏭', 3, "Peu importe la marque, je veux la qualité.", 'The brand does not matter, I want quality.' ),
      w('shopx-bonmarche', 'bon marché', 'cheap', '🪙', 3, "C'était étonnamment bon marché.", 'It was surprisingly cheap.', { ant: ['cher'], note: 'Invariable.' }),
    ],
  },
  {
    id: 'sports',
    title: 'Sports & Exercise',
    description: 'Play it, watch it, talk about it.',
    entries: [
      w('sports-foot', 'le foot(ball)', 'football', '⚽', 2, "On regarde le match de foot ce soir ?", 'Shall we watch the football match tonight?', { coll: ['jouer au foot'] }),
      w('sports-tennis', 'le tennis', 'tennis', '🎾', 3, "Elle joue au tennis tous les samedis.", 'She plays tennis every Saturday.' ),
      w('sports-natation', 'la natation', 'swimming', '🏊', 3, "La natation, c'est bon pour le dos.", 'Swimming is good for your back.', { coll: ['faire de la natation'] }),
      w('sports-course', 'la course (à pied)', 'running', '🏃', 3, "Je fais de la course à pied le matin.", 'I go running in the morning.', { syn: ['le footing, le running'] }),
      w('sports-velo2', 'faire du vélo', 'to cycle', '🚴', 2, "On a fait du vélo le long du canal.", 'We cycled along the canal.' ),
      w('sports-rando', 'la randonnée', 'hiking', '🥾', 3, "La randonnée dure quatre heures.", 'The hike takes four hours.', { coll: ['faire une rando (fam.)'] }),
      w('sports-equipe', "l'équipe", 'team', '👥', 2, "Notre équipe a gagné !", 'Our team won!', { coll: ['un esprit d\'équipe'] }),
      w('sports-match', 'le match', 'match', '🏟️', 2, "Le match est à vingt et une heures.", 'The match is at 9 p.m.', { coll: ['un match nul (a draw)'] }),
      w('sports-gagner2', 'gagner', 'to win', '🥇', 2, "Ils ont gagné deux à zéro.", 'They won two nil.', { ant: ['perdre'] }),
      w('sports-perdre2', 'perdre', 'to lose', '😞', 2, "On a perdu au dernier moment.", 'We lost at the last moment.', { ant: ['gagner'] }),
      w('sports-entrainer', "s'entraîner", 'to train', '🏋️', 3, "Il s'entraîne trois fois par semaine.", 'He trains three times a week.', { coll: ['un entraînement'] }),
      w('sports-but2', 'le but', 'goal', '🥅', 2, "Quel but magnifique !", 'What a magnificent goal!', { coll: ['marquer un but'] }),
      w('sports-piscine2', 'la piscine', 'swimming pool', '💧', 2, "La piscine ouvre à huit heures.", 'The pool opens at eight.' ),
      w('sports-salle', 'la salle de sport', 'the gym', '🏢', 3, "Je vais à la salle après le travail.", 'I go to the gym after work.', { syn: ['la salle (fam.)'] }),
      w('sports-etirer', "s'étirer", 'to stretch', '🧘', 4, "N'oublie pas de t'étirer après.", 'Do not forget to stretch afterwards.' ),
      w('sports-transpirer', 'transpirer', 'to sweat', '💦', 4, "J'ai transpiré comme jamais !", 'I sweated like never before!', { syn: ['suer'] }),
    ],
  },
  {
    id: 'music',
    title: 'Music & Arts',
    description: 'Instruments, concerts and galleries.',
    entries: [
      w('music-chanson', 'la chanson', 'song', '🎵', 2, "Cette chanson me reste dans la tête.", 'This song is stuck in my head.', { coll: ['la chanson française'] }),
      w('music-chanter', 'chanter', 'to sing', '🎤', 2, "Elle chante terriblement bien.", 'She sings amazingly well.', { coll: ['chanter juste/faux'] }),
      w('music-jouer', "jouer d'un instrument", 'to play an instrument', '🎹', 2, "Il joue du piano depuis dix ans.", 'He has played the piano for ten years.', { note: 'Jouer DE + instrument, jouer À + sport.' }),
      w('music-guitare', 'la guitare', 'guitar', '🎸', 3, "Apporte ta guitare ce soir !", 'Bring your guitar tonight!' ),
      w('music-batterie2', 'la batterie', 'drums', '🥁', 3, "Le voisin fait de la batterie… hélas.", 'The neighbour plays the drums… alas.', { note: 'Also means (car) battery.' }),
      w('music-concert', 'le concert', 'concert', '🎫', 2, "On a des places pour le concert.", 'We have tickets for the concert.', { coll: ['aller à un concert'] }),
      w('music-groupe', 'le groupe', 'band', '🎸', 3, "C'est mon groupe préféré.", 'It is my favourite band.' ),
      w('music-morceau2', 'un morceau', 'a piece / track', '🎼', 3, "Joue-nous un morceau !", 'Play us something!', { note: 'Also a piece (of food).' }),
      w('music-peinture2', 'la peinture', 'painting', '🎨', 3, "J'adore la peinture impressionniste.", 'I love impressionist painting.' ),
      w('music-tableau2', 'le tableau', 'painting (object)', '🖼️', 3, "Ce tableau vaut une fortune.", 'This painting is worth a fortune.' ),
      w('music-expo', "l'exposition", 'exhibition', '🏛️', 3, "L'expo se termine dimanche.", 'The exhibition ends on Sunday.', { syn: ['une expo (fam.)'] }),
      w('music-danse2', 'la danse', 'dance', '💃', 3, "Elle prend des cours de danse.", 'She takes dance classes.', { coll: ['danser'] }),
      w('music-scene2', 'la scène', 'stage', '🎭', 3, "Monter sur scène me terrifie.", 'Going on stage terrifies me.', { coll: ['sur scène'] }),
      w('music-billet2', 'le billet', 'ticket', '🎟️', 2, "Les billets partent très vite.", 'Tickets sell out very fast.', { syn: ['une place'] }),
      w('music-repetition', 'la répétition', 'rehearsal', '🔁', 4, "On a répétition mardi soir.", 'We have rehearsal on Tuesday evening.', { syn: ['une répète (fam.)'] }),
      w('music-ambiance', "l'ambiance", 'atmosphere', '🪩', 2, "Il y avait une super ambiance !", 'There was a great atmosphere!', { coll: ['mettre l\'ambiance'] }),
    ],
  },
  {
    id: 'tech',
    title: 'Tech & Internet',
    description: 'Screens, apps and connection trouble.',
    entries: [
      w('tech-ordi', "l'ordinateur", 'computer', '💻', 2, "Mon ordinateur est trop lent.", 'My computer is too slow.', { syn: ['un ordi (fam.)'] }),
      w('tech-portable2', 'le portable', 'mobile / laptop', '📱', 1, "J'ai laissé mon portable chez moi.", 'I left my phone at home.', { note: 'Context decides: phone or laptop.' }),
      w('tech-ecran2', "l'écran", 'screen', '🖥️', 2, "Tu passes trop de temps devant l'écran.", 'You spend too much time in front of the screen.', { coll: ['le temps d\'écran'] }),
      w('tech-appli', "l'application", 'app', '📲', 2, "Télécharge l'appli, c'est plus simple.", 'Download the app, it is easier.', { syn: ['une appli (fam.)'] }),
      w('tech-motdepasse', 'le mot de passe', 'password', '🔑', 2, "J'ai encore oublié mon mot de passe.", 'I forgot my password again.', { coll: ['réinitialiser le mot de passe'] }),
      w('tech-telecharger2', 'télécharger', 'to download', '⬇️', 2, "Le fichier met du temps à se télécharger.", 'The file is taking a while to download.' ),
      w('tech-connexion', 'la connexion', 'connection', '📶', 2, "La connexion est mauvaise ici.", 'The connection is bad here.', { coll: ['le wifi'] }),
      w('tech-panne2', 'en panne', 'broken / down', '🛑', 2, "L'imprimante est encore en panne.", 'The printer is down again.', { coll: ['tomber en panne'] }),
      w('tech-mail', 'le mail / courriel', 'email', '📧', 1, "Je t'envoie les infos par mail.", 'I will email you the details.', { coll: ['une boîte mail'] }),
      w('tech-fichier2', 'le fichier', 'file', '📁', 3, "Le fichier est trop lourd à envoyer.", 'The file is too big to send.', { coll: ['une pièce jointe (attachment)'] }),
      w('tech-imprimer2', 'imprimer', 'to print', '🖨️', 3, "Tu peux imprimer le billet ?", 'Can you print the ticket?' ),
      w('tech-sauvegarder', 'sauvegarder', 'to save / back up', '💾', 3, "Sauvegarde ton travail régulièrement !", 'Save your work regularly!', { coll: ['une sauvegarde'] }),
      w('tech-reseau2', 'les réseaux sociaux', 'social media', '🌐', 2, "Il passe sa vie sur les réseaux sociaux.", 'He spends his life on social media.', { syn: ['les réseaux (fam.)'] }),
      w('tech-brancher', 'brancher', 'to plug in', '🔌', 3, "Branche le chargeur, la batterie est vide.", 'Plug in the charger, the battery is dead.', { ant: ['débrancher'] }),
      w('tech-eteindre2', 'éteindre', 'to switch off', '⏻', 2, "Éteins la télé, on mange !", 'Turn off the TV, dinner time!', { ant: ['allumer'] }),
      w('tech-bug', 'un bug', 'a bug / glitch', '🐛', 3, "L'appli a un bug depuis la mise à jour.", 'The app has had a bug since the update.', { coll: ['ça bugge (fam.)'] }),
    ],
  },
  {
    id: 'schoolx',
    title: 'School & Study',
    description: 'Classes, exams and the vocabulary of learning.',
    entries: [
      w('schoolx-cours2', 'le cours', 'class / lesson', '📓', 1, "J'ai cours de huit heures à midi.", 'I have class from eight to noon.', { coll: ['sécher un cours (skip)'] }),
      w('schoolx-examen2', "l'examen", 'exam', '📝', 2, "Je révise pour l'examen de vendredi.", 'I am revising for Friday\'s exam.', { coll: ['passer/réussir/rater un examen'] }),
      w('schoolx-reviser', 'réviser', 'to revise', '📚', 2, "On révise ensemble à la bibliothèque ?", 'Shall we revise together at the library?', { coll: ['les révisions'] }),
      w('schoolx-note2', 'la note', 'grade / mark', '💯', 2, "Elle a eu une très bonne note.", 'She got a very good mark.', { coll: ['noter'] }),
      w('schoolx-devoirs', 'les devoirs', 'homework', '🏠', 2, "Fais tes devoirs avant de jouer.", 'Do your homework before playing.', { coll: ['faire ses devoirs'] }),
      w('schoolx-professeur2', 'le professeur', 'teacher', '👩‍🏫', 1, "Notre professeur explique très bien.", 'Our teacher explains things very well.', { syn: ['le/la prof (fam.)'] }),
      w('schoolx-eleve2', "l'élève", 'pupil', '🧑‍🎓', 2, "Il y a trente élèves dans la classe.", 'There are thirty pupils in the class.', { note: 'University → étudiant(e).' }),
      w('schoolx-erreur2', "l'erreur", 'mistake', '❌', 1, "On apprend de ses erreurs.", 'You learn from your mistakes.', { syn: ['une faute'] }),
      w('schoolx-question2', 'la question', 'question', '❓', 1, "J'ai une question bête…", 'I have a silly question…', { coll: ['poser une question'] }),
      w('schoolx-reponse2', 'la réponse', 'answer', '💡', 1, "La réponse était évidente !", 'The answer was obvious!', { coll: ['répondre à'] }),
      w('schoolx-exercice2', "l'exercice", 'exercise', '✏️', 2, "L'exercice trois est difficile.", 'Exercise three is hard.' ),
      w('schoolx-parcoeur', 'par cœur', 'by heart', '🫀', 2, "J'ai appris le poème par cœur.", 'I learned the poem by heart.', { coll: ['apprendre par cœur'] }),
      w('schoolx-progres2', 'les progrès', 'progress', '📈', 2, "Tu fais de vrais progrès en français !", 'You are making real progress in French!', { coll: ['faire des progrès'] }),
      w('schoolx-niveau2', 'le niveau', 'level', '🎚️', 2, "Quel est ton niveau en espagnol ?", 'What is your level in Spanish?', { coll: ['niveau débutant/avancé'] }),
      w('schoolx-traduire', 'traduire', 'to translate', '🔤', 2, "Tu peux me traduire ce mot ?", 'Can you translate this word for me?', { coll: ['une traduction'] }),
      w('schoolx-signifier', 'signifier / vouloir dire', 'to mean', '🤔', 1, "Qu'est-ce que ça veut dire ?", 'What does that mean?', { note: 'Spoken French prefers «vouloir dire».' }),
    ],
  },
  {
    id: 'jobsx',
    title: 'Jobs & Careers',
    description: 'Work life from CV to retirement.',
    entries: [
      w('jobsx-metier2', 'le métier', 'trade / profession', '🛠️', 2, "Quel métier tu voulais faire, enfant ?", 'What job did you want to do as a child?', { coll: ['exercer un métier'] }),
      w('jobsx-cv', 'le CV', 'CV / resume', '📄', 2, "Envoie ton CV et une lettre de motivation.", 'Send your CV and a cover letter.', { coll: ['la lettre de motivation'] }),
      w('jobsx-embaucher2', 'embaucher', 'to hire', '🤝', 3, "L'entreprise embauche trois personnes.", 'The company is hiring three people.', { ant: ['licencier'] }),
      w('jobsx-demissionner', 'démissionner', 'to resign', '🚪', 3, "Il a démissionné pour créer sa boîte.", 'He resigned to start his own company.', { coll: ['donner sa démission'] }),
      w('jobsx-boite', 'la boîte', 'company (informal)', '🏢', 3, "Ma boîte déménage à Lyon.", 'My company is moving to Lyon.', { note: 'Informal for «entreprise»; also nightclub.' }),
      w('jobsx-patron2', 'le patron / la patronne', 'boss', '👔', 2, "Le patron est plutôt sympa.", 'The boss is quite nice.', { syn: ['le/la chef'] }),
      w('jobsx-collegue2', 'le/la collègue', 'colleague', '👥', 2, "Je déjeune avec mes collègues.", 'I have lunch with my colleagues.' ),
      w('jobsx-reunion2', 'la réunion', 'meeting', '🗓️', 2, "Encore une réunion qui aurait pu être un mail…", 'Another meeting that could have been an email…', { coll: ['être en réunion'] }),
      w('jobsx-salaire2', 'le salaire', 'salary', '💰', 2, "Le salaire est correct pour ce poste.", 'The salary is decent for this position.', { coll: ['une augmentation (a raise)'] }),
      w('jobsx-conge', 'les congés', 'leave / holidays', '🏖️', 2, "Je prends mes congés en août.", 'I take my leave in August.', { coll: ['les congés payés', 'un jour de congé'] }),
      w('jobsx-greve2', 'la grève', 'strike', '✊', 3, "Les transports sont en grève demain.", 'Public transport is on strike tomorrow.', { coll: ['faire grève'] }),
      w('jobsx-stage', 'le stage', 'internship', '🎓', 3, "Elle fait un stage dans la presse.", 'She is doing an internship in the press.', { coll: ['un/une stagiaire'] }),
      w('jobsx-retraite2', 'la retraite', 'retirement', '🌅', 3, "Mon père vient de prendre sa retraite.", 'My father has just retired.', { coll: ['partir à la retraite'] }),
      w('jobsx-chomage2', 'le chômage', 'unemployment', '📉', 3, "Il est au chômage depuis mars.", 'He has been unemployed since March.', { coll: ['être au chômage'] }),
      w('jobsx-teletravail', 'le télétravail', 'remote work', '🏠', 2, "Je suis en télétravail le vendredi.", 'I work from home on Fridays.', { coll: ['télétravailler'] }),
      w('jobsx-carriere', 'la carrière', 'career', '🪜', 3, "Elle a fait toute sa carrière ici.", 'She spent her whole career here.', { coll: ['un plan de carrière'] }),
    ],
  },
  {
    id: 'emotions2',
    title: 'Emotions & Reactions',
    description: 'Say how you actually feel.',
    entries: [
      w('emo2-inquiet', 'inquiet / inquiète', 'worried', '😟', 2, "Je suis inquiète pour lui.", 'I am worried about him.', { coll: ['s\'inquiéter pour'] }),
      w('emo2-soulage', 'soulagé(e)', 'relieved', '😮‍💨', 3, "Ouf, je suis soulagé !", 'Phew, I am relieved!', { coll: ['quel soulagement !'] }),
      w('emo2-decu', 'déçu(e)', 'disappointed', '😞', 2, "Franchement, je suis un peu déçu.", 'Honestly, I am a bit disappointed.', { coll: ['une déception'] }),
      w('emo2-fier2', 'fier / fière', 'proud', '🦚', 2, "Je suis très fier de toi.", 'I am very proud of you.', { coll: ['fier de'] }),
      w('emo2-jaloux', 'jaloux / jalouse', 'jealous', '🟢', 3, "Il est jaloux de son frère.", 'He is jealous of his brother.', { coll: ['la jalousie'] }),
      w('emo2-genee', 'gêné(e)', 'embarrassed', '😳', 3, "J'étais tellement gêné !", 'I was so embarrassed!', { coll: ['c\'est gênant'] }),
      w('emo2-surpris', 'surpris(e)', 'surprised', '😲', 2, "On était tous surpris par la nouvelle.", 'We were all surprised by the news.', { coll: ['quelle surprise !'] }),
      w('emo2-enerve', 'énervé(e)', 'annoyed', '😠', 2, "Ne me parle pas, je suis énervé.", 'Do not talk to me, I am annoyed.', { coll: ['ça m\'énerve !'] }),
      w('emo2-detendu', 'détendu(e)', 'relaxed', '😌', 3, "Après le yoga, je suis super détendue.", 'After yoga I am super relaxed.', { coll: ['se détendre'] }),
      w('emo2-stresse', 'stressé(e)', 'stressed', '😰', 2, "Il est stressé par son examen.", 'He is stressed about his exam.', { coll: ['le stress'] }),
      w('emo2-ravi', 'ravi(e)', 'delighted', '🤩', 3, "Ravie de vous rencontrer !", 'Delighted to meet you!', { note: 'Common in polite introductions.' }),
      w('emo2-effraye', 'effrayé(e)', 'frightened', '😱', 3, "Le chat était effrayé par l'orage.", 'The cat was frightened by the storm.', { syn: ['avoir peur'] }),
      w('emo2-emu', 'ému(e)', 'moved / touched', '🥹', 3, "J'étais très ému par son discours.", 'I was very moved by his speech.', { coll: ['l\'émotion'] }),
      w('emo2-honte2', 'avoir honte', 'to be ashamed', '🫣', 3, "J'ai eu tellement honte !", 'I was so ashamed!', { coll: ['la honte ! (fam.)'] }),
      w('emo2-manquer', 'manquer', 'to miss (someone)', '💌', 2, "Tu me manques.", 'I miss you.', { note: 'Reversed: literally "you are missing to me".' }),
      w('emo2-hate', "avoir hâte de", 'to look forward to', '🤞', 2, "J'ai hâte de te revoir !", 'I cannot wait to see you again!', { coll: ['j\'ai trop hâte (fam.)'] }),
    ],
  },
  {
    id: 'personality',
    title: 'Personality',
    description: 'Describe who someone really is.',
    entries: [
      w('pers-gentil2', 'gentil(le)', 'kind', '💗', 1, "Merci, c'est très gentil !", 'Thank you, that is very kind!', { ant: ['méchant'] }),
      w('pers-mechant', 'méchant(e)', 'mean', '🐍', 2, "Ne sois pas méchant avec ta sœur.", 'Do not be mean to your sister.', { ant: ['gentil'] }),
      w('pers-timide2', 'timide', 'shy', '🙈', 2, "Il est timide au début, puis très drôle.", 'He is shy at first, then very funny.', { coll: ['la timidité'] }),
      w('pers-bavard', 'bavard(e)', 'chatty', '🦜', 3, "Ma voisine est très bavarde.", 'My neighbour is very chatty.', { coll: ['bavarder'] }),
      w('pers-paresseux', 'paresseux / paresseuse', 'lazy', '🦥', 3, "Mon chat est adorablement paresseux.", 'My cat is adorably lazy.', { syn: ['flemmard (fam.)'] }),
      w('pers-travailleur', 'travailleur / travailleuse', 'hard-working', '🐝', 3, "C'est quelqu'un de très travailleur.", 'He/she is a very hard-working person.' ),
      w('pers-honnete', 'honnête', 'honest', '🤲', 2, "Sois honnête avec moi.", 'Be honest with me.', { ant: ['malhonnête'] }),
      w('pers-poli2', 'poli(e)', 'polite', '🎩', 2, "Les enfants sont très polis.", 'The children are very polite.', { ant: ['impoli'] }),
      w('pers-tetu', 'têtu(e)', 'stubborn', '🐐', 3, "Têtu comme une mule !", 'Stubborn as a mule!', { coll: ['têtu comme une mule'] }),
      w('pers-genereux2', 'généreux / généreuse', 'generous', '🎁', 3, "Elle est généreuse avec son temps.", 'She is generous with her time.', { ant: ['radin (stingy, fam.)'] }),
      w('pers-marrant', 'marrant(e)', 'funny (informal)', '🤡', 3, "Il est marrant, ton copain !", 'Your friend is funny!', { syn: ['drôle, rigolo'] }),
      w('pers-serieux2', 'sérieux / sérieuse', 'serious / reliable', '🧐', 2, "C'est une entreprise sérieuse.", 'It is a reliable company.', { note: 'Also = trustworthy, not only stern.' }),
      w('pers-curieux', 'curieux / curieuse', 'curious', '🔎', 2, "Les enfants sont naturellement curieux.", 'Children are naturally curious.', { note: 'Can also mean nosy.' }),
      w('pers-sage', 'sage', 'well-behaved / wise', '🦉', 3, "Sois sage chez mamie !", 'Behave at granny\'s!', { note: 'For children = good; for adults = wise.' }),
      w('pers-fou2', 'fou / folle', 'crazy', '🤪', 2, "C'est fou, cette histoire !", 'That story is crazy!', { coll: ['un truc de fou (fam.)'] }),
      w('pers-sympa', 'sympa', 'nice (informal)', '😎', 1, "Tes amis sont super sympas.", 'Your friends are really nice.', { note: 'Short for sympathique — everywhere in spoken French.' }),
    ],
  },
  {
    id: 'lovex',
    title: 'Love & Relationships',
    description: 'From first dates to long stories.',
    entries: [
      w('lovex-rencontrer2', 'rencontrer', 'to meet', '🤝', 1, "Ils se sont rencontrés à la fac.", 'They met at university.', { coll: ['une rencontre'] }),
      w('lovex-rdv', 'le rendez-vous', 'date / appointment', '📅', 2, "On a rendez-vous à vingt heures.", 'We have a date at 8 p.m.', { note: 'Romantic or medical — context decides!' }),
      w('lovex-amoureux', 'amoureux / amoureuse', 'in love', '😍', 2, "Elle est amoureuse de son meilleur ami.", 'She is in love with her best friend.', { coll: ['tomber amoureux'] }),
      w('lovex-copain', 'le copain / la copine', 'boyfriend / girlfriend', '💑', 2, "Je te présente ma copine.", 'Meet my girlfriend.', { note: 'Also just "friend" — context and article matter.' }),
      w('lovex-embrasser2', 'embrasser', 'to kiss', '💋', 2, "Ils se sont embrassés sous la pluie.", 'They kissed in the rain.', { note: 'NOT to hug — that is «serrer dans ses bras».' }),
      w('lovex-calin', 'un câlin', 'a hug / cuddle', '🤗', 3, "Viens faire un câlin !", 'Come here for a hug!', { coll: ['faire un câlin'] }),
      w('lovex-marier2', 'se marier', 'to get married', '💍', 2, "Ils se marient en juin.", 'They are getting married in June.', { coll: ['le mariage'] }),
      w('lovex-couple', 'le couple', 'couple', '👫', 2, "Ils forment un beau couple.", 'They make a lovely couple.', { coll: ['la vie de couple'] }),
      w('lovex-separer', 'se séparer', 'to break up', '💔', 3, "Ils se sont séparés après dix ans.", 'They split up after ten years.', { syn: ['rompre'] }),
      w('lovex-celibataire', 'célibataire', 'single', '🕺', 2, "Il est célibataire depuis un an.", 'He has been single for a year.' ),
      w('lovex-confiance2', 'la confiance', 'trust', '🤲', 2, "La confiance, ça se mérite.", 'Trust must be earned.', { coll: ['faire confiance à'] }),
      w('lovex-jalousie', 'la jalousie', 'jealousy', '🌵', 3, "La jalousie abîme tout.", 'Jealousy ruins everything.' ),
      w('lovex-draguer', 'draguer', 'to flirt / chat up', '😏', 3, "Il drague tout le monde, c'est gênant.", 'He flirts with everyone, it is awkward.', { note: 'Informal.' }),
      w('lovex-coupfoudre', 'le coup de foudre', 'love at first sight', '⚡', 3, "Ça a été le coup de foudre immédiat.", 'It was love at first sight, instantly.', { note: 'Literally "lightning strike".' }),
      w('lovex-cherie', 'chéri(e)', 'darling', '🍯', 2, "Chéri, tu as pris les clés ?", 'Darling, did you take the keys?', { syn: ['mon amour, mon cœur'] }),
      w('lovex-fiancer', 'se fiancer', 'to get engaged', '💎', 3, "Ils se sont fiancés à Rome.", 'They got engaged in Rome.', { coll: ['les fiançailles'] }),
    ],
  },
  {
    id: 'mediax',
    title: 'Media & News',
    description: 'Talk about what everyone is talking about.',
    entries: [
      w('mediax-actualites', 'les actualités', 'the news', '📰', 2, "Tu as suivi les actualités ce matin ?", 'Did you follow the news this morning?', { syn: ['les actus, les infos (fam.)'] }),
      w('mediax-journal2', 'le journal', 'newspaper', '🗞️', 2, "Mon père lit le journal au petit-déjeuner.", 'My father reads the paper at breakfast.', { note: 'Also = TV news («le journal de 20h») and diary.' }),
      w('mediax-titre', 'le titre / le gros titre', 'headline', '🔠', 3, "C'est en gros titre partout.", 'It is headline news everywhere.', { coll: ['faire les gros titres'] }),
      w('mediax-emission2', "l'émission", 'programme / show', '📺', 2, "C'est mon émission préférée.", 'It is my favourite show.', { coll: ['une émission de radio/télé'] }),
      w('mediax-serie', 'la série', 'series', '🎬', 2, "On a fini la série en deux soirs.", 'We finished the series in two evenings.', { coll: ['regarder une série'] }),
      w('mediax-episode', "l'épisode", 'episode', '▶️', 3, "Encore un épisode et j'arrête, promis.", 'One more episode and I will stop, promise.' ),
      w('mediax-chaine2', 'la chaîne', 'channel', '📡', 3, "Change de chaîne, c'est nul.", 'Change the channel, this is rubbish.', { coll: ['zapper'] }),
      w('mediax-pub', 'la pub(licité)', 'advert', '📢', 2, "Il y a trop de pub à la télé.", 'There are too many ads on TV.', { syn: ['la pub (fam.)'] }),
      w('mediax-journaliste2', 'le/la journaliste', 'journalist', '🎙️', 3, "La journaliste pose de bonnes questions.", 'The journalist asks good questions.' ),
      w('mediax-interview', "l'interview", 'interview (media)', '🗨️', 3, "Son interview a fait le buzz.", 'Her interview went viral.', { note: 'Job interview = «entretien».' }),
      w('mediax-sondage', 'le sondage', 'poll / survey', '📊', 3, "Selon un sondage, 60% sont d'accord.", 'According to a poll, 60% agree.' ),
      w('mediax-rumeur', 'la rumeur', 'rumour', '🤫', 3, "Ce n'est qu'une rumeur, rien d'officiel.", 'It is only a rumour, nothing official.', { coll: ['une rumeur circule'] }),
      w('mediax-direct', 'en direct', 'live', '🔴', 3, "Le match est diffusé en direct.", 'The match is broadcast live.', { ant: ['en différé'] }),
      w('mediax-abonnement2', "l'abonnement", 'subscription', '💳', 2, "J'ai résilié mon abonnement.", 'I cancelled my subscription.', { coll: ['s\'abonner / se désabonner'] }),
      w('mediax-fakenews', 'une fausse information', 'fake news', '🚫', 3, "Vérifie la source, ça sent la fausse info.", 'Check the source, that smells like fake news.', { syn: ['une infox, une fake news'] }),
      w('mediax-media', 'les médias', 'the media', '🌍', 3, "Les médias en parlent beaucoup.", 'The media are talking about it a lot.' ),
    ],
  },
  {
    id: 'environment',
    title: 'Environment',
    description: 'The planet, in conversation.',
    entries: [
      w('env-environnement', "l'environnement", 'the environment', '🌍', 2, "Il faut protéger l'environnement.", 'We must protect the environment.', { coll: ['respectueux de l\'environnement'] }),
      w('env-climat', 'le climat', 'climate', '🌡️', 2, "Le climat change vite.", 'The climate is changing fast.', { coll: ['le changement climatique'] }),
      w('env-rechauffement', 'le réchauffement climatique', 'global warming', '🔥', 3, "Le réchauffement climatique s'accélère.", 'Global warming is speeding up.' ),
      w('env-pollution2', 'la pollution', 'pollution', '🏭', 2, "La pollution de l'air est un vrai problème.", 'Air pollution is a real problem.', { coll: ['polluer'] }),
      w('env-dechets', 'les déchets', 'waste / rubbish', '🗑️', 2, "Trie tes déchets !", 'Sort your rubbish!', { coll: ['le tri des déchets'] }),
      w('env-recycler', 'recycler', 'to recycle', '♻️', 2, "Le verre se recycle à l'infini.", 'Glass can be recycled endlessly.', { coll: ['le recyclage'] }),
      w('env-plastique2', 'le plastique', 'plastic', '🥤', 2, "Évitons le plastique à usage unique.", 'Let us avoid single-use plastic.', { coll: ['sans plastique'] }),
      w('env-energie2', "l'énergie", 'energy', '⚡', 2, "Les énergies renouvelables progressent.", 'Renewable energy is making progress.', { coll: ['les énergies renouvelables'] }),
      w('env-panneau2', 'le panneau solaire', 'solar panel', '☀️', 3, "Ils ont mis des panneaux solaires sur le toit.", 'They put solar panels on the roof.' ),
      w('env-eolienne', "l'éolienne", 'wind turbine', '🌬️', 3, "On voit des éoliennes depuis l'autoroute.", 'You can see wind turbines from the motorway.' ),
      w('env-secheresse2', 'la sécheresse', 'drought', '🏜️', 3, "La sécheresse menace les récoltes.", 'The drought threatens the harvests.' ),
      w('env-inondation2', "l'inondation", 'flood', '🌊', 3, "Des inondations ont coupé la route.", 'Floods cut off the road.' ),
      w('env-espece2', "une espèce menacée", 'an endangered species', '🐼', 3, "Le panda reste une espèce menacée.", 'The panda is still an endangered species.' ),
      w('env-nature2', 'la nature', 'nature', '🌳', 1, "On a besoin de nature pour respirer.", 'We need nature to breathe.', { coll: ['en pleine nature'] }),
      w('env-gaspiller', 'gaspiller', 'to waste', '🚿', 3, "Ne gaspille pas l'eau.", 'Do not waste water.', { coll: ['le gaspillage'] }),
      w('env-durable', 'durable', 'sustainable', '🌱', 3, "Il faut une solution durable.", 'We need a sustainable solution.', { coll: ['le développement durable'] }),
    ],
  },
  {
    id: 'societyx',
    title: 'Society & Opinion',
    description: 'Debate like a French dinner table.',
    entries: [
      w('socx-avis', "l'avis", 'opinion', '🗣️', 1, "À mon avis, c'est une erreur.", 'In my opinion, it is a mistake.', { coll: ['à mon avis', 'changer d\'avis'] }),
      w('socx-daccord', "être d'accord", 'to agree', '✅', 1, "Je suis complètement d'accord avec toi.", 'I completely agree with you.', { ant: ['ne pas être d\'accord'] }),
      w('socx-debat', 'le débat', 'debate', '⚖️', 3, "C'est un débat sans fin.", 'It is an endless debate.', { coll: ['débattre'] }),
      w('socx-droit2', 'le droit', 'right / law', '📜', 2, "C'est ton droit le plus strict.", 'It is absolutely your right.', { coll: ['avoir le droit de'] }),
      w('socx-loi2', 'la loi', 'law', '🏛️', 2, "La loi a changé l'année dernière.", 'The law changed last year.', { coll: ['voter une loi'] }),
      w('socx-egalite2', "l'égalité", 'equality', '🟰', 2, "Liberté, égalité, fraternité.", 'Liberty, equality, fraternity.', { note: 'The national motto.' }),
      w('socx-liberte2', 'la liberté', 'freedom', '🕊️', 2, "La liberté d'expression est essentielle.", 'Freedom of speech is essential.' ),
      w('socx-elections', 'les élections', 'elections', '🗳️', 3, "Les élections ont lieu en avril.", 'The elections take place in April.', { coll: ['voter'] }),
      w('socx-maire2', 'le maire / la maire', 'mayor', '🎗️', 3, "La maire a inauguré la bibliothèque.", 'The mayor opened the library.', { coll: ['la mairie'] }),
      w('socx-impots', 'les impôts', 'taxes', '🧾', 2, "On paie ses impôts en ligne maintenant.", 'We pay our taxes online now.', { coll: ['déclarer ses impôts'] }),
      w('socx-injuste2', 'injuste', 'unfair', '🙅', 2, "C'est profondément injuste.", 'It is deeply unfair.', { ant: ['juste'] }),
      w('socx-manifester', 'manifester', 'to protest', '📣', 3, "Ils manifestent contre la réforme.", 'They are protesting against the reform.', { coll: ['une manifestation, une manif (fam.)'] }),
      w('socx-benevole', 'bénévole', 'volunteer', '🤲', 3, "Elle est bénévole aux Restos du Cœur.", 'She volunteers at the Restos du Cœur.', { coll: ['le bénévolat'] }),
      w('socx-quartier2', 'le quartier', 'neighbourhood', '🏘️', 2, "C'est un quartier très vivant.", 'It is a very lively neighbourhood.', { coll: ['la vie de quartier'] }),
      w('socx-securite2', 'la sécurité', 'safety / security', '🦺', 2, "La sécurité avant tout.", 'Safety first.', { coll: ['en sécurité'] }),
      w('socx-convaincre2', 'convaincre', 'to convince', '🎯', 3, "Tu ne me convaincras pas !", 'You will not convince me!', { coll: ['convaincant'] }),
    ],
  },
  {
    id: 'celebrations',
    title: 'Celebrations',
    description: 'Parties, holidays and toasts.',
    entries: [
      w('celeb-fete2', 'la fête', 'party / celebration', '🎉', 1, "On fait une fête pour son départ.", 'We are throwing a party for his leaving.', { coll: ['faire la fête'] }),
      w('celeb-anniversaire2', "l'anniversaire", 'birthday', '🎂', 1, "Joyeux anniversaire !", 'Happy birthday!', { coll: ['fêter son anniversaire'] }),
      w('celeb-cadeau', 'le cadeau', 'gift', '🎁', 1, "J'ai trouvé le cadeau parfait.", 'I found the perfect gift.', { coll: ['offrir un cadeau', 'un paquet cadeau'] }),
      w('celeb-inviter2', 'inviter', 'to invite', '💌', 1, "Ils nous ont invités à dîner.", 'They invited us to dinner.', { coll: ['une invitation', 'les invités'] }),
      w('celeb-feter', 'fêter', 'to celebrate', '🥳', 2, "On fête ça ce soir !", 'We are celebrating tonight!', { syn: ['célébrer'] }),
      w('celeb-sante', 'Santé !', 'Cheers!', '🥂', 1, "Allez, santé tout le monde !", 'Come on, cheers everyone!', { syn: ['Tchin-tchin !', 'À la tienne !'] }),
      w('celeb-noel2', 'Noël', 'Christmas', '🎄', 2, "On passe Noël en famille.", 'We spend Christmas with family.', { coll: ['le réveillon de Noël'] }),
      w('celeb-nouvelan', 'le Nouvel An', 'New Year', '🎆', 2, "Bonne année et bonne santé !", 'Happy New Year and good health!', { coll: ['le réveillon du Nouvel An'] }),
      w('celeb-paques', 'Pâques', 'Easter', '🥚', 3, "À Pâques, on cache des œufs au jardin.", 'At Easter we hide eggs in the garden.', { coll: ['les œufs de Pâques'] }),
      w('celeb-quatorze', 'le 14 juillet', 'Bastille Day', '🇫🇷', 3, "On regarde le feu d'artifice du 14 juillet.", 'We watch the Bastille Day fireworks.', { coll: ['le feu d\'artifice'] }),
      w('celeb-mariage2', 'le mariage', 'wedding', '👰', 2, "Le mariage a lieu en Provence.", 'The wedding takes place in Provence.', { coll: ['assister à un mariage'] }),
      w('celeb-felicitations', 'Félicitations !', 'Congratulations!', '👏', 2, "Félicitations pour ton nouveau travail !", 'Congratulations on your new job!', { coll: ['féliciter'] }),
      w('celeb-bienvenue', 'Bienvenue !', 'Welcome!', '🚪', 1, "Bienvenue chez nous !", 'Welcome to our home!', { coll: ['souhaiter la bienvenue'] }),
      w('celeb-galette', 'la galette des rois', 'kings\' cake', '👑', 4, "Qui aura la fève dans la galette ?", 'Who will get the charm in the cake?', { note: 'Eaten for Epiphany in January.' }),
      w('celeb-crémaillère', 'pendre la crémaillère', 'housewarming party', '🏡', 4, "On pend la crémaillère samedi !", 'Housewarming party on Saturday!', { note: 'Literally "hang the chimney hook".' }),
      w('celeb-trinquer', 'trinquer', 'to clink glasses', '🍻', 3, "On trinque à ta réussite !", 'A toast to your success!', { coll: ['trinquer à'] }),
    ],
  },
  {
    id: 'connectors2',
    title: 'Opinion & Flow Phrases',
    description: 'Sound structured, sound French.',
    entries: [
      w('conn2-dabord', "d'abord", 'first of all', '1️⃣', 1, "D'abord, on va faire les courses.", 'First, we will do the shopping.', { syn: ['premièrement'] }),
      w('conn2-ensuite2', 'ensuite', 'then / next', '2️⃣', 1, "Ensuite, on passera chez Paul.", 'Then we will stop by Paul\'s.', { syn: ['puis'] }),
      w('conn2-enfin2', 'enfin', 'finally / at last', '🏁', 1, "Enfin, n'oublie pas d'appeler ta mère.", 'Finally, do not forget to call your mother.', { note: 'Also relief: «Enfin !» = At last!' }),
      w('conn2-parcontre', 'par contre', 'on the other hand', '↔️', 1, "C'est bon, par contre c'est cher.", 'It is good; on the other hand it is expensive.', { syn: ['en revanche (formal)'] }),
      w('conn2-dailleurs', "d'ailleurs", 'by the way / besides', '💬', 2, "D'ailleurs, tu as des nouvelles de Léo ?", 'By the way, any news from Léo?' ),
      w('conn2-ducoup', 'du coup', 'so / as a result', '🎲', 1, "Il pleuvait, du coup on est restés.", 'It was raining, so we stayed in.', { note: 'THE spoken-French filler of the decade.' }),
      w('conn2-cadit', 'cela dit', 'that said', '🤔', 3, "Cela dit, il n'a pas tout à fait tort.", 'That said, he is not entirely wrong.', { syn: ['ceci dit'] }),
      w('conn2-aufait', 'au fait', 'by the way', '📌', 2, "Au fait, tu viens samedi ?", 'By the way, are you coming on Saturday?', { note: 'Different from «en fait» (actually)!' }),
      w('conn2-enfait', 'en fait', 'actually', '🔍', 1, "En fait, je préfère rester ici.", 'Actually, I would rather stay here.', { note: 'Not «au fait» (by the way).' }),
      w('conn2-bref', 'bref', 'anyway / in short', '✂️', 2, "Bref, on a raté le train.", 'Long story short, we missed the train.', { coll: ['bref, passons'] }),
      w('conn2-quandmeme', 'quand même', 'still / all the same', '🎭', 1, "C'est quand même incroyable !", 'It is still incredible!', { note: 'Multi-purpose emphasis word.' }),
      w('conn2-selon', 'selon moi', 'according to me', '⚖️', 2, "Selon moi, c'est la meilleure option.", 'In my view, it is the best option.', { syn: ['à mon avis', 'pour ma part'] }),
      w('conn2-parexemple', 'par exemple', 'for example', '💡', 1, "Prends un fruit, par exemple une pomme.", 'Have some fruit, for example an apple.' ),
      w('conn2-cestadire', "c'est-à-dire", 'that is to say', '🔗', 2, "Il est polyglotte, c'est-à-dire qu'il parle cinq langues.", 'He is a polyglot — that is, he speaks five languages.' ),
      w('conn2-entoutcas', 'en tout cas', 'in any case', '📦', 2, "En tout cas, merci pour tout.", 'In any case, thanks for everything.', { syn: ['de toute façon'] }),
      w('conn2-tantpis', 'tant pis / tant mieux', 'too bad / so much the better', '🎲', 2, "Il ne vient pas ? Tant pis pour lui !", 'He is not coming? Too bad for him!', { note: 'A matched pair worth learning together.' }),
    ],
  },
  {
    id: 'politeness',
    title: 'Politeness Formulas',
    description: 'The oil in every French conversation.',
    entries: [
      w('pol-svp', "s'il vous plaît", 'please (formal)', '🙏', 1, "L'addition, s'il vous plaît.", 'The bill, please.', { note: '«s\'il te plaît» with friends.' }),
      w('pol-merci2', 'merci beaucoup', 'thank you very much', '💐', 1, "Merci beaucoup pour votre aide !", 'Thank you very much for your help!', { coll: ['merci mille fois'] }),
      w('pol-derien', 'de rien', "you're welcome", '🤗', 1, "Merci ! — De rien, c'est normal.", 'Thanks! — You are welcome, of course.', { syn: ['je vous en prie (formal)', 'avec plaisir'] }),
      w('pol-jevousenprie', 'je vous en prie', "you're welcome (formal)", '🎩', 2, "Je vous en prie, asseyez-vous.", 'Please, do sit down.', { note: 'Also = please go ahead.' }),
      w('pol-excusez', 'excusez-moi', 'excuse me', '🙇', 1, "Excusez-moi, vous avez l'heure ?", 'Excuse me, do you have the time?', { syn: ['pardon'] }),
      w('pol-desole', 'désolé(e)', 'sorry', '😔', 1, "Désolée pour le retard !", 'Sorry for being late!', { coll: ['vraiment désolé'] }),
      w('pol-bonnejournee', 'bonne journée', 'have a good day', '🌞', 1, "Merci, bonne journée à vous !", 'Thanks, have a good day!', { coll: ['bonne soirée / bon week-end'] }),
      w('pol-bonappetit', 'bon appétit', 'enjoy your meal', '🍴', 1, "Allez, bon appétit tout le monde !", 'Right, enjoy your meal everyone!' ),
      w('pol-volontiers', 'volontiers', 'gladly / yes please', '😊', 3, "Un café ? — Volontiers !", 'A coffee? — Yes, gladly!', { syn: ['avec plaisir'] }),
      w('pol-cava', 'ça va ?', 'how are you? (informal)', '👋', 1, "Salut, ça va ? — Ça va, et toi ?", 'Hi, how are you? — Fine, and you?', { note: 'Question and answer in one phrase.' }),
      w('pol-enchante2', 'enchanté(e)', 'nice to meet you', '🤝', 1, "Enchantée, moi c'est Claire.", 'Nice to meet you, I am Claire.' ),
      w('pol-pardon2', 'pardon', 'sorry / pardon', '🙊', 1, "Pardon, je ne vous avais pas vu !", 'Sorry, I did not see you!', { note: 'Also "excuse me" to pass through a crowd.' }),
      w('pol-pasdesouci', 'pas de souci', 'no worries', '👌', 2, "Je peux payer demain ? — Pas de souci.", 'Can I pay tomorrow? — No worries.', { syn: ['pas de problème'] }),
      w('pol-bienvenu2', 'je t\'en prie', "you're welcome (informal)", '💛', 2, "Merci pour tout ! — Je t'en prie.", 'Thanks for everything! — You are welcome.' ),
      w('pol-bonnechance', 'bonne chance', 'good luck', '🍀', 1, "Bonne chance pour ton entretien !", 'Good luck with your interview!', { coll: ['bon courage (hang in there)'] }),
      w('pol-boncourage', 'bon courage', 'good luck / hang in there', '💪', 1, "Encore deux heures de travail ? Bon courage !", 'Two more hours of work? Hang in there!', { note: 'For effort ahead — more common than «bonne chance».' }),
    ],
  },
  {
    id: 'countryside',
    title: 'Countryside & Farm',
    description: 'La France profonde, word by word.',
    entries: [
      w('country-campagne2', 'la campagne', 'countryside', '🌾', 2, "On passe le week-end à la campagne.", 'We are spending the weekend in the countryside.', { coll: ['à la campagne'] }),
      w('country-village2', 'le village', 'village', '⛪', 2, "Le village a trois cents habitants.", 'The village has three hundred inhabitants.' ),
      w('country-ferme2', 'la ferme', 'farm', '🚜', 2, "On achète nos œufs à la ferme.", 'We buy our eggs at the farm.', { coll: ['les produits de la ferme'] }),
      w('country-champ2', 'le champ', 'field', '🌻', 2, "Les champs de tournesols sont en fleur.", 'The sunflower fields are in bloom.' ),
      w('country-vigne', 'la vigne', 'vine / vineyard', '🍇', 3, "La région est couverte de vignes.", 'The region is covered in vines.', { coll: ['les vendanges (grape harvest)'] }),
      w('country-recolte2', 'la récolte', 'harvest', '🧺', 3, "La récolte a été bonne cette année.", 'The harvest was good this year.', { coll: ['récolter'] }),
      w('country-tracteur2', 'le tracteur', 'tractor', '🚜', 3, "Un tracteur bloque la petite route.", 'A tractor is blocking the small road.' ),
      w('country-poulailler', 'le poulailler', 'henhouse', '🐔', 4, "Le renard rôde près du poulailler.", 'The fox is prowling near the henhouse.' ),
      w('country-etable', "l'étable", 'cowshed', '🐄', 4, "Les vaches rentrent à l'étable le soir.", 'The cows come back to the shed at night.', { note: 'Horses → l\'écurie.' }),
      w('country-pre', 'le pré', 'meadow', '🐑', 3, "Les moutons sont dans le pré.", 'The sheep are in the meadow.', { syn: ['la prairie'] }),
      w('country-chemin', 'le chemin', 'path / way', '🥾', 2, "On a pris un petit chemin de terre.", 'We took a little dirt path.', { coll: ['en chemin (on the way)'] }),
      w('country-riviere2', 'la rivière', 'river', '🏞️', 2, "On pique-nique au bord de la rivière.", 'We picnic by the river.', { note: 'Large river to the sea = un fleuve.' }),
      w('country-colline2', 'la colline', 'hill', '⛰️', 3, "La maison est sur la colline.", 'The house is on the hill.' ),
      w('country-clocher', 'le clocher', 'church tower', '🔔', 4, "On voit le clocher depuis la route.", 'You can see the church tower from the road.' ),
      w('country-marche2', 'le marché du village', 'village market', '🧀', 2, "Le marché du village, c'est le dimanche matin.", 'The village market is on Sunday mornings.' ),
      w('country-calme2', 'le calme', 'peace and quiet', '🤫', 2, "Ce calme, ça change de Paris !", 'This quiet is quite a change from Paris!', { coll: ['au calme'] }),
    ],
  },
  {
    id: 'numbersx',
    title: 'Numbers & Quantities',
    description: 'From soixante-dix to des tas de.',
    entries: [
      w('numx-70', 'soixante-dix', 'seventy', '7️⃣0️⃣', 2, "Ma grand-mère a soixante-dix ans.", 'My grandmother is seventy.', { note: 'Literally "sixty-ten". Belgium says septante.' }),
      w('numx-80', 'quatre-vingts', 'eighty', '8️⃣0️⃣', 2, "Le billet coûte quatre-vingts euros.", 'The ticket costs eighty euros.', { note: '"Four twenties" — drops the s before another number.' }),
      w('numx-90', 'quatre-vingt-dix', 'ninety', '9️⃣0️⃣', 2, "Il roule à quatre-vingt-dix sur cette route.", 'He drives at ninety on this road.', { note: 'Switzerland says nonante.' }),
      w('numx-cent2', 'cent', 'a hundred', '💯', 1, "Il y avait au moins cent personnes.", 'There were at least a hundred people.', { coll: ['pour cent (%)'] }),
      w('numx-mille2', 'mille', 'a thousand', '🔢', 2, "Merci mille fois !", 'Thanks a thousand times!', { note: 'Invariable: deux mille.' }),
      w('numx-premier2', 'premier / première', 'first', '🥇', 1, "C'est la première fois que je viens.", 'It is the first time I have come.', { coll: ['au premier étage'] }),
      w('numx-dernier2', 'dernier / dernière', 'last', '🏁', 1, "C'est ma dernière semaine ici.", 'It is my last week here.', { coll: ['la semaine dernière'] }),
      w('numx-moitie2', 'la moitié', 'half', '➗', 2, "J'ai fait la moitié du travail.", 'I have done half the work.', { coll: ['à moitié'] }),
      w('numx-quart', 'le quart', 'quarter', '🕒', 2, "Il est trois heures et quart.", 'It is a quarter past three.', { coll: ['moins le quart'] }),
      w('numx-douzaine2', 'une douzaine', 'a dozen', '🥚', 3, "Une douzaine d'huîtres, s'il vous plaît.", 'A dozen oysters, please.' ),
      w('numx-dizaine', 'une dizaine', 'about ten', '🔟', 3, "Il reste une dizaine de places.", 'There are about ten seats left.', { note: '-aine = approximation: une vingtaine, une centaine.' }),
      w('numx-plupart', 'la plupart', 'most', '📊', 2, "La plupart des gens sont d'accord.", 'Most people agree.', { note: 'Keeps «des»: la plupart des…' }),
      w('numx-plusieurs2', 'plusieurs', 'several', '🖐️', 1, "J'ai essayé plusieurs fois.", 'I tried several times.' ),
      w('numx-quelques2', 'quelques', 'a few', '🤏', 1, "Attends quelques minutes.", 'Wait a few minutes.', { coll: ['quelques-uns'] }),
      w('numx-tas', 'des tas de', 'loads of (informal)', '⛰️', 3, "J'ai des tas de choses à te raconter !", 'I have loads to tell you!', { syn: ['plein de (fam.)'] }),
      w('numx-environ2', 'environ', 'about / roughly', '🎯', 2, "C'est à environ dix minutes à pied.", 'It is about ten minutes on foot.', { syn: ['à peu près'] }),
    ],
  },
  {
    id: 'travelx',
    title: 'Travel Essentials II',
    description: 'The words the airport actually uses.',
    entries: [
      w('travx-valise2', 'la valise', 'suitcase', '🧳', 2, "Ma valise fait dix-huit kilos… ça passe ?", 'My suitcase is eighteen kilos… will it be OK?', { coll: ['faire sa valise'] }),
      w('travx-bagage', 'les bagages', 'luggage', '🛄', 2, "Les bagages à main restent en cabine.", 'Hand luggage stays in the cabin.', { coll: ['le bagage à main'] }),
      w('travx-douane2', 'la douane', 'customs', '🛂', 3, "Rien à déclarer à la douane ?", 'Nothing to declare at customs?', { coll: ['passer la douane'] }),
      w('travx-embarquement', "l'embarquement", 'boarding', '🛫', 3, "L'embarquement commence porte 12.", 'Boarding starts at gate 12.', { coll: ['la carte d\'embarquement'] }),
      w('travx-retard2', 'le retard', 'delay', '⏰', 1, "Le vol a deux heures de retard.", 'The flight is two hours late.', { coll: ['en retard', 'avoir du retard'] }),
      w('travx-correspondance', 'la correspondance', 'connection', '🔀', 3, "Je rate ma correspondance à Lyon !", 'I am missing my connection in Lyon!', { note: 'Also = metro line change.' }),
      w('travx-guichet', 'le guichet', 'counter / ticket window', '🎫', 3, "Adressez-vous au guichet numéro trois.", 'Go to counter number three.', { coll: ['le guichet automatique (ATM)'] }),
      w('travx-horaires', 'les horaires', 'timetable', '🕐', 2, "Vérifie les horaires des trains.", 'Check the train times.', { coll: ['les horaires d\'ouverture'] }),
      w('travx-aller', 'un aller simple', 'a one-way ticket', '➡️', 2, "Un aller simple pour Marseille.", 'A one-way to Marseille.', { ant: ['un aller-retour (return)'] }),
      w('travx-allerretour', 'un aller-retour', 'a return ticket', '🔁', 2, "L'aller-retour est plus avantageux.", 'The return ticket is better value.' ),
      w('travx-quai2', 'le quai', 'platform', '🚉', 2, "Le train part du quai numéro cinq.", 'The train leaves from platform five.', { coll: ['sur le quai'] }),
      w('travx-composter', 'composter', 'to validate (a ticket)', '✅', 4, "N'oublie pas de composter ton billet !", 'Do not forget to validate your ticket!', { note: 'A very French ritual.' }),
      w('travx-location', 'la location de voiture', 'car rental', '🚗', 3, "La location est moins chère en ligne.", 'The rental is cheaper online.', { coll: ['louer une voiture'] }),
      w('travx-plan2', 'le plan', 'map (of a city)', '🗺️', 2, "Tu as un plan du métro ?", 'Do you have a metro map?', { note: 'Country map = une carte.' }),
      w('travx-perdu', 'perdu(e)', 'lost', '🧭', 1, "Excusez-moi, je suis un peu perdu…", 'Excuse me, I am a bit lost…', { coll: ['se perdre'] }),
      w('travx-frontiere2', 'la frontière', 'border', '🛃', 3, "On passe la frontière suisse à midi.", 'We cross the Swiss border at noon.' ),
    ],
  },
];
