// Vocabulary library, wave three: eight more rich themed packs (~80 cards)
// filling everyday gaps — quantities, weather, directions, school, technology,
// shopping, high-frequency adjectives and the connectors that glue speech
// together. Same card shape as vocab.js / vocab-extra.js.

const w = (id, fr, en, emoji, freq, example, exampleEn, extra = {}) =>
  ({ id, fr, en, emoji, freq, example, exampleEn, syn: [], ant: [], coll: [], note: '', ...extra });

export const CORE_VOCAB_PACKS = [
  {
    id: 'quantities',
    title: 'Quantities & Amounts',
    description: 'Say how much, how many and roughly how many.',
    entries: [
      w('qty-beaucoup', 'beaucoup', 'a lot / much', '📚', 1, "Il y a beaucoup de monde aujourd'hui.", 'There are a lot of people today.', { ant: ['peu'], coll: ['beaucoup de'] }),
      w('qty-peu', 'peu', 'little / few', '🤏', 1, "J'ai peu de temps ce matin.", 'I have little time this morning.', { ant: ['beaucoup'], coll: ['un peu de', 'peu à peu'] }),
      w('qty-assez', 'assez', 'enough / quite', '👌', 2, "On a assez de pain pour ce soir.", 'We have enough bread for tonight.', { coll: ['assez de', 'assez bien'] }),
      w('qty-trop', 'trop', 'too much / too many', '🥵', 1, "C'est trop cher pour moi.", "That's too expensive for me.", { coll: ['trop de'] }),
      w('qty-plusieurs', 'plusieurs', 'several', '🔢', 2, "J'ai essayé plusieurs fois.", 'I tried several times.', { syn: ['quelques'] }),
      w('qty-quelques', 'quelques', 'a few / some', '✋', 2, "Il reste quelques places.", 'A few seats are left.' ),
      w('qty-moitie', 'la moitié', 'half', '½', 3, "J'ai mangé la moitié du gâteau.", 'I ate half of the cake.', { coll: ['la moitié de'] }),
      w('qty-plupart', 'la plupart', 'most', '📊', 3, "La plupart des gens sont d'accord.", 'Most people agree.', { coll: ['la plupart du temps'] }),
      w('qty-environ', 'environ', 'about / roughly', '≈', 3, "Ça coûte environ vingt euros.", 'It costs about twenty euros.', { syn: ['à peu près'] }),
      w('qty-double', 'le double', 'double / twice as much', '✖️', 4, "Ils demandent le double du prix normal.", "They're asking double the normal price.", { ant: ['la moitié'] }),
    ],
  },
  {
    id: 'weather',
    title: 'Weather & Seasons',
    description: 'Talk about the sky, the seasons and the forecast.',
    entries: [
      w('wx-temps', 'le temps', 'the weather', '🌤️', 1, "Quel temps fait-il aujourd'hui ?", "What's the weather like today?", { note: 'Also means "time".', coll: ['il fait beau/mauvais'] }),
      w('wx-pleut', 'il pleut', 'it is raining', '🌧️', 1, "Prends un parapluie, il pleut.", "Take an umbrella, it's raining.", { coll: ['la pluie'] }),
      w('wx-soleil', 'le soleil', 'the sun', '☀️', 1, "Il y a du soleil ce matin.", "It's sunny this morning.", { coll: ['il fait soleil', 'un coup de soleil'] }),
      w('wx-neige', 'la neige', 'snow', '❄️', 2, "La neige a bloqué les routes.", 'The snow blocked the roads.', { coll: ['il neige'] }),
      w('wx-vent', 'le vent', 'wind', '💨', 2, "Il y a beaucoup de vent sur la côte.", "It's very windy on the coast.", { coll: ['un coup de vent'] }),
      w('wx-nuage', 'le nuage', 'cloud', '☁️', 3, "Le ciel est couvert de nuages.", 'The sky is covered with clouds.', { syn: ['nuageux (adj.)'] }),
      w('wx-orage', "l'orage", 'thunderstorm', '⛈️', 3, "Un orage arrive, rentrons.", "A storm is coming, let's go in.", { coll: ['un orage éclate'] }),
      w('wx-canicule', 'la canicule', 'heatwave', '🥵', 4, "On étouffe pendant la canicule.", "It's stifling during the heatwave.", { ant: ['le gel'] }),
      w('wx-printemps', 'le printemps', 'spring', '🌸', 2, "Au printemps, tout refleurit.", 'In spring, everything blossoms again.', { coll: ['au printemps'] }),
      w('wx-automne', "l'automne", 'autumn / fall', '🍂', 2, "Les feuilles tombent en automne.", 'The leaves fall in autumn.', { coll: ['en automne'] }),
    ],
  },
  {
    id: 'directions',
    title: 'Directions & Places',
    description: 'Ask the way and describe where things are.',
    entries: [
      w('dir-gauche', 'à gauche', 'on / to the left', '⬅️', 1, "Tournez à gauche après la boulangerie.", 'Turn left after the bakery.', { ant: ['à droite'] }),
      w('dir-droite', 'à droite', 'on / to the right', '➡️', 1, "La banque est à droite.", 'The bank is on the right.', { ant: ['à gauche'] }),
      w('dir-toutdroit', 'tout droit', 'straight ahead', '⬆️', 2, "Continuez tout droit jusqu'au feu.", 'Keep going straight to the traffic light.' ),
      w('dir-enface', 'en face', 'opposite / across', '↔️', 2, "La pharmacie est juste en face.", "The pharmacy is right across.", { coll: ['en face de'] }),
      w('dir-acote', 'à côté', 'next to / nearby', '🔀', 2, "Il habite à côté de chez moi.", 'He lives next to my place.', { coll: ['à côté de'] }),
      w('dir-loin', 'loin', 'far', '🛣️', 1, "C'est encore loin ?", 'Is it still far?', { ant: ['près'] }),
      w('dir-pres', 'près', 'near / close', '📍', 1, "On est tout près de la gare.", "We're very close to the station.", { ant: ['loin'], coll: ['près de'] }),
      w('dir-coin', 'le coin', 'the corner / area', '📐', 3, "Le café au coin de la rue.", 'The café on the street corner.', { coll: ['au coin de', 'dans le coin'] }),
      w('dir-carrefour', 'le carrefour', 'crossroads / junction', '🚦', 4, "Tournez au prochain carrefour.", 'Turn at the next junction.' ),
      w('dir-plan', 'le plan', 'map (of a town)', '🗺️', 3, "Tu as un plan de la ville ?", 'Do you have a map of the city?', { syn: ['la carte'] }),
    ],
  },
  {
    id: 'school',
    title: 'Classroom & Exams',
    description: 'Classrooms, exams and everything you learn.',
    entries: [
      w('edu-ecole', "l'école", 'school', '🏫', 1, "Les enfants vont à l'école à pied.", 'The children walk to school.', { coll: ["à l'école"] }),
      w('edu-cours', 'le cours', 'class / course', '📖', 1, "J'ai un cours de français à midi.", 'I have a French class at noon.', { coll: ['suivre un cours'] }),
      w('edu-eleve', "l'élève", 'pupil / student', '🧑‍🎓', 2, "C'est une élève très sérieuse.", "She's a very diligent student.", { syn: ["l'étudiant (higher ed)"] }),
      w('edu-examen', "l'examen", 'exam', '📝', 2, "Je révise pour mon examen de demain.", "I'm revising for my exam tomorrow.", { coll: ['passer un examen', 'réussir/rater un examen'], note: '“passer un examen” = to sit it, not to pass.' }),
      w('edu-note', 'la note', 'grade / mark', '💯', 2, "J'ai eu une bonne note en maths.", 'I got a good grade in maths.', { note: 'Also means "note / bill".' }),
      w('edu-apprendre', 'apprendre', 'to learn', '🧠', 1, "J'apprends l'espagnol depuis un an.", "I've been learning Spanish for a year.", { coll: ['apprendre par cœur'] }),
      w('edu-enseigner', 'enseigner', 'to teach', '👩‍🏫', 3, "Elle enseigne l'histoire au lycée.", 'She teaches history at the high school.' ),
      w('edu-devoir', 'les devoirs', 'homework', '🗂️', 2, "Tu as fait tes devoirs ?", 'Have you done your homework?', { note: 'Singular “le devoir” = duty.' }),
      w('edu-matiere', 'la matière', 'subject', '🔬', 3, "Ma matière préférée, c'est la biologie.", 'My favourite subject is biology.' ),
      w('edu-fac', 'la fac', 'uni (informal)', '🎓', 3, "Elle est en deuxième année à la fac.", "She's in her second year at uni.", { note: 'Short for « la faculté ».' }),
    ],
  },
  {
    id: 'cooking',
    title: 'Recipes & Cooking Verbs',
    description: 'Follow a recipe and talk about what you cook.',
    entries: [
      w('cook-recette', 'la recette', 'recipe', '📜', 2, "Tu me donnes la recette de ce gâteau ?", 'Will you give me the recipe for this cake?' ),
      w('cook-couper', 'couper', 'to cut / chop', '🔪', 2, "Coupez les oignons en petits morceaux.", 'Chop the onions into small pieces.', { coll: ['couper en dés'] }),
      w('cook-melanger', 'mélanger', 'to mix', '🥣', 3, "Mélangez la farine et le sucre.", 'Mix the flour and the sugar.', { syn: ['remuer'] }),
      w('cook-ajouter', 'ajouter', 'to add', '➕', 2, "Ajoutez une pincée de sel.", 'Add a pinch of salt.', { ant: ['retirer'] }),
      w('cook-verser', 'verser', 'to pour', '🫗', 3, "Versez le lait doucement.", 'Pour the milk slowly.' ),
      w('cook-cuire', 'cuire', 'to cook (in heat)', '🍳', 2, "Laissez cuire vingt minutes.", 'Let it cook for twenty minutes.', { coll: ['cuire au four', 'faire cuire'] }),
      w('cook-eplucher', 'éplucher', 'to peel', '🥔', 4, "Il faut éplucher les pommes de terre.", 'You need to peel the potatoes.', { syn: ['peler'] }),
      w('cook-four', 'le four', 'oven', '🔥', 2, "Préchauffez le four à 180 degrés.", 'Preheat the oven to 180 degrees.', { coll: ['au four', 'un four à micro-ondes'] }),
      w('cook-casserole', 'la casserole', 'saucepan', '🍲', 3, "Fais bouillir l'eau dans la casserole.", 'Boil the water in the saucepan.', { syn: ['la poêle (frying pan)'] }),
      w('cook-gouter', 'assaisonner', 'to season', '🧂', 4, "N'oublie pas d'assaisonner la sauce.", "Don't forget to season the sauce.", { coll: ['sel et poivre'] }),
    ],
  },
  {
    id: 'shopping2',
    title: 'Prices & Paying',
    description: 'Prices, deals and paying the bill.',
    entries: [
      w('shp-prix', 'le prix', 'price', '🏷️', 1, "Quel est le prix de ce manteau ?", "What's the price of this coat?", { coll: ['à moitié prix'] }),
      w('shp-cher', 'cher', 'expensive / dear', '💸', 1, "C'est un peu cher pour un café.", "That's a bit expensive for a coffee.", { ant: ['bon marché'] }),
      w('shp-solde', 'les soldes', 'the sales', '🔖', 2, "J'ai acheté ces bottes en solde.", 'I bought these boots in the sale.', { coll: ['en solde'] }),
      w('shp-remise', 'la remise', 'discount', '➖', 3, "Ils font une remise de dix pour cent.", "They're giving a ten percent discount.", { syn: ['la réduction'] }),
      w('shp-monnaie', 'la monnaie', 'change / currency', '🪙', 2, "Vous avez la monnaie sur vingt euros ?", 'Do you have change for twenty euros?', { note: 'Also “currency”.' }),
      w('shp-depenser', 'dépenser', 'to spend', '🛍️', 2, "On a trop dépensé ce mois-ci.", 'We spent too much this month.', { ant: ['économiser'] }),
      w('shp-economiser', 'économiser', 'to save (money)', '🐷', 3, "J'économise pour un voyage.", "I'm saving up for a trip.", { ant: ['dépenser'] }),
      w('shp-recu', 'le reçu', 'receipt', '🧾', 3, "Gardez le reçu pour l'échange.", 'Keep the receipt for the exchange.', { syn: ['le ticket de caisse'] }),
      w('shp-gratuit', 'gratuit', 'free (no cost)', '🆓', 2, "La livraison est gratuite dès trente euros.", 'Delivery is free from thirty euros.', { ant: ['payant'] }),
      w('shp-couter', 'coûter', 'to cost', '💰', 1, "Ça coûte combien ?", 'How much does it cost?', { coll: ['coûter cher'] }),
    ],
  },
  {
    id: 'adjectives',
    title: 'Everyday Adjectives',
    description: 'The describing words you reach for constantly.',
    entries: [
      w('adj-bon', 'bon', 'good', '👍', 1, "C'est un très bon restaurant.", "It's a very good restaurant.", { ant: ['mauvais'] }),
      w('adj-mauvais', 'mauvais', 'bad', '👎', 1, "Il fait un mauvais temps aujourd'hui.", "The weather is bad today.", { ant: ['bon'] }),
      w('adj-grand', 'grand', 'big / tall', '📏', 1, "Ils ont une grande maison.", 'They have a big house.', { ant: ['petit'] }),
      w('adj-petit', 'petit', 'small / little', '🐭', 1, "Un petit café, s'il vous plaît.", 'A small coffee, please.', { ant: ['grand'] }),
      w('adj-beau', 'beau', 'beautiful / handsome', '😍', 1, "Quel beau paysage !", 'What a beautiful landscape!', { syn: ['joli'], note: 'bel before a vowel: un bel homme.' }),
      w('adj-facile', 'facile', 'easy', '✅', 2, "L'exercice était plutôt facile.", 'The exercise was rather easy.', { ant: ['difficile'] }),
      w('adj-difficile', 'difficile', 'difficult', '🧗', 2, "C'est difficile à prononcer.", "It's difficult to pronounce.", { ant: ['facile'] }),
      w('adj-nouveau', 'nouveau', 'new', '🆕', 1, "Tu as vu son nouveau vélo ?", 'Have you seen his new bike?', { ant: ['vieux'], note: 'nouvel before a vowel.' }),
      w('adj-vieux', 'vieux', 'old', '👴', 1, "C'est un vieux quartier de la ville.", "It's an old neighbourhood of the city.", { ant: ['nouveau', 'jeune'], note: 'vieil before a vowel.' }),
      w('adj-important', 'important', 'important', '❗', 2, "J'ai une réunion importante demain.", 'I have an important meeting tomorrow.' ),
    ],
  },
  {
    id: 'connectors',
    title: 'Connectors & Discourse',
    description: 'The little words that make speech flow.',
    entries: [
      w('con-mais', 'mais', 'but', '↩️', 1, "J'aimerais venir, mais je travaille.", "I'd like to come, but I'm working.", { ant: ['et'] }),
      w('con-parceque', 'parce que', 'because', '❓', 1, "Je reste parce que je suis fatigué.", "I'm staying because I'm tired.", { syn: ['car'] }),
      w('con-donc', 'donc', 'so / therefore', '➡️', 1, "Il pleut, donc on reste ici.", "It's raining, so we're staying here.", { syn: ['alors'] }),
      w('con-alors', 'alors', 'then / so', '⏭️', 1, "Alors, qu'est-ce qu'on fait ?", 'So, what shall we do?' ),
      w('con-cependant', 'cependant', 'however', '⚖️', 4, "C'est cher ; cependant, la qualité est là.", "It's expensive; however, the quality is there.", { syn: ['pourtant'] }),
      w('con-dabord', "d'abord", 'first (of all)', '1️⃣', 2, "D'abord, on prépare la pâte.", 'First, we prepare the dough.', { ant: ['enfin'] }),
      w('con-ensuite', 'ensuite', 'then / next', '2️⃣', 2, "Ensuite, ajoutez les œufs.", 'Then, add the eggs.', { syn: ['puis'] }),
      w('con-enfin', 'enfin', 'finally / at last', '🏁', 2, "Enfin, on met au four.", 'Finally, put it in the oven.', { ant: ["d'abord"] }),
      w('con-parexemple', 'par exemple', 'for example', '💡', 2, "Prends un fruit, une pomme par exemple.", 'Have some fruit, an apple for example.' ),
      w('con-enfait', 'en fait', 'actually / in fact', '🔎', 2, "En fait, je ne suis pas d'accord.", "Actually, I don't agree." ),
    ],
  },
  {
    id: 'questions',
    title: 'Question Words',
    description: 'Ask who, what, where, when, why and how.',
    entries: [
      w('q-qui', 'qui', 'who', '🙋', 1, "Qui a pris mon stylo ?", 'Who took my pen?' ),
      w('q-que', 'que / quoi', 'what', '❓', 1, "Qu'est-ce que tu fais ?", 'What are you doing?', { note: '“quoi” at the end: Tu fais quoi ?' }),
      w('q-ou', 'où', 'where', '📍', 1, "Où est la sortie ?", 'Where is the exit?' ),
      w('q-quand', 'quand', 'when', '🕐', 1, "Quand est-ce qu'on part ?", 'When are we leaving?' ),
      w('q-comment', 'comment', 'how', '🔧', 1, "Comment ça marche ?", 'How does it work?', { coll: ['comment ça va'] }),
      w('q-pourquoi', 'pourquoi', 'why', '🤔', 1, "Pourquoi tu ris ?", 'Why are you laughing?', { note: 'Answer with « parce que ».' }),
      w('q-combien', 'combien', 'how much / many', '💰', 1, "Ça fait combien ?", 'How much is it?', { coll: ['combien de'] }),
      w('q-quel', 'quel / quelle', 'which / what', '👉', 1, "Quel jour sommes-nous ?", 'What day is it?', { note: 'Agrees: quel, quelle, quels, quelles.' }),
      w('q-lequel', 'lequel', 'which one', '🔀', 3, "Lequel préfères-tu ?", 'Which one do you prefer?' ),
      w('q-estceque', 'est-ce que', '(question marker)', '❔', 1, "Est-ce que tu viens ?", 'Are you coming?', { note: 'Turns a statement into a yes/no question.' }),
    ],
  },
  {
    id: 'timewords',
    title: 'Time Expressions',
    description: 'When, how often and for how long.',
    entries: [
      w('te-maintenant', 'maintenant', 'now', '⏱️', 1, "On y va maintenant ?", 'Shall we go now?' ),
      w('te-bientot', 'bientôt', 'soon', '⏳', 2, "Le train arrive bientôt.", 'The train is arriving soon.' ),
      w('te-deja', 'déjà', 'already', '✅', 2, "Tu as déjà fini ?", 'Have you already finished?', { ant: ['pas encore'] }),
      w('te-encore', 'encore', 'still / again / yet', '🔁', 1, "Il dort encore.", "He's still asleep.", { coll: ['pas encore'] }),
      w('te-toujours', 'toujours', 'always / still', '♾️', 1, "Elle est toujours en retard.", "She's always late.", { ant: ['jamais'] }),
      w('te-souvent', 'souvent', 'often', '🔂', 2, "On se voit souvent.", 'We see each other often.', { ant: ['rarement'] }),
      w('te-parfois', 'parfois', 'sometimes', '🎲', 2, "Parfois, je travaille le samedi.", 'Sometimes I work on Saturdays.', { syn: ['quelquefois'] }),
      w('te-tot', 'tôt', 'early', '🌅', 2, "Je me lève tôt le matin.", 'I get up early in the morning.', { ant: ['tard'] }),
      w('te-tard', 'tard', 'late', '🌙', 2, "Il est rentré très tard.", 'He got home very late.', { ant: ['tôt'] }),
      w('te-depuis', 'depuis', 'since / for', '📆', 2, "J'habite ici depuis deux ans.", "I've lived here for two years.", { note: 'Use with the present tense in French.' }),
    ],
  },
];
